// Code generated by cmd/codegen. DO NOT EDIT.
// Source: backend/internal/bootstrap/system_tables.json
// Generated at: 2026-01-05T12:48:09+08:00

package models

import (
	"encoding/json"
	"time"
)

// Ensure imports are used
var (
	_ json.RawMessage
	_ time.Time
)

// GenSystemApp represents the _System_App table (generated).
// Application configurations
type GenSystemApp struct {
	ID string `json:"id"`
	Name string `json:"name"`
	Label string `json:"label"`
	Description string `json:"description"`
	Icon string `json:"icon"`
	Color string `json:"color"`
	NavigationItems json.RawMessage `json:"navigation_items"`
	IsDefault bool `json:"is_default"`
	CreatedDate time.Time `json:"created_date"`
	LastModifiedDate time.Time `json:"last_modified_date"`
}

// GenSystemDashboard represents the _System_Dashboard table (generated).
// Dashboard configurations with widget-based layouts
type GenSystemDashboard struct {
	ID string `json:"id"`
	Name string `json:"name"`
	Description string `json:"description"`
	Layout string `json:"layout"`
	Widgets json.RawMessage `json:"widgets"`
	CreatedDate time.Time `json:"created_date"`
	LastModifiedDate time.Time `json:"last_modified_date"`
}

// GenSystemField represents the _System_Field table (generated).
// Field metadata definitions
type GenSystemField struct {
	ID string `json:"id"`
	ObjectID string `json:"object_id"`
	APIName string `json:"api_name"`
	Label string `json:"label"`
	Type string `json:"type"`
	Required bool `json:"required"`
	Unique bool `json:"unique"`
	IsSystem bool `json:"is_system"`
	IsNameField bool `json:"is_name_field"`
	Indexed bool `json:"indexed"`
	Options json.RawMessage `json:"options,omitempty"`
	ReferenceTo *string `json:"reference_to,omitempty"`
	DeleteRule *string `json:"delete_rule,omitempty"`
	Formula *string `json:"formula,omitempty"`
	ReturnType *string `json:"return_type,omitempty"`
	DefaultValue *string `json:"default_value,omitempty"`
	HelpText *string `json:"help_text,omitempty"`
	Description *string `json:"description,omitempty"`
	TrackHistory bool `json:"track_history"`
	MinValue *float64 `json:"min_value,omitempty"`
	MaxValue *float64 `json:"max_value,omitempty"`
	MinLength *int `json:"min_length,omitempty"`
	MaxLength *int `json:"max_length,omitempty"`
	Regex *string `json:"regex,omitempty"`
	RegexMessage *string `json:"regex_message,omitempty"`
	Validator *string `json:"validator,omitempty"`
	ControllingField *string `json:"controlling_field,omitempty"`
	PicklistDependency json.RawMessage `json:"picklist_dependency,omitempty"`
	RollupConfig json.RawMessage `json:"rollup_config,omitempty"`
	IsMasterDetail bool `json:"is_master_detail"`
	RelationshipName *string `json:"relationship_name,omitempty"`
	IsDeleted bool `json:"is_deleted"`
	OwnerID *string `json:"owner_id,omitempty"`
	CreatedByID *string `json:"created_by_id,omitempty"`
	LastModifiedByID *string `json:"last_modified_by_id,omitempty"`
	CreatedDate time.Time `json:"created_date"`
	LastModifiedDate time.Time `json:"last_modified_date"`
}

// GenSystemFlow represents the _System_Flow table (generated).
// Workflow automation definitions
type GenSystemFlow struct {
	ID string `json:"id"`
	Name string `json:"name"`
	TriggerObject string `json:"trigger_object"`
	TriggerType string `json:"trigger_type"`
	TriggerCondition string `json:"trigger_condition"`
	ActionType string `json:"action_type"`
	ActionConfig json.RawMessage `json:"action_config"`
	FlowType string `json:"flow_type"`
	Description *string `json:"description,omitempty"`
	Status string `json:"status"`
	CreatedDate time.Time `json:"created_date"`
	CreatedByID *string `json:"created_by_id,omitempty"`
	LastModifiedByID *string `json:"last_modified_by_id,omitempty"`
	OwnerID *string `json:"owner_id,omitempty"`
	IsDeleted bool `json:"is_deleted"`
	Schedule *string `json:"schedule,omitempty"`
	ScheduleTimezone *string `json:"schedule_timezone,omitempty"`
	LastRunAt *time.Time `json:"last_run_at,omitempty"`
	NextRunAt *time.Time `json:"next_run_at,omitempty"`
	IsRunning bool `json:"is_running"`
	LastModifiedDate time.Time `json:"last_modified_date"`
}

// GenSystemLayout represents the _System_Layout table (generated).
// Page layout configurations
type GenSystemLayout struct {
	ID string `json:"id"`
	ObjectAPIName string `json:"object_api_name"`
	Config json.RawMessage `json:"config"`
	CreatedDate time.Time `json:"created_date"`
	LastModifiedDate time.Time `json:"last_modified_date"`
}

// GenSystemListView represents the _System_ListView table (generated).
// List view configurations
type GenSystemListView struct {
	ID string `json:"id"`
	ObjectAPIName string `json:"object_api_name"`
	Label string `json:"label"`
	FilterExpr *string `json:"filter_expr,omitempty"`
	Fields json.RawMessage `json:"fields"`
	CreatedDate time.Time `json:"created_date"`
	LastModifiedDate time.Time `json:"last_modified_date"`
}

// GenSystemObject represents the _System_Object table (generated).
// Object metadata definitions
type GenSystemObject struct {
	ID string `json:"id"`
	APIName string `json:"api_name"`
	TableType string `json:"table_type"`
	Label string `json:"label"`
	PluralLabel *string `json:"plural_label,omitempty"`
	AppID *string `json:"app_id,omitempty"`
	Icon *string `json:"icon,omitempty"`
	Description string `json:"description"`
	ThemeColor *string `json:"theme_color,omitempty"`
	IsCustom bool `json:"is_custom"`
	SharingModel string `json:"sharing_model"`
	PathField *string `json:"path_field,omitempty"`
	ListFields json.RawMessage `json:"list_fields,omitempty"`
	IsDeleted bool `json:"is_deleted"`
	OwnerID *string `json:"owner_id,omitempty"`
	CreatedByID *string `json:"created_by_id,omitempty"`
	LastModifiedByID *string `json:"last_modified_by_id,omitempty"`
	CreatedDate time.Time `json:"created_date"`
	LastModifiedDate time.Time `json:"last_modified_date"`
}

// GenSystemProfile represents the _System_Profile table (generated).
// User profiles and permission sets
type GenSystemProfile struct {
	ID string `json:"id"`
	Name string `json:"name"`
	Description string `json:"description"`
	IsActive bool `json:"is_active"`
	IsSystem bool `json:"is_system"`
	IsDeleted bool `json:"is_deleted"`
	OwnerID *string `json:"owner_id,omitempty"`
	CreatedByID *string `json:"created_by_id,omitempty"`
	LastModifiedByID *string `json:"last_modified_by_id,omitempty"`
	CreatedDate time.Time `json:"created_date"`
	LastModifiedDate time.Time `json:"last_modified_date"`
}

// GenSystemRole represents the _System_Role table (generated).
// Role hierarchy for access control
type GenSystemRole struct {
	ID string `json:"id"`
	Name string `json:"name"`
	Description string `json:"description"`
	ParentRoleID *string `json:"parent_role_id,omitempty"`
	IsActive bool `json:"is_active"`
	IsDeleted bool `json:"is_deleted"`
	OwnerID *string `json:"owner_id,omitempty"`
	CreatedByID *string `json:"created_by_id,omitempty"`
	LastModifiedByID *string `json:"last_modified_by_id,omitempty"`
	CreatedDate time.Time `json:"created_date"`
	LastModifiedDate time.Time `json:"last_modified_date"`
}

// GenSystemUser represents the _System_User table (generated).
// System users
type GenSystemUser struct {
	ID string `json:"id"`
	Username string `json:"username"`
	Email string `json:"email"`
	FirstName string `json:"first_name"`
	LastName string `json:"last_name"`
	Phone *string `json:"phone,omitempty"`
	ProfileID string `json:"profile_id"`
	RoleID *string `json:"role_id,omitempty"`
	IsActive bool `json:"is_active"`
	IsDeleted bool `json:"is_deleted"`
	OwnerID *string `json:"owner_id,omitempty"`
	CreatedByID *string `json:"created_by_id,omitempty"`
	LastModifiedByID *string `json:"last_modified_by_id,omitempty"`
	LastLoginDate *time.Time `json:"last_login_date,omitempty"`
	CreatedDate time.Time `json:"created_date"`
	LastModifiedDate time.Time `json:"last_modified_date"`
}

// GenSystemValidation represents the _System_Validation table (generated).
// Validation rule definitions
type GenSystemValidation struct {
	ID string `json:"id"`
	ObjectAPIName string `json:"object_api_name"`
	Name string `json:"name"`
	Active bool `json:"active"`
	Condition string `json:"condition"`
	ErrorMessage string `json:"error_message"`
	CreatedDate time.Time `json:"created_date"`
	LastModifiedDate time.Time `json:"last_modified_date"`
}

