// Code generated by cmd/tools/gen_constants. DO NOT EDIT.
// Source: shared/constants/system.json
// Generated at: 2025-12-28T20:17:49+08:00

package constants

const (
	// System Tables (Generated)
	TableAction = "_System_Action"
	TableActionHandler = "_System_ActionHandler"
	TableAPIEndpoint = "_System_ApiEndpoint"
	TableApp = "_System_App"
	TableConfig = "_System_Config"
	TableDashboard = "_System_Dashboard"
	TableEmailTemplate = "_System_EmailTemplate"
	TableField = "_System_Field"
	TableFieldPerms = "_System_FieldPerms"
	TableFieldRendering = "_System_FieldRendering"
	TableFlow = "_System_Flow"
	TableFormulaFunction = "_System_FormulaFunction"
	TableLayout = "_System_Layout"
	TableLimit = "_System_Limit"
	TableListView = "_System_ListView"
	TableLog = "_System_Log"
	TableNavigationMenu = "_System_NavigationMenu"
	TableObject = "_System_Object"
	TableObjectPerms = "_System_ObjectPerms"
	TableProfile = "_System_Profile"
	TableProfileLayout = "_System_ProfileLayout"
	TablePrompt = "_System_Prompt"
	TableRecent = "_System_Recent"
	TableRecordType = "_System_RecordType"
	TableRecycleBin = "_System_RecycleBin"
	TableRelationship = "_System_Relationship"
	TableRole = "_System_Role"
	TableSetupPage = "_System_SetupPage"
	TableSharingRule = "_System_SharingRule"
	TableTab = "_System_Tab"
	TableTransformation = "_System_Transformation"
	TableUIComponent = "_System_UIComponent"
	TableUITheme = "_System_UITheme"
	TableUser = "_System_User"
	TableValidation = "_System_Validation"
	TableWebhook = "_System_Webhook"

	// System Fields (Generated)
	FieldCreatedByID = "created_by_id"
	FieldCreatedDate = "created_date"
	FieldID = "id"
	FieldIsDeleted = "is_deleted"
	FieldLastModifiedByID = "last_modified_by_id"
	FieldLastModifiedDate = "last_modified_date"
	FieldName = "name"
	FieldOwnerID = "owner_id"

	// Permissions (Generated)
	PermissionCreate = "create"
	PermissionDelete = "delete"
	PermissionEdit = "edit"
	PermissionModifyAll = "modifyAll"
	PermissionRead = "read"
	PermissionViewAll = "viewAll"
)
