// Code generated by cmd/codegen. DO NOT EDIT.
// Source: backend/internal/bootstrap/system_tables.json
// Generated at: 2026-01-12T06:46:13+08:00

// ==================== System Table Names ====================

export const SYSTEM_TABLE_NAMES = {
    SYSTEM_AI_CONVERSATION: '_System_AI_Conversation',
    SYSTEM_ACTION: '_System_Action',
    SYSTEM_APP: '_System_App',
    SYSTEM_APPROVALPROCESS: '_System_ApprovalProcess',
    SYSTEM_APPROVALWORKITEM: '_System_ApprovalWorkItem',
    SYSTEM_AUDITLOG: '_System_AuditLog',
    SYSTEM_AUTONUMBER: '_System_AutoNumber',
    SYSTEM_COMMENT: '_System_Comment',
    SYSTEM_CONFIG: '_System_Config',
    SYSTEM_DASHBOARD: '_System_Dashboard',
    SYSTEM_EMAILTEMPLATE: '_System_EmailTemplate',
    SYSTEM_FEEDITEM: '_System_FeedItem',
    SYSTEM_FIELD: '_System_Field',
    SYSTEM_FIELDDEPENDENCY: '_System_FieldDependency',
    SYSTEM_FIELDPERMS: '_System_FieldPerms',
    SYSTEM_FILE: '_System_File',
    SYSTEM_FLOW: '_System_Flow',
    SYSTEM_FLOWINSTANCE: '_System_FlowInstance',
    SYSTEM_FLOWSTEP: '_System_FlowStep',
    SYSTEM_GROUP: '_System_Group',
    SYSTEM_GROUPMEMBER: '_System_GroupMember',
    SYSTEM_LAYOUT: '_System_Layout',
    SYSTEM_LISTVIEW: '_System_ListView',
    SYSTEM_LOG: '_System_Log',
    SYSTEM_NOTIFICATION: '_System_Notification',
    SYSTEM_OBJECT: '_System_Object',
    SYSTEM_OBJECTPERMS: '_System_ObjectPerms',
    SYSTEM_OUTBOXEVENT: '_System_OutboxEvent',
    SYSTEM_PERMISSIONSET: '_System_PermissionSet',
    SYSTEM_PERMISSIONSETASSIGNMENT: '_System_PermissionSetAssignment',
    SYSTEM_PROFILE: '_System_Profile',
    SYSTEM_PROFILELAYOUT: '_System_ProfileLayout',
    SYSTEM_RECENT: '_System_Recent',
    SYSTEM_RECORDSHARE: '_System_RecordShare',
    SYSTEM_RECORDTYPE: '_System_RecordType',
    SYSTEM_RECYCLEBIN: '_System_RecycleBin',
    SYSTEM_RELATIONSHIP: '_System_Relationship',
    SYSTEM_ROLE: '_System_Role',
    SYSTEM_SESSION: '_System_Session',
    SYSTEM_SETUPPAGE: '_System_SetupPage',
    SYSTEM_SHARINGRULE: '_System_SharingRule',
    SYSTEM_SYSTEMLOG: '_System_SystemLog',
    SYSTEM_TABLE: '_System_Table',
    SYSTEM_TEAMMEMBER: '_System_TeamMember',
    SYSTEM_THEME: '_System_Theme',
    SYSTEM_UICOMPONENT: '_System_UIComponent',
    SYSTEM_USER: '_System_User',
    SYSTEM_VALIDATION: '_System_Validation',
    SYSTEM_WEBHOOK: '_System_Webhook',
} as const;

export type SystemTableName = typeof SYSTEM_TABLE_NAMES[keyof typeof SYSTEM_TABLE_NAMES];

// ==================== Common Fields ====================

export const COMMON_FIELDS = {
    CREATED_BY_ID: '__sys_gen_created_by_id',
    CREATED_DATE: '__sys_gen_created_date',
    ID: '__sys_gen_id',
    IS_DELETED: '__sys_gen_is_deleted',
    LAST_MODIFIED_BY_ID: '__sys_gen_last_modified_by_id',
    LAST_MODIFIED_DATE: '__sys_gen_last_modified_date',
    OWNER_ID: '__sys_gen_owner_id',
    ACTION_TYPE: 'action_type',
    API_NAME: 'api_name',
    APPROVED_BY_ID: 'approved_by_id',
    APPROVED_DATE: 'approved_date',
    APPROVER_ID: 'approver_id',
    APPROVER_TYPE: 'approver_type',
    CATEGORY: 'category',
    COMMENTS: 'comments',
    CONDITION: 'condition',
    CONFIG: 'config',
    CREATED_BY: 'created_by',
    CURRENT_STEP_ID: 'current_step_id',
    DELETED_BY: 'deleted_by',
    DELETED_DATE: 'deleted_date',
    DESCRIPTION: 'description',
    DETAILS: 'details',
    EMAIL: 'email',
    ENTRY_CRITERIA: 'entry_criteria',
    EXPIRES_AT: 'expires_at',
    FILTERS: 'filters',
    FIRST_NAME: 'first_name',
    FLOW_ID: 'flow_id',
    FLOW_INSTANCE_ID: 'flow_instance_id',
    FLOW_STEP_ID: 'flow_step_id',
    IP_ADDRESS: 'ip_address',
    IS_ACTIVE: 'is_active',
    IS_CUSTOM: 'is_custom',
    IS_MANAGED: 'is_managed',
    IS_REVOKED: 'is_revoked',
    IS_SECRET: 'is_secret',
    IS_SYSTEM: 'is_system',
    KEY_NAME: 'key_name',
    LABEL: 'label',
    LAST_ACTIVITY: 'last_activity',
    LAST_LOGIN_DATE: 'last_login_date',
    LAST_NAME: 'last_name',
    LEVEL: 'level',
    MESSAGE: 'message',
    NAME: 'name',
    OBJECT_API_NAME: 'object_api_name',
    OBJECT_ID: 'object_id',
    ON_FAILURE_STEP: 'on_failure_step',
    ON_SUCCESS_STEP: 'on_success_step',
    PASSWORD: 'password',
    PERMISSION_SET_ID: 'permission_set_id',
    PLURAL_LABEL: 'plural_label',
    PROCESS_ID: 'process_id',
    PROFILE_ID: 'profile_id',
    RECORD_ID: 'record_id',
    RECORD_NAME: 'record_name',
    REFERENCE_TO: 'reference_to',
    REQUIRED: 'required',
    ROLE_ID: 'role_id',
    SCHEMA_VERSION: 'schema_version',
    SORT_ORDER: 'sort_order',
    SOURCE: 'source',
    STATUS: 'status',
    STEP_NAME: 'step_name',
    STEP_ORDER: 'step_order',
    STEP_TYPE: 'step_type',
    SUBJECT: 'subject',
    SUBMITTED_DATE: 'submitted_date',
    TABLE_NAME: 'table_name',
    TABLE_TYPE: 'table_type',
    TIMESTAMP: 'timestamp',
    TOKEN: 'token',
    TRIGGER_OBJECT: 'trigger_object',
    TRIGGER_TYPE: 'trigger_type',
    TYPE: 'type',
    UNIQUE: 'unique',
    USER_AGENT: 'user_agent',
    USER_ID: 'user_id',
    USERNAME: 'username',
    VALUE: 'value',
    WORK_ITEM_ID: 'work_item_id',
} as const;

// ==================== Field Constants ====================

export const FIELDS_SYSTEM_AI_CONVERSATION = {
    CREATED_DATE: '__sys_gen_created_date',
    ID: '__sys_gen_id',
    IS_DELETED: '__sys_gen_is_deleted',
    LAST_MODIFIED_DATE: '__sys_gen_last_modified_date',
    IS_ACTIVE: 'is_active',
    MESSAGES: 'messages',
    TITLE: 'title',
    USER_ID: 'user_id',
} as const;

export const FIELDS_SYSTEM_ACTION = {
    CREATED_DATE: '__sys_gen_created_date',
    ID: '__sys_gen_id',
    LAST_MODIFIED_DATE: '__sys_gen_last_modified_date',
    CONFIG: 'config',
    ICON: 'icon',
    LABEL: 'label',
    NAME: 'name',
    OBJECT_API_NAME: 'object_api_name',
    TARGET_OBJECT: 'target_object',
    TYPE: 'type',
} as const;

export const FIELDS_SYSTEM_APP = {
    CREATED_DATE: '__sys_gen_created_date',
    ID: '__sys_gen_id',
    LAST_MODIFIED_DATE: '__sys_gen_last_modified_date',
    COLOR: 'color',
    DESCRIPTION: 'description',
    ICON: 'icon',
    IS_DEFAULT: 'is_default',
    LABEL: 'label',
    NAME: 'name',
    NAVIGATION_ITEMS: 'navigation_items',
} as const;

export const FIELDS_SYSTEM_APPROVALPROCESS = {
    CREATED_BY_ID: '__sys_gen_created_by_id',
    CREATED_DATE: '__sys_gen_created_date',
    ID: '__sys_gen_id',
    IS_DELETED: '__sys_gen_is_deleted',
    LAST_MODIFIED_BY_ID: '__sys_gen_last_modified_by_id',
    LAST_MODIFIED_DATE: '__sys_gen_last_modified_date',
    OWNER_ID: '__sys_gen_owner_id',
    APPROVER_ID: 'approver_id',
    APPROVER_TYPE: 'approver_type',
    DESCRIPTION: 'description',
    ENTRY_CRITERIA: 'entry_criteria',
    IS_ACTIVE: 'is_active',
    NAME: 'name',
    OBJECT_API_NAME: 'object_api_name',
} as const;

export const FIELDS_SYSTEM_APPROVALWORKITEM = {
    CREATED_BY_ID: '__sys_gen_created_by_id',
    CREATED_DATE: '__sys_gen_created_date',
    ID: '__sys_gen_id',
    IS_DELETED: '__sys_gen_is_deleted',
    LAST_MODIFIED_BY_ID: '__sys_gen_last_modified_by_id',
    LAST_MODIFIED_DATE: '__sys_gen_last_modified_date',
    OWNER_ID: '__sys_gen_owner_id',
    APPROVED_BY_ID: 'approved_by_id',
    APPROVED_DATE: 'approved_date',
    APPROVER_ID: 'approver_id',
    COMMENTS: 'comments',
    FLOW_INSTANCE_ID: 'flow_instance_id',
    FLOW_STEP_ID: 'flow_step_id',
    OBJECT_API_NAME: 'object_api_name',
    PROCESS_ID: 'process_id',
    RECORD_ID: 'record_id',
    STATUS: 'status',
    SUBMITTED_BY_ID: 'submitted_by_id',
    SUBMITTED_DATE: 'submitted_date',
} as const;

export const FIELDS_SYSTEM_AUDITLOG = {
    CREATED_DATE: '__sys_gen_created_date',
    ID: '__sys_gen_id',
    LAST_MODIFIED_DATE: '__sys_gen_last_modified_date',
    CHANGED_AT: 'changed_at',
    CHANGED_BY_ID: 'changed_by_id',
    FIELD_NAME: 'field_name',
    NEW_VALUE: 'new_value',
    OBJECT_API_NAME: 'object_api_name',
    OLD_VALUE: 'old_value',
    RECORD_ID: 'record_id',
} as const;

export const FIELDS_SYSTEM_AUTONUMBER = {
    CREATED_DATE: '__sys_gen_created_date',
    ID: '__sys_gen_id',
    LAST_MODIFIED_DATE: '__sys_gen_last_modified_date',
    CURRENT_NUMBER: 'current_number',
    DISPLAY_FORMAT: 'display_format',
    FIELD_API_NAME: 'field_api_name',
    OBJECT_API_NAME: 'object_api_name',
    STARTING_NUMBER: 'starting_number',
} as const;

export const FIELDS_SYSTEM_COMMENT = {
    CREATED_BY_ID: '__sys_gen_created_by_id',
    CREATED_DATE: '__sys_gen_created_date',
    ID: '__sys_gen_id',
    IS_DELETED: '__sys_gen_is_deleted',
    LAST_MODIFIED_DATE: '__sys_gen_last_modified_date',
    BODY: 'body',
    IS_RESOLVED: 'is_resolved',
    OBJECT_API_NAME: 'object_api_name',
    PARENT_COMMENT_ID: 'parent_comment_id',
    RECORD_ID: 'record_id',
} as const;

export const FIELDS_SYSTEM_CONFIG = {
    CREATED_DATE: '__sys_gen_created_date',
    LAST_MODIFIED_DATE: '__sys_gen_last_modified_date',
    DESCRIPTION: 'description',
    IS_SECRET: 'is_secret',
    KEY_NAME: 'key_name',
    VALUE: 'value',
} as const;

export const FIELDS_SYSTEM_DASHBOARD = {
    CREATED_BY_ID: '__sys_gen_created_by_id',
    CREATED_DATE: '__sys_gen_created_date',
    ID: '__sys_gen_id',
    IS_DELETED: '__sys_gen_is_deleted',
    LAST_MODIFIED_BY_ID: '__sys_gen_last_modified_by_id',
    LAST_MODIFIED_DATE: '__sys_gen_last_modified_date',
    OWNER_ID: '__sys_gen_owner_id',
    DESCRIPTION: 'description',
    LAYOUT: 'layout',
    NAME: 'name',
    WIDGETS: 'widgets',
} as const;

export const FIELDS_SYSTEM_EMAILTEMPLATE = {
    CREATED_DATE: '__sys_gen_created_date',
    ID: '__sys_gen_id',
    LAST_MODIFIED_DATE: '__sys_gen_last_modified_date',
    FROM_EMAIL: 'from_email',
    FROM_NAME: 'from_name',
    HTML_BODY: 'html_body',
    IS_ACTIVE: 'is_active',
    NAME: 'name',
    REPLY_TO: 'reply_to',
    SUBJECT: 'subject',
    TEXT_BODY: 'text_body',
} as const;

export const FIELDS_SYSTEM_FEEDITEM = {
    CREATED_BY_ID: '__sys_gen_created_by_id',
    CREATED_DATE: '__sys_gen_created_date',
    ID: '__sys_gen_id',
    LAST_MODIFIED_DATE: '__sys_gen_last_modified_date',
    BODY: 'body',
    PARENT_ID: 'parent_id',
    TYPE: 'type',
} as const;

export const FIELDS_SYSTEM_FIELD = {
    CREATED_BY_ID: '__sys_gen_created_by_id',
    CREATED_DATE: '__sys_gen_created_date',
    ID: '__sys_gen_id',
    IS_DELETED: '__sys_gen_is_deleted',
    LAST_MODIFIED_BY_ID: '__sys_gen_last_modified_by_id',
    LAST_MODIFIED_DATE: '__sys_gen_last_modified_date',
    OWNER_ID: '__sys_gen_owner_id',
    API_NAME: 'api_name',
    CONTROLLING_FIELD: 'controlling_field',
    DEFAULT_VALUE: 'default_value',
    DELETE_RULE: 'delete_rule',
    DESCRIPTION: 'description',
    FORMULA: 'formula',
    HELP_TEXT: 'help_text',
    INDEXED: 'indexed',
    IS_MASTER_DETAIL: 'is_master_detail',
    IS_NAME_FIELD: 'is_name_field',
    IS_POLYMORPHIC: 'is_polymorphic',
    IS_SYSTEM: 'is_system',
    IS_UNIQUE: 'is_unique',
    LABEL: 'label',
    MAX_LENGTH: 'max_length',
    MAX_VALUE: 'max_value',
    MIN_LENGTH: 'min_length',
    MIN_VALUE: 'min_value',
    OBJECT_ID: 'object_id',
    OPTIONS: 'options',
    PICKLIST_DEPENDENCY: 'picklist_dependency',
    REFERENCE_TO: 'reference_to',
    REGEX: 'regex',
    REGEX_MESSAGE: 'regex_message',
    RELATIONSHIP_NAME: 'relationship_name',
    REQUIRED: 'required',
    RETURN_TYPE: 'return_type',
    ROLLUP_CONFIG: 'rollup_config',
    TRACK_HISTORY: 'track_history',
    TYPE: 'type',
    VALIDATOR: 'validator',
} as const;

export const FIELDS_SYSTEM_FIELDDEPENDENCY = {
    CREATED_DATE: '__sys_gen_created_date',
    ID: '__sys_gen_id',
    LAST_MODIFIED_DATE: '__sys_gen_last_modified_date',
    CONTROLLING_FIELD_ID: 'controlling_field_id',
    CONTROLLING_VALUE: 'controlling_value',
    DEPENDENT_FIELD_ID: 'dependent_field_id',
    DEPENDENT_VALUES: 'dependent_values',
} as const;

export const FIELDS_SYSTEM_FIELDPERMS = {
    CREATED_DATE: '__sys_gen_created_date',
    ID: '__sys_gen_id',
    LAST_MODIFIED_DATE: '__sys_gen_last_modified_date',
    EDITABLE: 'editable',
    FIELD_API_NAME: 'field_api_name',
    OBJECT_API_NAME: 'object_api_name',
    PERMISSION_SET_ID: 'permission_set_id',
    PROFILE_ID: 'profile_id',
    READABLE: 'readable',
} as const;

export const FIELDS_SYSTEM_FILE = {
    CREATED_BY_ID: '__sys_gen_created_by_id',
    CREATED_DATE: '__sys_gen_created_date',
    ID: '__sys_gen_id',
    LAST_MODIFIED_DATE: '__sys_gen_last_modified_date',
    MIME_TYPE: 'mime_type',
    NAME: 'name',
    PARENT_ID: 'parent_id',
    SIZE_BYTES: 'size_bytes',
    STORAGE_PATH: 'storage_path',
} as const;

export const FIELDS_SYSTEM_FLOW = {
    CREATED_BY_ID: '__sys_gen_created_by_id',
    CREATED_DATE: '__sys_gen_created_date',
    ID: '__sys_gen_id',
    IS_DELETED: '__sys_gen_is_deleted',
    LAST_MODIFIED_BY_ID: '__sys_gen_last_modified_by_id',
    LAST_MODIFIED_DATE: '__sys_gen_last_modified_date',
    OWNER_ID: '__sys_gen_owner_id',
    ACTION_CONFIG: 'action_config',
    ACTION_TYPE: 'action_type',
    DESCRIPTION: 'description',
    FLOW_TYPE: 'flow_type',
    IS_RUNNING: 'is_running',
    LAST_RUN_AT: 'last_run_at',
    NAME: 'name',
    NEXT_RUN_AT: 'next_run_at',
    SCHEDULE: 'schedule',
    SCHEDULE_TIMEZONE: 'schedule_timezone',
    STATUS: 'status',
    TRIGGER_CONDITION: 'trigger_condition',
    TRIGGER_OBJECT: 'trigger_object',
    TRIGGER_TYPE: 'trigger_type',
} as const;

export const FIELDS_SYSTEM_FLOWINSTANCE = {
    CREATED_BY_ID: '__sys_gen_created_by_id',
    CREATED_DATE: '__sys_gen_created_date',
    ID: '__sys_gen_id',
    IS_DELETED: '__sys_gen_is_deleted',
    LAST_MODIFIED_BY_ID: '__sys_gen_last_modified_by_id',
    LAST_MODIFIED_DATE: '__sys_gen_last_modified_date',
    OWNER_ID: '__sys_gen_owner_id',
    COMPLETED_DATE: 'completed_date',
    CONTEXT_DATA: 'context_data',
    CURRENT_STEP_ID: 'current_step_id',
    FLOW_ID: 'flow_id',
    OBJECT_API_NAME: 'object_api_name',
    PAUSED_DATE: 'paused_date',
    RECORD_ID: 'record_id',
    STARTED_DATE: 'started_date',
    STATUS: 'status',
} as const;

export const FIELDS_SYSTEM_FLOWSTEP = {
    CREATED_BY_ID: '__sys_gen_created_by_id',
    CREATED_DATE: '__sys_gen_created_date',
    ID: '__sys_gen_id',
    IS_DELETED: '__sys_gen_is_deleted',
    LAST_MODIFIED_BY_ID: '__sys_gen_last_modified_by_id',
    LAST_MODIFIED_DATE: '__sys_gen_last_modified_date',
    OWNER_ID: '__sys_gen_owner_id',
    ACTION_CONFIG: 'action_config',
    ACTION_TYPE: 'action_type',
    ENTRY_CONDITION: 'entry_condition',
    FLOW_ID: 'flow_id',
    ON_FAILURE_STEP: 'on_failure_step',
    ON_SUCCESS_STEP: 'on_success_step',
    STEP_NAME: 'step_name',
    STEP_ORDER: 'step_order',
    STEP_TYPE: 'step_type',
} as const;

export const FIELDS_SYSTEM_GROUP = {
    CREATED_DATE: '__sys_gen_created_date',
    ID: '__sys_gen_id',
    IS_DELETED: '__sys_gen_is_deleted',
    LAST_MODIFIED_DATE: '__sys_gen_last_modified_date',
    EMAIL: 'email',
    LABEL: 'label',
    NAME: 'name',
    TYPE: 'type',
} as const;

export const FIELDS_SYSTEM_GROUPMEMBER = {
    CREATED_DATE: '__sys_gen_created_date',
    ID: '__sys_gen_id',
    IS_DELETED: '__sys_gen_is_deleted',
    LAST_MODIFIED_DATE: '__sys_gen_last_modified_date',
    GROUP_ID: 'group_id',
    USER_ID: 'user_id',
} as const;

export const FIELDS_SYSTEM_LAYOUT = {
    CREATED_DATE: '__sys_gen_created_date',
    ID: '__sys_gen_id',
    LAST_MODIFIED_DATE: '__sys_gen_last_modified_date',
    CONFIG: 'config',
    OBJECT_API_NAME: 'object_api_name',
} as const;

export const FIELDS_SYSTEM_LISTVIEW = {
    CREATED_DATE: '__sys_gen_created_date',
    ID: '__sys_gen_id',
    LAST_MODIFIED_DATE: '__sys_gen_last_modified_date',
    FIELDS: 'fields',
    FILTER_EXPR: 'filter_expr',
    LABEL: 'label',
    OBJECT_API_NAME: 'object_api_name',
} as const;

export const FIELDS_SYSTEM_LOG = {
    CREATED_DATE: '__sys_gen_created_date',
    ID: '__sys_gen_id',
    LAST_MODIFIED_DATE: '__sys_gen_last_modified_date',
    DETAILS: 'details',
    LEVEL: 'level',
    MESSAGE: 'message',
    SOURCE: 'source',
    TIMESTAMP: 'timestamp',
} as const;

export const FIELDS_SYSTEM_NOTIFICATION = {
    CREATED_DATE: '__sys_gen_created_date',
    ID: '__sys_gen_id',
    LAST_MODIFIED_DATE: '__sys_gen_last_modified_date',
    BODY: 'body',
    IS_READ: 'is_read',
    LINK: 'link',
    NOTIFICATION_TYPE: 'notification_type',
    RECIPIENT_ID: 'recipient_id',
    TITLE: 'title',
} as const;

export const FIELDS_SYSTEM_OBJECT = {
    CREATED_BY_ID: '__sys_gen_created_by_id',
    CREATED_DATE: '__sys_gen_created_date',
    ID: '__sys_gen_id',
    IS_DELETED: '__sys_gen_is_deleted',
    LAST_MODIFIED_BY_ID: '__sys_gen_last_modified_by_id',
    LAST_MODIFIED_DATE: '__sys_gen_last_modified_date',
    OWNER_ID: '__sys_gen_owner_id',
    API_NAME: 'api_name',
    APP_ID: 'app_id',
    DESCRIPTION: 'description',
    ICON: 'icon',
    IS_CUSTOM: 'is_custom',
    LABEL: 'label',
    LIST_FIELDS: 'list_fields',
    PATH_FIELD: 'path_field',
    PLURAL_LABEL: 'plural_label',
    SHARING_MODEL: 'sharing_model',
    TABLE_TYPE: 'table_type',
    THEME_COLOR: 'theme_color',
} as const;

export const FIELDS_SYSTEM_OBJECTPERMS = {
    CREATED_DATE: '__sys_gen_created_date',
    ID: '__sys_gen_id',
    LAST_MODIFIED_DATE: '__sys_gen_last_modified_date',
    ALLOW_CREATE: 'allow_create',
    ALLOW_DELETE: 'allow_delete',
    ALLOW_EDIT: 'allow_edit',
    ALLOW_READ: 'allow_read',
    MODIFY_ALL: 'modify_all',
    OBJECT_API_NAME: 'object_api_name',
    PERMISSION_SET_ID: 'permission_set_id',
    PROFILE_ID: 'profile_id',
    VIEW_ALL: 'view_all',
} as const;

export const FIELDS_SYSTEM_OUTBOXEVENT = {
    CREATED_DATE: '__sys_gen_created_date',
    ID: '__sys_gen_id',
    LAST_MODIFIED_DATE: '__sys_gen_last_modified_date',
    ERROR_MESSAGE: 'error_message',
    EVENT_TYPE: 'event_type',
    PAYLOAD: 'payload',
    PROCESSED_DATE: 'processed_date',
    RETRY_COUNT: 'retry_count',
    STATUS: 'status',
} as const;

export const FIELDS_SYSTEM_PERMISSIONSET = {
    CREATED_DATE: '__sys_gen_created_date',
    ID: '__sys_gen_id',
    IS_DELETED: '__sys_gen_is_deleted',
    LAST_MODIFIED_DATE: '__sys_gen_last_modified_date',
    DESCRIPTION: 'description',
    IS_ACTIVE: 'is_active',
    LABEL: 'label',
    NAME: 'name',
} as const;

export const FIELDS_SYSTEM_PERMISSIONSETASSIGNMENT = {
    CREATED_DATE: '__sys_gen_created_date',
    ID: '__sys_gen_id',
    IS_DELETED: '__sys_gen_is_deleted',
    LAST_MODIFIED_DATE: '__sys_gen_last_modified_date',
    ASSIGNEE_ID: 'assignee_id',
    PERMISSION_SET_ID: 'permission_set_id',
} as const;

export const FIELDS_SYSTEM_PROFILE = {
    CREATED_BY_ID: '__sys_gen_created_by_id',
    CREATED_DATE: '__sys_gen_created_date',
    ID: '__sys_gen_id',
    IS_DELETED: '__sys_gen_is_deleted',
    LAST_MODIFIED_BY_ID: '__sys_gen_last_modified_by_id',
    LAST_MODIFIED_DATE: '__sys_gen_last_modified_date',
    OWNER_ID: '__sys_gen_owner_id',
    DESCRIPTION: 'description',
    IS_ACTIVE: 'is_active',
    IS_SYSTEM: 'is_system',
    NAME: 'name',
} as const;

export const FIELDS_SYSTEM_PROFILELAYOUT = {
    CREATED_DATE: '__sys_gen_created_date',
    ID: '__sys_gen_id',
    LAST_MODIFIED_DATE: '__sys_gen_last_modified_date',
    LAYOUT_ID: 'layout_id',
    OBJECT_API_NAME: 'object_api_name',
    PROFILE_ID: 'profile_id',
} as const;

export const FIELDS_SYSTEM_RECENT = {
    CREATED_DATE: '__sys_gen_created_date',
    ID: '__sys_gen_id',
    LAST_MODIFIED_DATE: '__sys_gen_last_modified_date',
    OBJECT_API_NAME: 'object_api_name',
    RECORD_ID: 'record_id',
    RECORD_NAME: 'record_name',
    TIMESTAMP: 'timestamp',
    USER_ID: 'user_id',
} as const;

export const FIELDS_SYSTEM_RECORDSHARE = {
    CREATED_BY_ID: '__sys_gen_created_by_id',
    CREATED_DATE: '__sys_gen_created_date',
    ID: '__sys_gen_id',
    IS_DELETED: '__sys_gen_is_deleted',
    LAST_MODIFIED_BY_ID: '__sys_gen_last_modified_by_id',
    LAST_MODIFIED_DATE: '__sys_gen_last_modified_date',
    ACCESS_LEVEL: 'access_level',
    OBJECT_API_NAME: 'object_api_name',
    REASON: 'reason',
    RECORD_ID: 'record_id',
    SHARE_WITH_GROUP_ID: 'share_with_group_id',
    SHARE_WITH_USER_ID: 'share_with_user_id',
} as const;

export const FIELDS_SYSTEM_RECORDTYPE = {
    CREATED_DATE: '__sys_gen_created_date',
    ID: '__sys_gen_id',
    IS_DELETED: '__sys_gen_is_deleted',
    LAST_MODIFIED_DATE: '__sys_gen_last_modified_date',
    DESCRIPTION: 'description',
    IS_ACTIVE: 'is_active',
    IS_MASTER: 'is_master',
    NAME: 'name',
    OBJECT_ID: 'object_id',
} as const;

export const FIELDS_SYSTEM_RECYCLEBIN = {
    CREATED_DATE: '__sys_gen_created_date',
    ID: '__sys_gen_id',
    LAST_MODIFIED_DATE: '__sys_gen_last_modified_date',
    DELETED_BY: 'deleted_by',
    DELETED_DATE: 'deleted_date',
    OBJECT_API_NAME: 'object_api_name',
    RECORD_ID: 'record_id',
    RECORD_NAME: 'record_name',
} as const;

export const FIELDS_SYSTEM_RELATIONSHIP = {
    CREATED_DATE: '__sys_gen_created_date',
    ID: '__sys_gen_id',
    LAST_MODIFIED_DATE: '__sys_gen_last_modified_date',
    CASCADE_DELETE: 'cascade_delete',
    CHILD_OBJECT_API_NAME: 'child_object_api_name',
    FIELD_API_NAME: 'field_api_name',
    PARENT_OBJECT_API_NAME: 'parent_object_api_name',
    RELATED_LIST_FIELDS: 'related_list_fields',
    RELATED_LIST_LABEL: 'related_list_label',
    RELATIONSHIP_NAME: 'relationship_name',
    RELATIONSHIP_TYPE: 'relationship_type',
    RESTRICTED_DELETE: 'restricted_delete',
} as const;

export const FIELDS_SYSTEM_ROLE = {
    CREATED_BY_ID: '__sys_gen_created_by_id',
    CREATED_DATE: '__sys_gen_created_date',
    ID: '__sys_gen_id',
    IS_DELETED: '__sys_gen_is_deleted',
    LAST_MODIFIED_BY_ID: '__sys_gen_last_modified_by_id',
    LAST_MODIFIED_DATE: '__sys_gen_last_modified_date',
    OWNER_ID: '__sys_gen_owner_id',
    DESCRIPTION: 'description',
    IS_ACTIVE: 'is_active',
    NAME: 'name',
    PARENT_ROLE_ID: 'parent_role_id',
} as const;

export const FIELDS_SYSTEM_SESSION = {
    CREATED_DATE: '__sys_gen_created_date',
    ID: '__sys_gen_id',
    LAST_MODIFIED_DATE: '__sys_gen_last_modified_date',
    EXPIRES_AT: 'expires_at',
    IP_ADDRESS: 'ip_address',
    IS_REVOKED: 'is_revoked',
    LAST_ACTIVITY: 'last_activity',
    TOKEN: 'token',
    USER_AGENT: 'user_agent',
    USER_ID: 'user_id',
} as const;

export const FIELDS_SYSTEM_SETUPPAGE = {
    CREATED_DATE: '__sys_gen_created_date',
    ID: '__sys_gen_id',
    LAST_MODIFIED_DATE: '__sys_gen_last_modified_date',
    CATEGORY: 'category',
    COMPONENT_NAME: 'component_name',
    DESCRIPTION: 'description',
    ICON: 'icon',
    IS_ENABLED: 'is_enabled',
    LABEL: 'label',
    PAGE_ORDER: 'page_order',
    PATH: 'path',
    PERMISSION_REQUIRED: 'permission_required',
} as const;

export const FIELDS_SYSTEM_SHARINGRULE = {
    CREATED_BY_ID: '__sys_gen_created_by_id',
    CREATED_DATE: '__sys_gen_created_date',
    ID: '__sys_gen_id',
    IS_DELETED: '__sys_gen_is_deleted',
    LAST_MODIFIED_BY_ID: '__sys_gen_last_modified_by_id',
    LAST_MODIFIED_DATE: '__sys_gen_last_modified_date',
    OWNER_ID: '__sys_gen_owner_id',
    ACCESS_LEVEL: 'access_level',
    CRITERIA: 'criteria',
    NAME: 'name',
    OBJECT_API_NAME: 'object_api_name',
    SHARE_WITH_GROUP_ID: 'share_with_group_id',
    SHARE_WITH_ROLE_ID: 'share_with_role_id',
} as const;

export const FIELDS_SYSTEM_SYSTEMLOG = {
    ID: '__sys_gen_id',
    DETAILS: 'details',
    LEVEL: 'level',
    MESSAGE: 'message',
    SOURCE: 'source',
    TIMESTAMP: 'timestamp',
} as const;

export const FIELDS_SYSTEM_TABLE = {
    CREATED_DATE: '__sys_gen_created_date',
    ID: '__sys_gen_id',
    LAST_MODIFIED_DATE: '__sys_gen_last_modified_date',
    CATEGORY: 'category',
    CREATED_BY: 'created_by',
    DESCRIPTION: 'description',
    IS_MANAGED: 'is_managed',
    SCHEMA_VERSION: 'schema_version',
    TABLE_NAME: 'table_name',
    TABLE_TYPE: 'table_type',
} as const;

export const FIELDS_SYSTEM_TEAMMEMBER = {
    CREATED_BY_ID: '__sys_gen_created_by_id',
    CREATED_DATE: '__sys_gen_created_date',
    ID: '__sys_gen_id',
    IS_DELETED: '__sys_gen_is_deleted',
    LAST_MODIFIED_BY_ID: '__sys_gen_last_modified_by_id',
    LAST_MODIFIED_DATE: '__sys_gen_last_modified_date',
    ACCESS_LEVEL: 'access_level',
    OBJECT_API_NAME: 'object_api_name',
    RECORD_ID: 'record_id',
    TEAM_ROLE: 'team_role',
    USER_ID: 'user_id',
} as const;

export const FIELDS_SYSTEM_THEME = {
    CREATED_DATE: '__sys_gen_created_date',
    ID: '__sys_gen_id',
    LAST_MODIFIED_DATE: '__sys_gen_last_modified_date',
    COLORS: 'colors',
    DENSITY: 'density',
    IS_ACTIVE: 'is_active',
    LOGO_URL: 'logo_url',
    NAME: 'name',
} as const;

export const FIELDS_SYSTEM_UICOMPONENT = {
    CREATED_DATE: '__sys_gen_created_date',
    ID: '__sys_gen_id',
    LAST_MODIFIED_DATE: '__sys_gen_last_modified_date',
    COMPONENT_PATH: 'component_path',
    DESCRIPTION: 'description',
    IS_EMBEDDABLE: 'is_embeddable',
    NAME: 'name',
    TYPE: 'type',
} as const;

export const FIELDS_SYSTEM_USER = {
    CREATED_BY_ID: '__sys_gen_created_by_id',
    CREATED_DATE: '__sys_gen_created_date',
    ID: '__sys_gen_id',
    IS_DELETED: '__sys_gen_is_deleted',
    LAST_MODIFIED_BY_ID: '__sys_gen_last_modified_by_id',
    LAST_MODIFIED_DATE: '__sys_gen_last_modified_date',
    OWNER_ID: '__sys_gen_owner_id',
    EMAIL: 'email',
    FIRST_NAME: 'first_name',
    IS_ACTIVE: 'is_active',
    LAST_LOGIN_DATE: 'last_login_date',
    LAST_NAME: 'last_name',
    PASSWORD: 'password',
    PHONE: 'phone',
    PROFILE_ID: 'profile_id',
    ROLE_ID: 'role_id',
    USERNAME: 'username',
} as const;

export const FIELDS_SYSTEM_VALIDATION = {
    CREATED_DATE: '__sys_gen_created_date',
    ID: '__sys_gen_id',
    LAST_MODIFIED_DATE: '__sys_gen_last_modified_date',
    ACTIVE: 'active',
    CONDITION: 'condition',
    ERROR_MESSAGE: 'error_message',
    NAME: 'name',
    OBJECT_API_NAME: 'object_api_name',
} as const;

export const FIELDS_SYSTEM_WEBHOOK = {
    CREATED_DATE: '__sys_gen_created_date',
    ID: '__sys_gen_id',
    LAST_MODIFIED_DATE: '__sys_gen_last_modified_date',
    AUTH_CONFIG: 'auth_config',
    AUTH_TYPE: 'auth_type',
    HEADERS: 'headers',
    IS_ACTIVE: 'is_active',
    METHOD: 'method',
    NAME: 'name',
    URL: 'url',
} as const;

// ==================== TypeScript Interfaces ====================

/** _System_AI_Conversation - Persisted AI conversation history per user */
export interface SystemAIConversation {
    __sys_gen_id: string;
    id?: string; // Alias for __sys_gen_id
    user_id: string;
    title: string;
    messages: Record<string, unknown>;
    is_active: boolean;
    __sys_gen_created_date: string;
    created_date?: string; // Alias for __sys_gen_created_date
    __sys_gen_last_modified_date: string;
    last_modified_date?: string; // Alias for __sys_gen_last_modified_date
    __sys_gen_is_deleted: boolean;
    is_deleted?: boolean; // Alias for __sys_gen_is_deleted
}

/** _System_Action - UI action definitions */
export interface SystemAction {
    __sys_gen_id: string;
    id?: string; // Alias for __sys_gen_id
    object_api_name: string;
    name: string;
    label: string;
    type: string;
    icon?: string;
    target_object?: string;
    config?: Record<string, unknown>;
    __sys_gen_created_date: string;
    created_date?: string; // Alias for __sys_gen_created_date
    __sys_gen_last_modified_date: string;
    last_modified_date?: string; // Alias for __sys_gen_last_modified_date
}

/** _System_App - Application configurations */
export interface SystemApp {
    __sys_gen_id: string;
    id?: string; // Alias for __sys_gen_id
    name: string;
    label: string;
    description: string;
    icon: string;
    color: string;
    navigation_items: Record<string, unknown>;
    is_default: boolean;
    __sys_gen_created_date: string;
    created_date?: string; // Alias for __sys_gen_created_date
    __sys_gen_last_modified_date: string;
    last_modified_date?: string; // Alias for __sys_gen_last_modified_date
}

/** _System_ApprovalProcess - Approval process definitions */
export interface SystemApprovalProcess {
    __sys_gen_id: string;
    id?: string; // Alias for __sys_gen_id
    name: string;
    object_api_name: string;
    description?: string;
    entry_criteria?: string;
    approver_type: string;
    approver_id?: string;
    is_active: boolean;
    __sys_gen_owner_id?: string;
    owner_id?: string; // Alias for __sys_gen_owner_id
    __sys_gen_created_by_id?: string;
    created_by_id?: string; // Alias for __sys_gen_created_by_id
    __sys_gen_created_date: string;
    created_date?: string; // Alias for __sys_gen_created_date
    __sys_gen_last_modified_by_id?: string;
    last_modified_by_id?: string; // Alias for __sys_gen_last_modified_by_id
    __sys_gen_last_modified_date?: string;
    last_modified_date?: string; // Alias for __sys_gen_last_modified_date
    __sys_gen_is_deleted: boolean;
    is_deleted?: boolean; // Alias for __sys_gen_is_deleted
}

/** _System_ApprovalWorkItem - Pending approval work items */
export interface SystemApprovalWorkItem {
    __sys_gen_id: string;
    id?: string; // Alias for __sys_gen_id
    process_id: string;
    flow_instance_id?: string;
    flow_step_id?: string;
    object_api_name: string;
    record_id: string;
    status: string;
    submitted_by_id?: string;
    submitted_date: string;
    approver_id?: string;
    approved_by_id?: string;
    approved_date?: string;
    comments?: string;
    __sys_gen_owner_id?: string;
    owner_id?: string; // Alias for __sys_gen_owner_id
    __sys_gen_created_by_id?: string;
    created_by_id?: string; // Alias for __sys_gen_created_by_id
    __sys_gen_created_date: string;
    created_date?: string; // Alias for __sys_gen_created_date
    __sys_gen_last_modified_by_id?: string;
    last_modified_by_id?: string; // Alias for __sys_gen_last_modified_by_id
    __sys_gen_last_modified_date?: string;
    last_modified_date?: string; // Alias for __sys_gen_last_modified_date
    __sys_gen_is_deleted: boolean;
    is_deleted?: boolean; // Alias for __sys_gen_is_deleted
}

/** _System_AuditLog - Field history tracking */
export interface SystemAuditLog {
    __sys_gen_id: string;
    id?: string; // Alias for __sys_gen_id
    object_api_name: string;
    record_id: string;
    field_name: string;
    old_value: string;
    new_value: string;
    changed_by_id: string;
    changed_at: string;
    __sys_gen_created_date: string;
    created_date?: string; // Alias for __sys_gen_created_date
    __sys_gen_last_modified_date: string;
    last_modified_date?: string; // Alias for __sys_gen_last_modified_date
}

/** _System_AutoNumber - Auto-number sequence tracking */
export interface SystemAutoNumber {
    __sys_gen_id: string;
    id?: string; // Alias for __sys_gen_id
    object_api_name: string;
    field_api_name: string;
    display_format: string;
    starting_number: number;
    current_number: number;
    __sys_gen_created_date: string;
    created_date?: string; // Alias for __sys_gen_created_date
    __sys_gen_last_modified_date: string;
    last_modified_date?: string; // Alias for __sys_gen_last_modified_date
}

/** _System_Comment - User comments on records */
export interface SystemComment {
    __sys_gen_id: string;
    id?: string; // Alias for __sys_gen_id
    object_api_name: string;
    record_id: string;
    body: string;
    __sys_gen_created_by_id: string;
    created_by_id?: string; // Alias for __sys_gen_created_by_id
    __sys_gen_created_date: string;
    created_date?: string; // Alias for __sys_gen_created_date
    __sys_gen_is_deleted: boolean;
    is_deleted?: boolean; // Alias for __sys_gen_is_deleted
    parent_comment_id?: string;
    is_resolved: boolean;
    __sys_gen_last_modified_date: string;
    last_modified_date?: string; // Alias for __sys_gen_last_modified_date
}

/** _System_Config - System configuration settings */
export interface SystemConfig {
    key_name: string;
    value: string;
    is_secret: boolean;
    description: string;
    __sys_gen_created_date: string;
    created_date?: string; // Alias for __sys_gen_created_date
    __sys_gen_last_modified_date: string;
    last_modified_date?: string; // Alias for __sys_gen_last_modified_date
}

/** _System_Dashboard - Dashboard configurations with widget-based layouts */
export interface SystemDashboard {
    __sys_gen_id: string;
    id?: string; // Alias for __sys_gen_id
    name: string;
    description: string;
    layout: string;
    widgets: Record<string, unknown>;
    __sys_gen_created_date: string;
    created_date?: string; // Alias for __sys_gen_created_date
    __sys_gen_owner_id?: string;
    owner_id?: string; // Alias for __sys_gen_owner_id
    __sys_gen_created_by_id?: string;
    created_by_id?: string; // Alias for __sys_gen_created_by_id
    __sys_gen_last_modified_by_id?: string;
    last_modified_by_id?: string; // Alias for __sys_gen_last_modified_by_id
    __sys_gen_is_deleted: boolean;
    is_deleted?: boolean; // Alias for __sys_gen_is_deleted
    __sys_gen_last_modified_date: string;
    last_modified_date?: string; // Alias for __sys_gen_last_modified_date
}

/** _System_EmailTemplate - Email templates for notifications */
export interface SystemEmailTemplate {
    __sys_gen_id: string;
    id?: string; // Alias for __sys_gen_id
    name: string;
    subject: string;
    html_body: string;
    text_body: string;
    from_name: string;
    from_email: string;
    reply_to: string;
    is_active: boolean;
    __sys_gen_created_date: string;
    created_date?: string; // Alias for __sys_gen_created_date
    __sys_gen_last_modified_date: string;
    last_modified_date?: string; // Alias for __sys_gen_last_modified_date
}

/** _System_FeedItem - Feed items for chatter and notifications */
export interface SystemFeedItem {
    __sys_gen_id: string;
    id?: string; // Alias for __sys_gen_id
    parent_id: string;
    type: string;
    body: string;
    __sys_gen_created_by_id: string;
    created_by_id?: string; // Alias for __sys_gen_created_by_id
    __sys_gen_created_date: string;
    created_date?: string; // Alias for __sys_gen_created_date
    __sys_gen_last_modified_date: string;
    last_modified_date?: string; // Alias for __sys_gen_last_modified_date
}

/** _System_Field - Field metadata definitions */
export interface SystemField {
    __sys_gen_id: string;
    id?: string; // Alias for __sys_gen_id
    object_id: string;
    api_name: string;
    label: string;
    type: string;
    required: boolean;
    is_unique: boolean;
    is_system: boolean;
    is_name_field: boolean;
    indexed: boolean;
    options?: Record<string, unknown>;
    reference_to?: Record<string, unknown>;
    delete_rule?: string;
    formula?: string;
    return_type?: string;
    default_value?: string;
    help_text?: string;
    description?: string;
    track_history: boolean;
    min_value?: number;
    max_value?: number;
    min_length?: number;
    max_length?: number;
    regex?: string;
    regex_message?: string;
    validator?: string;
    controlling_field?: string;
    picklist_dependency?: Record<string, unknown>;
    rollup_config?: Record<string, unknown>;
    is_master_detail: boolean;
    is_polymorphic: boolean;
    relationship_name?: string;
    __sys_gen_is_deleted: boolean;
    is_deleted?: boolean; // Alias for __sys_gen_is_deleted
    __sys_gen_owner_id?: string;
    owner_id?: string; // Alias for __sys_gen_owner_id
    __sys_gen_created_by_id?: string;
    created_by_id?: string; // Alias for __sys_gen_created_by_id
    __sys_gen_last_modified_by_id?: string;
    last_modified_by_id?: string; // Alias for __sys_gen_last_modified_by_id
    __sys_gen_created_date: string;
    created_date?: string; // Alias for __sys_gen_created_date
    __sys_gen_last_modified_date: string;
    last_modified_date?: string; // Alias for __sys_gen_last_modified_date
}

/** _System_FieldDependency - Field dependency rules */
export interface SystemFieldDependency {
    __sys_gen_id: string;
    id?: string; // Alias for __sys_gen_id
    controlling_field_id: string;
    dependent_field_id: string;
    controlling_value: string;
    dependent_values: Record<string, unknown>;
    __sys_gen_created_date: string;
    created_date?: string; // Alias for __sys_gen_created_date
    __sys_gen_last_modified_date: string;
    last_modified_date?: string; // Alias for __sys_gen_last_modified_date
}

/** _System_FieldPerms - Field permissions for profiles */
export interface SystemFieldPerms {
    __sys_gen_id: string;
    id?: string; // Alias for __sys_gen_id
    profile_id?: string;
    permission_set_id?: string;
    object_api_name: string;
    field_api_name: string;
    readable: boolean;
    editable: boolean;
    __sys_gen_created_date: string;
    created_date?: string; // Alias for __sys_gen_created_date
    __sys_gen_last_modified_date: string;
    last_modified_date?: string; // Alias for __sys_gen_last_modified_date
}

/** _System_File - File attachments */
export interface SystemFile {
    __sys_gen_id: string;
    id?: string; // Alias for __sys_gen_id
    parent_id: string;
    name: string;
    mime_type: string;
    size_bytes: number;
    storage_path: string;
    __sys_gen_created_by_id: string;
    created_by_id?: string; // Alias for __sys_gen_created_by_id
    __sys_gen_created_date: string;
    created_date?: string; // Alias for __sys_gen_created_date
    __sys_gen_last_modified_date: string;
    last_modified_date?: string; // Alias for __sys_gen_last_modified_date
}

/** _System_Flow - Workflow automation definitions */
export interface SystemFlow {
    __sys_gen_id: string;
    id?: string; // Alias for __sys_gen_id
    name: string;
    trigger_object: string;
    trigger_type: string;
    trigger_condition: string;
    action_type: string;
    action_config: Record<string, unknown>;
    flow_type: string;
    description?: string;
    status: string;
    __sys_gen_created_date: string;
    created_date?: string; // Alias for __sys_gen_created_date
    __sys_gen_created_by_id?: string;
    created_by_id?: string; // Alias for __sys_gen_created_by_id
    __sys_gen_last_modified_by_id?: string;
    last_modified_by_id?: string; // Alias for __sys_gen_last_modified_by_id
    __sys_gen_owner_id?: string;
    owner_id?: string; // Alias for __sys_gen_owner_id
    __sys_gen_is_deleted: boolean;
    is_deleted?: boolean; // Alias for __sys_gen_is_deleted
    schedule?: string;
    schedule_timezone?: string;
    last_run_at?: string;
    next_run_at?: string;
    is_running: boolean;
    __sys_gen_last_modified_date: string;
    last_modified_date?: string; // Alias for __sys_gen_last_modified_date
}

/** _System_FlowInstance - Tracks running and paused flow executions */
export interface SystemFlowInstance {
    __sys_gen_id: string;
    id?: string; // Alias for __sys_gen_id
    flow_id: string;
    object_api_name: string;
    record_id: string;
    status: string;
    current_step_id?: string;
    context_data?: Record<string, unknown>;
    started_date: string;
    paused_date?: string;
    completed_date?: string;
    __sys_gen_owner_id?: string;
    owner_id?: string; // Alias for __sys_gen_owner_id
    __sys_gen_created_by_id?: string;
    created_by_id?: string; // Alias for __sys_gen_created_by_id
    __sys_gen_created_date: string;
    created_date?: string; // Alias for __sys_gen_created_date
    __sys_gen_last_modified_by_id?: string;
    last_modified_by_id?: string; // Alias for __sys_gen_last_modified_by_id
    __sys_gen_last_modified_date?: string;
    last_modified_date?: string; // Alias for __sys_gen_last_modified_date
    __sys_gen_is_deleted: boolean;
    is_deleted?: boolean; // Alias for __sys_gen_is_deleted
}

/** _System_FlowStep - Step definitions for multi-step flows */
export interface SystemFlowStep {
    __sys_gen_id: string;
    id?: string; // Alias for __sys_gen_id
    flow_id: string;
    step_order: number;
    step_name: string;
    step_type: string;
    action_type?: string;
    action_config?: Record<string, unknown>;
    entry_condition?: string;
    on_success_step?: string;
    on_failure_step?: string;
    __sys_gen_created_date: string;
    created_date?: string; // Alias for __sys_gen_created_date
    __sys_gen_created_by_id?: string;
    created_by_id?: string; // Alias for __sys_gen_created_by_id
    __sys_gen_last_modified_by_id?: string;
    last_modified_by_id?: string; // Alias for __sys_gen_last_modified_by_id
    __sys_gen_owner_id?: string;
    owner_id?: string; // Alias for __sys_gen_owner_id
    __sys_gen_is_deleted: boolean;
    is_deleted?: boolean; // Alias for __sys_gen_is_deleted
    __sys_gen_last_modified_date: string;
    last_modified_date?: string; // Alias for __sys_gen_last_modified_date
}

/** _System_Group - Groups and Queues */
export interface SystemGroup {
    __sys_gen_id: string;
    id?: string; // Alias for __sys_gen_id
    name: string;
    label: string;
    type: string;
    email?: string;
    __sys_gen_created_date: string;
    created_date?: string; // Alias for __sys_gen_created_date
    __sys_gen_is_deleted: boolean;
    is_deleted?: boolean; // Alias for __sys_gen_is_deleted
    __sys_gen_last_modified_date: string;
    last_modified_date?: string; // Alias for __sys_gen_last_modified_date
}

/** _System_GroupMember - Group membership */
export interface SystemGroupMember {
    __sys_gen_id: string;
    id?: string; // Alias for __sys_gen_id
    group_id: string;
    user_id: string;
    __sys_gen_created_date: string;
    created_date?: string; // Alias for __sys_gen_created_date
    __sys_gen_is_deleted: boolean;
    is_deleted?: boolean; // Alias for __sys_gen_is_deleted
    __sys_gen_last_modified_date: string;
    last_modified_date?: string; // Alias for __sys_gen_last_modified_date
}

/** _System_Layout - Page layout configurations */
export interface SystemLayout {
    __sys_gen_id: string;
    id?: string; // Alias for __sys_gen_id
    object_api_name: string;
    config: Record<string, unknown>;
    __sys_gen_created_date: string;
    created_date?: string; // Alias for __sys_gen_created_date
    __sys_gen_last_modified_date: string;
    last_modified_date?: string; // Alias for __sys_gen_last_modified_date
}

/** _System_ListView - List view configurations */
export interface SystemListView {
    __sys_gen_id: string;
    id?: string; // Alias for __sys_gen_id
    object_api_name: string;
    label: string;
    filter_expr?: string;
    fields: Record<string, unknown>;
    __sys_gen_created_date: string;
    created_date?: string; // Alias for __sys_gen_created_date
    __sys_gen_last_modified_date: string;
    last_modified_date?: string; // Alias for __sys_gen_last_modified_date
}

/** _System_Log - System event logs */
export interface SystemLog {
    __sys_gen_id: string;
    id?: string; // Alias for __sys_gen_id
    timestamp: string;
    level: string;
    source: string;
    message: string;
    details?: string;
    __sys_gen_created_date: string;
    created_date?: string; // Alias for __sys_gen_created_date
    __sys_gen_last_modified_date: string;
    last_modified_date?: string; // Alias for __sys_gen_last_modified_date
}

/** _System_Notification - User notifications */
export interface SystemNotification {
    __sys_gen_id: string;
    id?: string; // Alias for __sys_gen_id
    recipient_id: string;
    title: string;
    body: string;
    link: string;
    is_read: boolean;
    notification_type: string;
    __sys_gen_created_date: string;
    created_date?: string; // Alias for __sys_gen_created_date
    __sys_gen_last_modified_date: string;
    last_modified_date?: string; // Alias for __sys_gen_last_modified_date
}

/** _System_Object - Object metadata definitions */
export interface SystemObject {
    __sys_gen_id: string;
    id?: string; // Alias for __sys_gen_id
    api_name: string;
    table_type: string;
    label: string;
    plural_label?: string;
    app_id?: string;
    icon?: string;
    description: string;
    theme_color?: string;
    is_custom: boolean;
    sharing_model: string;
    path_field?: string;
    list_fields?: Record<string, unknown>;
    __sys_gen_is_deleted: boolean;
    is_deleted?: boolean; // Alias for __sys_gen_is_deleted
    __sys_gen_owner_id?: string;
    owner_id?: string; // Alias for __sys_gen_owner_id
    __sys_gen_created_by_id?: string;
    created_by_id?: string; // Alias for __sys_gen_created_by_id
    __sys_gen_last_modified_by_id?: string;
    last_modified_by_id?: string; // Alias for __sys_gen_last_modified_by_id
    __sys_gen_created_date: string;
    created_date?: string; // Alias for __sys_gen_created_date
    __sys_gen_last_modified_date: string;
    last_modified_date?: string; // Alias for __sys_gen_last_modified_date
}

/** _System_ObjectPerms - Object permissions for profiles */
export interface SystemObjectPerms {
    __sys_gen_id: string;
    id?: string; // Alias for __sys_gen_id
    profile_id?: string;
    permission_set_id?: string;
    object_api_name: string;
    allow_read: boolean;
    allow_create: boolean;
    allow_edit: boolean;
    allow_delete: boolean;
    view_all: boolean;
    modify_all: boolean;
    __sys_gen_created_date: string;
    created_date?: string; // Alias for __sys_gen_created_date
    __sys_gen_last_modified_date: string;
    last_modified_date?: string; // Alias for __sys_gen_last_modified_date
}

/** _System_OutboxEvent - Transactional event outbox for guaranteed delivery */
export interface SystemOutboxEvent {
    __sys_gen_id: string;
    id?: string; // Alias for __sys_gen_id
    event_type: string;
    payload: Record<string, unknown>;
    status: string;
    retry_count: number;
    error_message?: string;
    processed_date?: string;
    __sys_gen_created_date: string;
    created_date?: string; // Alias for __sys_gen_created_date
    __sys_gen_last_modified_date: string;
    last_modified_date?: string; // Alias for __sys_gen_last_modified_date
}

/** _System_PermissionSet - Additive permission sets */
export interface SystemPermissionSet {
    __sys_gen_id: string;
    id?: string; // Alias for __sys_gen_id
    name: string;
    label: string;
    description: string;
    is_active: boolean;
    __sys_gen_created_date: string;
    created_date?: string; // Alias for __sys_gen_created_date
    __sys_gen_is_deleted: boolean;
    is_deleted?: boolean; // Alias for __sys_gen_is_deleted
    __sys_gen_last_modified_date: string;
    last_modified_date?: string; // Alias for __sys_gen_last_modified_date
}

/** _System_PermissionSetAssignment - Assignment of permission sets to users */
export interface SystemPermissionSetAssignment {
    __sys_gen_id: string;
    id?: string; // Alias for __sys_gen_id
    assignee_id: string;
    permission_set_id: string;
    __sys_gen_created_date: string;
    created_date?: string; // Alias for __sys_gen_created_date
    __sys_gen_is_deleted: boolean;
    is_deleted?: boolean; // Alias for __sys_gen_is_deleted
    __sys_gen_last_modified_date: string;
    last_modified_date?: string; // Alias for __sys_gen_last_modified_date
}

/** _System_Profile - User profiles and permission sets */
export interface SystemProfile {
    __sys_gen_id: string;
    id?: string; // Alias for __sys_gen_id
    name: string;
    description: string;
    is_active: boolean;
    is_system: boolean;
    __sys_gen_is_deleted: boolean;
    is_deleted?: boolean; // Alias for __sys_gen_is_deleted
    __sys_gen_owner_id?: string;
    owner_id?: string; // Alias for __sys_gen_owner_id
    __sys_gen_created_by_id?: string;
    created_by_id?: string; // Alias for __sys_gen_created_by_id
    __sys_gen_last_modified_by_id?: string;
    last_modified_by_id?: string; // Alias for __sys_gen_last_modified_by_id
    __sys_gen_created_date: string;
    created_date?: string; // Alias for __sys_gen_created_date
    __sys_gen_last_modified_date: string;
    last_modified_date?: string; // Alias for __sys_gen_last_modified_date
}

/** _System_ProfileLayout - Profile to layout assignments */
export interface SystemProfileLayout {
    __sys_gen_id: string;
    id?: string; // Alias for __sys_gen_id
    profile_id: string;
    object_api_name: string;
    layout_id: string;
    __sys_gen_created_date: string;
    created_date?: string; // Alias for __sys_gen_created_date
    __sys_gen_last_modified_date: string;
    last_modified_date?: string; // Alias for __sys_gen_last_modified_date
}

/** _System_Recent - Recently viewed records */
export interface SystemRecent {
    __sys_gen_id: string;
    id?: string; // Alias for __sys_gen_id
    user_id: string;
    object_api_name: string;
    record_id: string;
    record_name: string;
    timestamp: string;
    __sys_gen_created_date: string;
    created_date?: string; // Alias for __sys_gen_created_date
    __sys_gen_last_modified_date: string;
    last_modified_date?: string; // Alias for __sys_gen_last_modified_date
}

/** _System_RecordShare - Manual record sharing with users or groups */
export interface SystemRecordShare {
    __sys_gen_id: string;
    id?: string; // Alias for __sys_gen_id
    object_api_name: string;
    record_id: string;
    share_with_user_id?: string;
    share_with_group_id?: string;
    access_level: string;
    reason: string;
    __sys_gen_created_by_id?: string;
    created_by_id?: string; // Alias for __sys_gen_created_by_id
    __sys_gen_created_date: string;
    created_date?: string; // Alias for __sys_gen_created_date
    __sys_gen_last_modified_by_id?: string;
    last_modified_by_id?: string; // Alias for __sys_gen_last_modified_by_id
    __sys_gen_last_modified_date?: string;
    last_modified_date?: string; // Alias for __sys_gen_last_modified_date
    __sys_gen_is_deleted: boolean;
    is_deleted?: boolean; // Alias for __sys_gen_is_deleted
}

/** _System_RecordType - Record type configurations */
export interface SystemRecordType {
    __sys_gen_id: string;
    id?: string; // Alias for __sys_gen_id
    object_id: string;
    name: string;
    description: string;
    is_active: boolean;
    is_master: boolean;
    __sys_gen_is_deleted: boolean;
    is_deleted?: boolean; // Alias for __sys_gen_is_deleted
    __sys_gen_created_date: string;
    created_date?: string; // Alias for __sys_gen_created_date
    __sys_gen_last_modified_date: string;
    last_modified_date?: string; // Alias for __sys_gen_last_modified_date
}

/** _System_RecycleBin - Recycle bin for soft-deleted records */
export interface SystemRecycleBin {
    __sys_gen_id: string;
    id?: string; // Alias for __sys_gen_id
    record_id: string;
    object_api_name: string;
    record_name: string;
    deleted_by: string;
    deleted_date: string;
    __sys_gen_created_date: string;
    created_date?: string; // Alias for __sys_gen_created_date
    __sys_gen_last_modified_date: string;
    last_modified_date?: string; // Alias for __sys_gen_last_modified_date
}

/** _System_Relationship - Object relationship definitions */
export interface SystemRelationship {
    __sys_gen_id: string;
    id?: string; // Alias for __sys_gen_id
    child_object_api_name: string;
    parent_object_api_name: string;
    field_api_name: string;
    relationship_name: string;
    relationship_type: string;
    cascade_delete: boolean;
    restricted_delete: boolean;
    related_list_label: string;
    related_list_fields: string;
    __sys_gen_created_date: string;
    created_date?: string; // Alias for __sys_gen_created_date
    __sys_gen_last_modified_date: string;
    last_modified_date?: string; // Alias for __sys_gen_last_modified_date
}

/** _System_Role - Role hierarchy for access control */
export interface SystemRole {
    __sys_gen_id: string;
    id?: string; // Alias for __sys_gen_id
    name: string;
    description: string;
    parent_role_id?: string;
    is_active: boolean;
    __sys_gen_is_deleted: boolean;
    is_deleted?: boolean; // Alias for __sys_gen_is_deleted
    __sys_gen_owner_id?: string;
    owner_id?: string; // Alias for __sys_gen_owner_id
    __sys_gen_created_by_id?: string;
    created_by_id?: string; // Alias for __sys_gen_created_by_id
    __sys_gen_last_modified_by_id?: string;
    last_modified_by_id?: string; // Alias for __sys_gen_last_modified_by_id
    __sys_gen_created_date: string;
    created_date?: string; // Alias for __sys_gen_created_date
    __sys_gen_last_modified_date: string;
    last_modified_date?: string; // Alias for __sys_gen_last_modified_date
}

/** _System_Session - User authentication sessions */
export interface SystemSession {
    __sys_gen_id: string;
    id?: string; // Alias for __sys_gen_id
    user_id: string;
    token: string;
    expires_at: string;
    last_activity: string;
    ip_address: string;
    user_agent: string;
    is_revoked: boolean;
    __sys_gen_created_date: string;
    created_date?: string; // Alias for __sys_gen_created_date
    __sys_gen_last_modified_date: string;
    last_modified_date?: string; // Alias for __sys_gen_last_modified_date
}

/** _System_SetupPage - Setup page definitions */
export interface SystemSetupPage {
    __sys_gen_id: string;
    id?: string; // Alias for __sys_gen_id
    label: string;
    icon?: string;
    component_name: string;
    category: string;
    page_order: number;
    permission_required?: string;
    is_enabled: boolean;
    description?: string;
    path?: string;
    __sys_gen_created_date: string;
    created_date?: string; // Alias for __sys_gen_created_date
    __sys_gen_last_modified_date: string;
    last_modified_date?: string; // Alias for __sys_gen_last_modified_date
}

/** _System_SharingRule - Record sharing rules */
export interface SystemSharingRule {
    __sys_gen_id: string;
    id?: string; // Alias for __sys_gen_id
    object_api_name: string;
    name: string;
    criteria: string;
    access_level: string;
    share_with_role_id?: string;
    share_with_group_id?: string;
    __sys_gen_is_deleted: boolean;
    is_deleted?: boolean; // Alias for __sys_gen_is_deleted
    __sys_gen_owner_id?: string;
    owner_id?: string; // Alias for __sys_gen_owner_id
    __sys_gen_created_by_id?: string;
    created_by_id?: string; // Alias for __sys_gen_created_by_id
    __sys_gen_last_modified_by_id?: string;
    last_modified_by_id?: string; // Alias for __sys_gen_last_modified_by_id
    __sys_gen_created_date: string;
    created_date?: string; // Alias for __sys_gen_created_date
    __sys_gen_last_modified_date: string;
    last_modified_date?: string; // Alias for __sys_gen_last_modified_date
}

/** _System_SystemLog - System operation logs */
export interface SystemSystemLog {
    __sys_gen_id: string;
    id?: string; // Alias for __sys_gen_id
    timestamp: string;
    level: string;
    source: string;
    message: string;
    details?: string;
}

/** _System_Table - Meta-metadata registry cataloging all tables */
export interface SystemTable {
    __sys_gen_id: string;
    id?: string; // Alias for __sys_gen_id
    table_name: string;
    table_type: string;
    category: string;
    description: string;
    is_managed: boolean;
    schema_version: string;
    created_by: string;
    __sys_gen_created_date: string;
    created_date?: string; // Alias for __sys_gen_created_date
    __sys_gen_last_modified_date: string;
    last_modified_date?: string; // Alias for __sys_gen_last_modified_date
}

/** _System_TeamMember - Generic record team members */
export interface SystemTeamMember {
    __sys_gen_id: string;
    id?: string; // Alias for __sys_gen_id
    object_api_name: string;
    record_id: string;
    user_id: string;
    team_role: string;
    access_level: string;
    __sys_gen_created_by_id?: string;
    created_by_id?: string; // Alias for __sys_gen_created_by_id
    __sys_gen_created_date: string;
    created_date?: string; // Alias for __sys_gen_created_date
    __sys_gen_last_modified_by_id?: string;
    last_modified_by_id?: string; // Alias for __sys_gen_last_modified_by_id
    __sys_gen_last_modified_date?: string;
    last_modified_date?: string; // Alias for __sys_gen_last_modified_date
    __sys_gen_is_deleted: boolean;
    is_deleted?: boolean; // Alias for __sys_gen_is_deleted
}

/** _System_Theme - Visual theme configurations */
export interface SystemTheme {
    __sys_gen_id: string;
    id?: string; // Alias for __sys_gen_id
    name: string;
    is_active: boolean;
    colors: Record<string, unknown>;
    density: string;
    logo_url?: string;
    __sys_gen_created_date: string;
    created_date?: string; // Alias for __sys_gen_created_date
    __sys_gen_last_modified_date: string;
    last_modified_date?: string; // Alias for __sys_gen_last_modified_date
}

/** _System_UIComponent - Registered UI components */
export interface SystemUIComponent {
    __sys_gen_id: string;
    id?: string; // Alias for __sys_gen_id
    name: string;
    type: string;
    is_embeddable: boolean;
    description: string;
    component_path?: string;
    __sys_gen_created_date: string;
    created_date?: string; // Alias for __sys_gen_created_date
    __sys_gen_last_modified_date: string;
    last_modified_date?: string; // Alias for __sys_gen_last_modified_date
}

/** _System_User - System users */
export interface SystemUser {
    __sys_gen_id: string;
    id?: string; // Alias for __sys_gen_id
    username: string;
    email: string;
    first_name: string;
    last_name: string;
    phone?: string;
    profile_id: string;
    role_id?: string;
    is_active: boolean;
    __sys_gen_is_deleted: boolean;
    is_deleted?: boolean; // Alias for __sys_gen_is_deleted
    __sys_gen_owner_id?: string;
    owner_id?: string; // Alias for __sys_gen_owner_id
    __sys_gen_created_by_id?: string;
    created_by_id?: string; // Alias for __sys_gen_created_by_id
    __sys_gen_last_modified_by_id?: string;
    last_modified_by_id?: string; // Alias for __sys_gen_last_modified_by_id
    last_login_date?: string;
    __sys_gen_created_date: string;
    created_date?: string; // Alias for __sys_gen_created_date
    __sys_gen_last_modified_date: string;
    last_modified_date?: string; // Alias for __sys_gen_last_modified_date
}

/** _System_Validation - Validation rule definitions */
export interface SystemValidation {
    __sys_gen_id: string;
    id?: string; // Alias for __sys_gen_id
    object_api_name: string;
    name: string;
    active: boolean;
    condition: string;
    error_message: string;
    __sys_gen_created_date: string;
    created_date?: string; // Alias for __sys_gen_created_date
    __sys_gen_last_modified_date: string;
    last_modified_date?: string; // Alias for __sys_gen_last_modified_date
}

/** _System_Webhook - External webhook configurations */
export interface SystemWebhook {
    __sys_gen_id: string;
    id?: string; // Alias for __sys_gen_id
    name: string;
    url: string;
    method: string;
    headers: string;
    auth_type: string;
    auth_config: string;
    is_active: boolean;
    __sys_gen_created_date: string;
    created_date?: string; // Alias for __sys_gen_created_date
    __sys_gen_last_modified_date: string;
    last_modified_date?: string; // Alias for __sys_gen_last_modified_date
}

