// Code generated by cmd/codegen. DO NOT EDIT.
// Source: internal/bootstrap/system_tables.json
// Generated at: 2026-01-08T19:28:20+08:00

package constants

// System Table Names
const (
	TableAIConversation = "_System_AI_Conversation"
	TableAction = "_System_Action"
	TableApp = "_System_App"
	TableApprovalProcess = "_System_ApprovalProcess"
	TableApprovalWorkItem = "_System_ApprovalWorkItem"
	TableAuditLog = "_System_AuditLog"
	TableAutoNumber = "_System_AutoNumber"
	TableComment = "_System_Comment"
	TableConfig = "_System_Config"
	TableDashboard = "_System_Dashboard"
	TableEmailTemplate = "_System_EmailTemplate"
	TableFeedItem = "_System_FeedItem"
	TableField = "_System_Field"
	TableFieldDependency = "_System_FieldDependency"
	TableFieldPerms = "_System_FieldPerms"
	TableFile = "_System_File"
	TableFlow = "_System_Flow"
	TableFlowInstance = "_System_FlowInstance"
	TableFlowStep = "_System_FlowStep"
	TableGroup = "_System_Group"
	TableGroupMember = "_System_GroupMember"
	TableLayout = "_System_Layout"
	TableListView = "_System_ListView"
	TableLog = "_System_Log"
	TableNotification = "_System_Notification"
	TableObject = "_System_Object"
	TableObjectPerms = "_System_ObjectPerms"
	TableOutboxEvent = "_System_OutboxEvent"
	TablePermissionSet = "_System_PermissionSet"
	TablePermissionSetAssignment = "_System_PermissionSetAssignment"
	TableProfile = "_System_Profile"
	TableProfileLayout = "_System_ProfileLayout"
	TableRecent = "_System_Recent"
	TableRecordShare = "_System_RecordShare"
	TableRecordType = "_System_RecordType"
	TableRecycleBin = "_System_RecycleBin"
	TableRelationship = "_System_Relationship"
	TableRole = "_System_Role"
	TableSession = "_System_Session"
	TableSetupPage = "_System_SetupPage"
	TableSharingRule = "_System_SharingRule"
	TableSystemLog = "_System_SystemLog"
	TableTable = "_System_Table"
	TableTeamMember = "_System_TeamMember"
	TableTheme = "_System_Theme"
	TableUIComponent = "_System_UIComponent"
	TableUser = "_System_User"
	TableValidation = "_System_Validation"
	TableWebhook = "_System_Webhook"
)

// AllSystemTableNames returns all system table names for validation
var AllSystemTableNames = []string{
	TableAIConversation,
	TableAction,
	TableApp,
	TableApprovalProcess,
	TableApprovalWorkItem,
	TableAuditLog,
	TableAutoNumber,
	TableComment,
	TableConfig,
	TableDashboard,
	TableEmailTemplate,
	TableFeedItem,
	TableField,
	TableFieldDependency,
	TableFieldPerms,
	TableFile,
	TableFlow,
	TableFlowInstance,
	TableFlowStep,
	TableGroup,
	TableGroupMember,
	TableLayout,
	TableListView,
	TableLog,
	TableNotification,
	TableObject,
	TableObjectPerms,
	TableOutboxEvent,
	TablePermissionSet,
	TablePermissionSetAssignment,
	TableProfile,
	TableProfileLayout,
	TableRecent,
	TableRecordShare,
	TableRecordType,
	TableRecycleBin,
	TableRelationship,
	TableRole,
	TableSession,
	TableSetupPage,
	TableSharingRule,
	TableSystemLog,
	TableTable,
	TableTeamMember,
	TableTheme,
	TableUIComponent,
	TableUser,
	TableValidation,
	TableWebhook,
}
