// Code generated by cmd/codegen. DO NOT EDIT.
// Source: internal/bootstrap/system_tables.json
// Generated at: 2026-01-12T06:46:13+08:00

package constants

// Common field names (backward compatible)
const (
	FieldCreatedByID = "__sys_gen_created_by_id"
	FieldCreatedDate = "__sys_gen_created_date"
	FieldID = "__sys_gen_id"
	FieldIsDeleted = "__sys_gen_is_deleted"
	FieldLastModifiedByID = "__sys_gen_last_modified_by_id"
	FieldLastModifiedDate = "__sys_gen_last_modified_date"
	FieldOwnerID = "__sys_gen_owner_id"
	FieldActionType = "action_type"
	FieldAPIName = "api_name"
	FieldApprovedByID = "approved_by_id"
	FieldApprovedDate = "approved_date"
	FieldApproverID = "approver_id"
	FieldApproverType = "approver_type"
	FieldCategory = "category"
	FieldComments = "comments"
	FieldCondition = "condition"
	FieldConfig = "config"
	FieldCreatedBy = "created_by"
	FieldCurrentStepID = "current_step_id"
	FieldDeletedBy = "deleted_by"
	FieldDeletedDate = "deleted_date"
	FieldDescription = "description"
	FieldDetails = "details"
	FieldEmail = "email"
	FieldEntryCriteria = "entry_criteria"
	FieldExpiresAt = "expires_at"
	FieldFilters = "filters"
	FieldFirstName = "first_name"
	FieldFlowID = "flow_id"
	FieldFlowInstanceID = "flow_instance_id"
	FieldFlowStepID = "flow_step_id"
	FieldIPAddress = "ip_address"
	FieldIsActive = "is_active"
	FieldIsCustom = "is_custom"
	FieldIsManaged = "is_managed"
	FieldIsRevoked = "is_revoked"
	FieldIsSecret = "is_secret"
	FieldIsSystem = "is_system"
	FieldKeyName = "key_name"
	FieldLabel = "label"
	FieldLastActivity = "last_activity"
	FieldLastLoginDate = "last_login_date"
	FieldLastName = "last_name"
	FieldLevel = "level"
	FieldMessage = "message"
	FieldName = "name"
	FieldObjectAPIName = "object_api_name"
	FieldObjectID = "object_id"
	FieldOnFailureStep = "on_failure_step"
	FieldOnSuccessStep = "on_success_step"
	FieldPassword = "password"
	FieldPermissionSetID = "permission_set_id"
	FieldPluralLabel = "plural_label"
	FieldProcessID = "process_id"
	FieldProfileID = "profile_id"
	FieldRecordID = "record_id"
	FieldRecordName = "record_name"
	FieldReferenceTo = "reference_to"
	FieldRequired = "required"
	FieldRoleID = "role_id"
	FieldSchemaVersion = "schema_version"
	FieldSortOrder = "sort_order"
	FieldSource = "source"
	FieldStatus = "status"
	FieldStepName = "step_name"
	FieldStepOrder = "step_order"
	FieldStepType = "step_type"
	FieldSubject = "subject"
	FieldSubmittedDate = "submitted_date"
	FieldTableName = "table_name"
	FieldTableType = "table_type"
	FieldTimestamp = "timestamp"
	FieldToken = "token"
	FieldTriggerObject = "trigger_object"
	FieldTriggerType = "trigger_type"
	FieldType = "type"
	FieldUnique = "unique"
	FieldUserAgent = "user_agent"
	FieldUserID = "user_id"
	FieldUsername = "username"
	FieldValue = "value"
	FieldWorkItemID = "work_item_id"
)

// _System_AI_Conversation fields
const (
	FieldSysAIConversation_CreatedDate = "__sys_gen_created_date"
	FieldSysAIConversation_ID = "__sys_gen_id"
	FieldSysAIConversation_IsDeleted = "__sys_gen_is_deleted"
	FieldSysAIConversation_LastModifiedDate = "__sys_gen_last_modified_date"
	FieldSysAIConversation_IsActive = "is_active"
	FieldSysAIConversation_Messages = "messages"
	FieldSysAIConversation_Title = "title"
	FieldSysAIConversation_UserID = "user_id"
)

// _System_Action fields
const (
	FieldSysAction_CreatedDate = "__sys_gen_created_date"
	FieldSysAction_ID = "__sys_gen_id"
	FieldSysAction_LastModifiedDate = "__sys_gen_last_modified_date"
	FieldSysAction_Config = "config"
	FieldSysAction_Icon = "icon"
	FieldSysAction_Label = "label"
	FieldSysAction_Name = "name"
	FieldSysAction_ObjectAPIName = "object_api_name"
	FieldSysAction_TargetObject = "target_object"
	FieldSysAction_Type = "type"
)

// _System_App fields
const (
	FieldSysApp_CreatedDate = "__sys_gen_created_date"
	FieldSysApp_ID = "__sys_gen_id"
	FieldSysApp_LastModifiedDate = "__sys_gen_last_modified_date"
	FieldSysApp_Color = "color"
	FieldSysApp_Description = "description"
	FieldSysApp_Icon = "icon"
	FieldSysApp_IsDefault = "is_default"
	FieldSysApp_Label = "label"
	FieldSysApp_Name = "name"
	FieldSysApp_NavigationItems = "navigation_items"
)

// _System_ApprovalProcess fields
const (
	FieldSysApprovalProcess_CreatedByID = "__sys_gen_created_by_id"
	FieldSysApprovalProcess_CreatedDate = "__sys_gen_created_date"
	FieldSysApprovalProcess_ID = "__sys_gen_id"
	FieldSysApprovalProcess_IsDeleted = "__sys_gen_is_deleted"
	FieldSysApprovalProcess_LastModifiedByID = "__sys_gen_last_modified_by_id"
	FieldSysApprovalProcess_LastModifiedDate = "__sys_gen_last_modified_date"
	FieldSysApprovalProcess_OwnerID = "__sys_gen_owner_id"
	FieldSysApprovalProcess_ApproverID = "approver_id"
	FieldSysApprovalProcess_ApproverType = "approver_type"
	FieldSysApprovalProcess_Description = "description"
	FieldSysApprovalProcess_EntryCriteria = "entry_criteria"
	FieldSysApprovalProcess_IsActive = "is_active"
	FieldSysApprovalProcess_Name = "name"
	FieldSysApprovalProcess_ObjectAPIName = "object_api_name"
)

// _System_ApprovalWorkItem fields
const (
	FieldSysApprovalWorkItem_CreatedByID = "__sys_gen_created_by_id"
	FieldSysApprovalWorkItem_CreatedDate = "__sys_gen_created_date"
	FieldSysApprovalWorkItem_ID = "__sys_gen_id"
	FieldSysApprovalWorkItem_IsDeleted = "__sys_gen_is_deleted"
	FieldSysApprovalWorkItem_LastModifiedByID = "__sys_gen_last_modified_by_id"
	FieldSysApprovalWorkItem_LastModifiedDate = "__sys_gen_last_modified_date"
	FieldSysApprovalWorkItem_OwnerID = "__sys_gen_owner_id"
	FieldSysApprovalWorkItem_ApprovedByID = "approved_by_id"
	FieldSysApprovalWorkItem_ApprovedDate = "approved_date"
	FieldSysApprovalWorkItem_ApproverID = "approver_id"
	FieldSysApprovalWorkItem_Comments = "comments"
	FieldSysApprovalWorkItem_FlowInstanceID = "flow_instance_id"
	FieldSysApprovalWorkItem_FlowStepID = "flow_step_id"
	FieldSysApprovalWorkItem_ObjectAPIName = "object_api_name"
	FieldSysApprovalWorkItem_ProcessID = "process_id"
	FieldSysApprovalWorkItem_RecordID = "record_id"
	FieldSysApprovalWorkItem_Status = "status"
	FieldSysApprovalWorkItem_SubmittedByID = "submitted_by_id"
	FieldSysApprovalWorkItem_SubmittedDate = "submitted_date"
)

// _System_AuditLog fields
const (
	FieldSysAuditLog_CreatedDate = "__sys_gen_created_date"
	FieldSysAuditLog_ID = "__sys_gen_id"
	FieldSysAuditLog_LastModifiedDate = "__sys_gen_last_modified_date"
	FieldSysAuditLog_ChangedAt = "changed_at"
	FieldSysAuditLog_ChangedByID = "changed_by_id"
	FieldSysAuditLog_FieldName = "field_name"
	FieldSysAuditLog_NewValue = "new_value"
	FieldSysAuditLog_ObjectAPIName = "object_api_name"
	FieldSysAuditLog_OldValue = "old_value"
	FieldSysAuditLog_RecordID = "record_id"
)

// _System_AutoNumber fields
const (
	FieldSysAutoNumber_CreatedDate = "__sys_gen_created_date"
	FieldSysAutoNumber_ID = "__sys_gen_id"
	FieldSysAutoNumber_LastModifiedDate = "__sys_gen_last_modified_date"
	FieldSysAutoNumber_CurrentNumber = "current_number"
	FieldSysAutoNumber_DisplayFormat = "display_format"
	FieldSysAutoNumber_FieldAPIName = "field_api_name"
	FieldSysAutoNumber_ObjectAPIName = "object_api_name"
	FieldSysAutoNumber_StartingNumber = "starting_number"
)

// _System_Comment fields
const (
	FieldSysComment_CreatedByID = "__sys_gen_created_by_id"
	FieldSysComment_CreatedDate = "__sys_gen_created_date"
	FieldSysComment_ID = "__sys_gen_id"
	FieldSysComment_IsDeleted = "__sys_gen_is_deleted"
	FieldSysComment_LastModifiedDate = "__sys_gen_last_modified_date"
	FieldSysComment_Body = "body"
	FieldSysComment_IsResolved = "is_resolved"
	FieldSysComment_ObjectAPIName = "object_api_name"
	FieldSysComment_ParentCommentID = "parent_comment_id"
	FieldSysComment_RecordID = "record_id"
)

// _System_Config fields
const (
	FieldSysConfig_CreatedDate = "__sys_gen_created_date"
	FieldSysConfig_LastModifiedDate = "__sys_gen_last_modified_date"
	FieldSysConfig_Description = "description"
	FieldSysConfig_IsSecret = "is_secret"
	FieldSysConfig_KeyName = "key_name"
	FieldSysConfig_Value = "value"
)

// _System_Dashboard fields
const (
	FieldSysDashboard_CreatedByID = "__sys_gen_created_by_id"
	FieldSysDashboard_CreatedDate = "__sys_gen_created_date"
	FieldSysDashboard_ID = "__sys_gen_id"
	FieldSysDashboard_IsDeleted = "__sys_gen_is_deleted"
	FieldSysDashboard_LastModifiedByID = "__sys_gen_last_modified_by_id"
	FieldSysDashboard_LastModifiedDate = "__sys_gen_last_modified_date"
	FieldSysDashboard_OwnerID = "__sys_gen_owner_id"
	FieldSysDashboard_Description = "description"
	FieldSysDashboard_Layout = "layout"
	FieldSysDashboard_Name = "name"
	FieldSysDashboard_Widgets = "widgets"
)

// _System_EmailTemplate fields
const (
	FieldSysEmailTemplate_CreatedDate = "__sys_gen_created_date"
	FieldSysEmailTemplate_ID = "__sys_gen_id"
	FieldSysEmailTemplate_LastModifiedDate = "__sys_gen_last_modified_date"
	FieldSysEmailTemplate_FromEmail = "from_email"
	FieldSysEmailTemplate_FromName = "from_name"
	FieldSysEmailTemplate_HTMLBody = "html_body"
	FieldSysEmailTemplate_IsActive = "is_active"
	FieldSysEmailTemplate_Name = "name"
	FieldSysEmailTemplate_ReplyTo = "reply_to"
	FieldSysEmailTemplate_Subject = "subject"
	FieldSysEmailTemplate_TextBody = "text_body"
)

// _System_FeedItem fields
const (
	FieldSysFeedItem_CreatedByID = "__sys_gen_created_by_id"
	FieldSysFeedItem_CreatedDate = "__sys_gen_created_date"
	FieldSysFeedItem_ID = "__sys_gen_id"
	FieldSysFeedItem_LastModifiedDate = "__sys_gen_last_modified_date"
	FieldSysFeedItem_Body = "body"
	FieldSysFeedItem_ParentID = "parent_id"
	FieldSysFeedItem_Type = "type"
)

// _System_Field fields
const (
	FieldSysField_CreatedByID = "__sys_gen_created_by_id"
	FieldSysField_CreatedDate = "__sys_gen_created_date"
	FieldSysField_ID = "__sys_gen_id"
	FieldSysField_IsDeleted = "__sys_gen_is_deleted"
	FieldSysField_LastModifiedByID = "__sys_gen_last_modified_by_id"
	FieldSysField_LastModifiedDate = "__sys_gen_last_modified_date"
	FieldSysField_OwnerID = "__sys_gen_owner_id"
	FieldSysField_APIName = "api_name"
	FieldSysField_ControllingField = "controlling_field"
	FieldSysField_DefaultValue = "default_value"
	FieldSysField_DeleteRule = "delete_rule"
	FieldSysField_Description = "description"
	FieldSysField_Formula = "formula"
	FieldSysField_HelpText = "help_text"
	FieldSysField_Indexed = "indexed"
	FieldSysField_IsMasterDetail = "is_master_detail"
	FieldSysField_IsNameField = "is_name_field"
	FieldSysField_IsPolymorphic = "is_polymorphic"
	FieldSysField_IsSystem = "is_system"
	FieldSysField_IsUnique = "is_unique"
	FieldSysField_Label = "label"
	FieldSysField_MaxLength = "max_length"
	FieldSysField_MaxValue = "max_value"
	FieldSysField_MinLength = "min_length"
	FieldSysField_MinValue = "min_value"
	FieldSysField_ObjectID = "object_id"
	FieldSysField_Options = "options"
	FieldSysField_PicklistDependency = "picklist_dependency"
	FieldSysField_ReferenceTo = "reference_to"
	FieldSysField_Regex = "regex"
	FieldSysField_RegexMessage = "regex_message"
	FieldSysField_RelationshipName = "relationship_name"
	FieldSysField_Required = "required"
	FieldSysField_ReturnType = "return_type"
	FieldSysField_RollupConfig = "rollup_config"
	FieldSysField_TrackHistory = "track_history"
	FieldSysField_Type = "type"
	FieldSysField_Validator = "validator"
)

// _System_FieldDependency fields
const (
	FieldSysFieldDependency_CreatedDate = "__sys_gen_created_date"
	FieldSysFieldDependency_ID = "__sys_gen_id"
	FieldSysFieldDependency_LastModifiedDate = "__sys_gen_last_modified_date"
	FieldSysFieldDependency_ControllingFieldID = "controlling_field_id"
	FieldSysFieldDependency_ControllingValue = "controlling_value"
	FieldSysFieldDependency_DependentFieldID = "dependent_field_id"
	FieldSysFieldDependency_DependentValues = "dependent_values"
)

// _System_FieldPerms fields
const (
	FieldSysFieldPerms_CreatedDate = "__sys_gen_created_date"
	FieldSysFieldPerms_ID = "__sys_gen_id"
	FieldSysFieldPerms_LastModifiedDate = "__sys_gen_last_modified_date"
	FieldSysFieldPerms_Editable = "editable"
	FieldSysFieldPerms_FieldAPIName = "field_api_name"
	FieldSysFieldPerms_ObjectAPIName = "object_api_name"
	FieldSysFieldPerms_PermissionSetID = "permission_set_id"
	FieldSysFieldPerms_ProfileID = "profile_id"
	FieldSysFieldPerms_Readable = "readable"
)

// _System_File fields
const (
	FieldSysFile_CreatedByID = "__sys_gen_created_by_id"
	FieldSysFile_CreatedDate = "__sys_gen_created_date"
	FieldSysFile_ID = "__sys_gen_id"
	FieldSysFile_LastModifiedDate = "__sys_gen_last_modified_date"
	FieldSysFile_MimeType = "mime_type"
	FieldSysFile_Name = "name"
	FieldSysFile_ParentID = "parent_id"
	FieldSysFile_SizeBytes = "size_bytes"
	FieldSysFile_StoragePath = "storage_path"
)

// _System_Flow fields
const (
	FieldSysFlow_CreatedByID = "__sys_gen_created_by_id"
	FieldSysFlow_CreatedDate = "__sys_gen_created_date"
	FieldSysFlow_ID = "__sys_gen_id"
	FieldSysFlow_IsDeleted = "__sys_gen_is_deleted"
	FieldSysFlow_LastModifiedByID = "__sys_gen_last_modified_by_id"
	FieldSysFlow_LastModifiedDate = "__sys_gen_last_modified_date"
	FieldSysFlow_OwnerID = "__sys_gen_owner_id"
	FieldSysFlow_ActionConfig = "action_config"
	FieldSysFlow_ActionType = "action_type"
	FieldSysFlow_Description = "description"
	FieldSysFlow_FlowType = "flow_type"
	FieldSysFlow_IsRunning = "is_running"
	FieldSysFlow_LastRunAt = "last_run_at"
	FieldSysFlow_Name = "name"
	FieldSysFlow_NextRunAt = "next_run_at"
	FieldSysFlow_Schedule = "schedule"
	FieldSysFlow_ScheduleTimezone = "schedule_timezone"
	FieldSysFlow_Status = "status"
	FieldSysFlow_TriggerCondition = "trigger_condition"
	FieldSysFlow_TriggerObject = "trigger_object"
	FieldSysFlow_TriggerType = "trigger_type"
)

// _System_FlowInstance fields
const (
	FieldSysFlowInstance_CreatedByID = "__sys_gen_created_by_id"
	FieldSysFlowInstance_CreatedDate = "__sys_gen_created_date"
	FieldSysFlowInstance_ID = "__sys_gen_id"
	FieldSysFlowInstance_IsDeleted = "__sys_gen_is_deleted"
	FieldSysFlowInstance_LastModifiedByID = "__sys_gen_last_modified_by_id"
	FieldSysFlowInstance_LastModifiedDate = "__sys_gen_last_modified_date"
	FieldSysFlowInstance_OwnerID = "__sys_gen_owner_id"
	FieldSysFlowInstance_CompletedDate = "completed_date"
	FieldSysFlowInstance_ContextData = "context_data"
	FieldSysFlowInstance_CurrentStepID = "current_step_id"
	FieldSysFlowInstance_FlowID = "flow_id"
	FieldSysFlowInstance_ObjectAPIName = "object_api_name"
	FieldSysFlowInstance_PausedDate = "paused_date"
	FieldSysFlowInstance_RecordID = "record_id"
	FieldSysFlowInstance_StartedDate = "started_date"
	FieldSysFlowInstance_Status = "status"
)

// _System_FlowStep fields
const (
	FieldSysFlowStep_CreatedByID = "__sys_gen_created_by_id"
	FieldSysFlowStep_CreatedDate = "__sys_gen_created_date"
	FieldSysFlowStep_ID = "__sys_gen_id"
	FieldSysFlowStep_IsDeleted = "__sys_gen_is_deleted"
	FieldSysFlowStep_LastModifiedByID = "__sys_gen_last_modified_by_id"
	FieldSysFlowStep_LastModifiedDate = "__sys_gen_last_modified_date"
	FieldSysFlowStep_OwnerID = "__sys_gen_owner_id"
	FieldSysFlowStep_ActionConfig = "action_config"
	FieldSysFlowStep_ActionType = "action_type"
	FieldSysFlowStep_EntryCondition = "entry_condition"
	FieldSysFlowStep_FlowID = "flow_id"
	FieldSysFlowStep_OnFailureStep = "on_failure_step"
	FieldSysFlowStep_OnSuccessStep = "on_success_step"
	FieldSysFlowStep_StepName = "step_name"
	FieldSysFlowStep_StepOrder = "step_order"
	FieldSysFlowStep_StepType = "step_type"
)

// _System_Group fields
const (
	FieldSysGroup_CreatedDate = "__sys_gen_created_date"
	FieldSysGroup_ID = "__sys_gen_id"
	FieldSysGroup_IsDeleted = "__sys_gen_is_deleted"
	FieldSysGroup_LastModifiedDate = "__sys_gen_last_modified_date"
	FieldSysGroup_Email = "email"
	FieldSysGroup_Label = "label"
	FieldSysGroup_Name = "name"
	FieldSysGroup_Type = "type"
)

// _System_GroupMember fields
const (
	FieldSysGroupMember_CreatedDate = "__sys_gen_created_date"
	FieldSysGroupMember_ID = "__sys_gen_id"
	FieldSysGroupMember_IsDeleted = "__sys_gen_is_deleted"
	FieldSysGroupMember_LastModifiedDate = "__sys_gen_last_modified_date"
	FieldSysGroupMember_GroupID = "group_id"
	FieldSysGroupMember_UserID = "user_id"
)

// _System_Layout fields
const (
	FieldSysLayout_CreatedDate = "__sys_gen_created_date"
	FieldSysLayout_ID = "__sys_gen_id"
	FieldSysLayout_LastModifiedDate = "__sys_gen_last_modified_date"
	FieldSysLayout_Config = "config"
	FieldSysLayout_ObjectAPIName = "object_api_name"
)

// _System_ListView fields
const (
	FieldSysListView_CreatedDate = "__sys_gen_created_date"
	FieldSysListView_ID = "__sys_gen_id"
	FieldSysListView_LastModifiedDate = "__sys_gen_last_modified_date"
	FieldSysListView_Fields = "fields"
	FieldSysListView_FilterExpr = "filter_expr"
	FieldSysListView_Label = "label"
	FieldSysListView_ObjectAPIName = "object_api_name"
)

// _System_Log fields
const (
	FieldSysLog_CreatedDate = "__sys_gen_created_date"
	FieldSysLog_ID = "__sys_gen_id"
	FieldSysLog_LastModifiedDate = "__sys_gen_last_modified_date"
	FieldSysLog_Details = "details"
	FieldSysLog_Level = "level"
	FieldSysLog_Message = "message"
	FieldSysLog_Source = "source"
	FieldSysLog_Timestamp = "timestamp"
)

// _System_Notification fields
const (
	FieldSysNotification_CreatedDate = "__sys_gen_created_date"
	FieldSysNotification_ID = "__sys_gen_id"
	FieldSysNotification_LastModifiedDate = "__sys_gen_last_modified_date"
	FieldSysNotification_Body = "body"
	FieldSysNotification_IsRead = "is_read"
	FieldSysNotification_Link = "link"
	FieldSysNotification_NotificationType = "notification_type"
	FieldSysNotification_RecipientID = "recipient_id"
	FieldSysNotification_Title = "title"
)

// _System_Object fields
const (
	FieldSysObject_CreatedByID = "__sys_gen_created_by_id"
	FieldSysObject_CreatedDate = "__sys_gen_created_date"
	FieldSysObject_ID = "__sys_gen_id"
	FieldSysObject_IsDeleted = "__sys_gen_is_deleted"
	FieldSysObject_LastModifiedByID = "__sys_gen_last_modified_by_id"
	FieldSysObject_LastModifiedDate = "__sys_gen_last_modified_date"
	FieldSysObject_OwnerID = "__sys_gen_owner_id"
	FieldSysObject_APIName = "api_name"
	FieldSysObject_AppID = "app_id"
	FieldSysObject_Description = "description"
	FieldSysObject_Icon = "icon"
	FieldSysObject_IsCustom = "is_custom"
	FieldSysObject_Label = "label"
	FieldSysObject_ListFields = "list_fields"
	FieldSysObject_PathField = "path_field"
	FieldSysObject_PluralLabel = "plural_label"
	FieldSysObject_SharingModel = "sharing_model"
	FieldSysObject_TableType = "table_type"
	FieldSysObject_ThemeColor = "theme_color"
)

// _System_ObjectPerms fields
const (
	FieldSysObjectPerms_CreatedDate = "__sys_gen_created_date"
	FieldSysObjectPerms_ID = "__sys_gen_id"
	FieldSysObjectPerms_LastModifiedDate = "__sys_gen_last_modified_date"
	FieldSysObjectPerms_AllowCreate = "allow_create"
	FieldSysObjectPerms_AllowDelete = "allow_delete"
	FieldSysObjectPerms_AllowEdit = "allow_edit"
	FieldSysObjectPerms_AllowRead = "allow_read"
	FieldSysObjectPerms_ModifyAll = "modify_all"
	FieldSysObjectPerms_ObjectAPIName = "object_api_name"
	FieldSysObjectPerms_PermissionSetID = "permission_set_id"
	FieldSysObjectPerms_ProfileID = "profile_id"
	FieldSysObjectPerms_ViewAll = "view_all"
)

// _System_OutboxEvent fields
const (
	FieldSysOutboxEvent_CreatedDate = "__sys_gen_created_date"
	FieldSysOutboxEvent_ID = "__sys_gen_id"
	FieldSysOutboxEvent_LastModifiedDate = "__sys_gen_last_modified_date"
	FieldSysOutboxEvent_ErrorMessage = "error_message"
	FieldSysOutboxEvent_EventType = "event_type"
	FieldSysOutboxEvent_Payload = "payload"
	FieldSysOutboxEvent_ProcessedDate = "processed_date"
	FieldSysOutboxEvent_RetryCount = "retry_count"
	FieldSysOutboxEvent_Status = "status"
)

// _System_PermissionSet fields
const (
	FieldSysPermissionSet_CreatedDate = "__sys_gen_created_date"
	FieldSysPermissionSet_ID = "__sys_gen_id"
	FieldSysPermissionSet_IsDeleted = "__sys_gen_is_deleted"
	FieldSysPermissionSet_LastModifiedDate = "__sys_gen_last_modified_date"
	FieldSysPermissionSet_Description = "description"
	FieldSysPermissionSet_IsActive = "is_active"
	FieldSysPermissionSet_Label = "label"
	FieldSysPermissionSet_Name = "name"
)

// _System_PermissionSetAssignment fields
const (
	FieldSysPermissionSetAssignment_CreatedDate = "__sys_gen_created_date"
	FieldSysPermissionSetAssignment_ID = "__sys_gen_id"
	FieldSysPermissionSetAssignment_IsDeleted = "__sys_gen_is_deleted"
	FieldSysPermissionSetAssignment_LastModifiedDate = "__sys_gen_last_modified_date"
	FieldSysPermissionSetAssignment_AssigneeID = "assignee_id"
	FieldSysPermissionSetAssignment_PermissionSetID = "permission_set_id"
)

// _System_Profile fields
const (
	FieldSysProfile_CreatedByID = "__sys_gen_created_by_id"
	FieldSysProfile_CreatedDate = "__sys_gen_created_date"
	FieldSysProfile_ID = "__sys_gen_id"
	FieldSysProfile_IsDeleted = "__sys_gen_is_deleted"
	FieldSysProfile_LastModifiedByID = "__sys_gen_last_modified_by_id"
	FieldSysProfile_LastModifiedDate = "__sys_gen_last_modified_date"
	FieldSysProfile_OwnerID = "__sys_gen_owner_id"
	FieldSysProfile_Description = "description"
	FieldSysProfile_IsActive = "is_active"
	FieldSysProfile_IsSystem = "is_system"
	FieldSysProfile_Name = "name"
)

// _System_ProfileLayout fields
const (
	FieldSysProfileLayout_CreatedDate = "__sys_gen_created_date"
	FieldSysProfileLayout_ID = "__sys_gen_id"
	FieldSysProfileLayout_LastModifiedDate = "__sys_gen_last_modified_date"
	FieldSysProfileLayout_LayoutID = "layout_id"
	FieldSysProfileLayout_ObjectAPIName = "object_api_name"
	FieldSysProfileLayout_ProfileID = "profile_id"
)

// _System_Recent fields
const (
	FieldSysRecent_CreatedDate = "__sys_gen_created_date"
	FieldSysRecent_ID = "__sys_gen_id"
	FieldSysRecent_LastModifiedDate = "__sys_gen_last_modified_date"
	FieldSysRecent_ObjectAPIName = "object_api_name"
	FieldSysRecent_RecordID = "record_id"
	FieldSysRecent_RecordName = "record_name"
	FieldSysRecent_Timestamp = "timestamp"
	FieldSysRecent_UserID = "user_id"
)

// _System_RecordShare fields
const (
	FieldSysRecordShare_CreatedByID = "__sys_gen_created_by_id"
	FieldSysRecordShare_CreatedDate = "__sys_gen_created_date"
	FieldSysRecordShare_ID = "__sys_gen_id"
	FieldSysRecordShare_IsDeleted = "__sys_gen_is_deleted"
	FieldSysRecordShare_LastModifiedByID = "__sys_gen_last_modified_by_id"
	FieldSysRecordShare_LastModifiedDate = "__sys_gen_last_modified_date"
	FieldSysRecordShare_AccessLevel = "access_level"
	FieldSysRecordShare_ObjectAPIName = "object_api_name"
	FieldSysRecordShare_Reason = "reason"
	FieldSysRecordShare_RecordID = "record_id"
	FieldSysRecordShare_ShareWithGroupID = "share_with_group_id"
	FieldSysRecordShare_ShareWithUserID = "share_with_user_id"
)

// _System_RecordType fields
const (
	FieldSysRecordType_CreatedDate = "__sys_gen_created_date"
	FieldSysRecordType_ID = "__sys_gen_id"
	FieldSysRecordType_IsDeleted = "__sys_gen_is_deleted"
	FieldSysRecordType_LastModifiedDate = "__sys_gen_last_modified_date"
	FieldSysRecordType_Description = "description"
	FieldSysRecordType_IsActive = "is_active"
	FieldSysRecordType_IsMaster = "is_master"
	FieldSysRecordType_Name = "name"
	FieldSysRecordType_ObjectID = "object_id"
)

// _System_RecycleBin fields
const (
	FieldSysRecycleBin_CreatedDate = "__sys_gen_created_date"
	FieldSysRecycleBin_ID = "__sys_gen_id"
	FieldSysRecycleBin_LastModifiedDate = "__sys_gen_last_modified_date"
	FieldSysRecycleBin_DeletedBy = "deleted_by"
	FieldSysRecycleBin_DeletedDate = "deleted_date"
	FieldSysRecycleBin_ObjectAPIName = "object_api_name"
	FieldSysRecycleBin_RecordID = "record_id"
	FieldSysRecycleBin_RecordName = "record_name"
)

// _System_Relationship fields
const (
	FieldSysRelationship_CreatedDate = "__sys_gen_created_date"
	FieldSysRelationship_ID = "__sys_gen_id"
	FieldSysRelationship_LastModifiedDate = "__sys_gen_last_modified_date"
	FieldSysRelationship_CascadeDelete = "cascade_delete"
	FieldSysRelationship_ChildObjectAPIName = "child_object_api_name"
	FieldSysRelationship_FieldAPIName = "field_api_name"
	FieldSysRelationship_ParentObjectAPIName = "parent_object_api_name"
	FieldSysRelationship_RelatedListFields = "related_list_fields"
	FieldSysRelationship_RelatedListLabel = "related_list_label"
	FieldSysRelationship_RelationshipName = "relationship_name"
	FieldSysRelationship_RelationshipType = "relationship_type"
	FieldSysRelationship_RestrictedDelete = "restricted_delete"
)

// _System_Role fields
const (
	FieldSysRole_CreatedByID = "__sys_gen_created_by_id"
	FieldSysRole_CreatedDate = "__sys_gen_created_date"
	FieldSysRole_ID = "__sys_gen_id"
	FieldSysRole_IsDeleted = "__sys_gen_is_deleted"
	FieldSysRole_LastModifiedByID = "__sys_gen_last_modified_by_id"
	FieldSysRole_LastModifiedDate = "__sys_gen_last_modified_date"
	FieldSysRole_OwnerID = "__sys_gen_owner_id"
	FieldSysRole_Description = "description"
	FieldSysRole_IsActive = "is_active"
	FieldSysRole_Name = "name"
	FieldSysRole_ParentRoleID = "parent_role_id"
)

// _System_Session fields
const (
	FieldSysSession_CreatedDate = "__sys_gen_created_date"
	FieldSysSession_ID = "__sys_gen_id"
	FieldSysSession_LastModifiedDate = "__sys_gen_last_modified_date"
	FieldSysSession_ExpiresAt = "expires_at"
	FieldSysSession_IPAddress = "ip_address"
	FieldSysSession_IsRevoked = "is_revoked"
	FieldSysSession_LastActivity = "last_activity"
	FieldSysSession_Token = "token"
	FieldSysSession_UserAgent = "user_agent"
	FieldSysSession_UserID = "user_id"
)

// _System_SetupPage fields
const (
	FieldSysSetupPage_CreatedDate = "__sys_gen_created_date"
	FieldSysSetupPage_ID = "__sys_gen_id"
	FieldSysSetupPage_LastModifiedDate = "__sys_gen_last_modified_date"
	FieldSysSetupPage_Category = "category"
	FieldSysSetupPage_ComponentName = "component_name"
	FieldSysSetupPage_Description = "description"
	FieldSysSetupPage_Icon = "icon"
	FieldSysSetupPage_IsEnabled = "is_enabled"
	FieldSysSetupPage_Label = "label"
	FieldSysSetupPage_PageOrder = "page_order"
	FieldSysSetupPage_Path = "path"
	FieldSysSetupPage_PermissionRequired = "permission_required"
)

// _System_SharingRule fields
const (
	FieldSysSharingRule_CreatedByID = "__sys_gen_created_by_id"
	FieldSysSharingRule_CreatedDate = "__sys_gen_created_date"
	FieldSysSharingRule_ID = "__sys_gen_id"
	FieldSysSharingRule_IsDeleted = "__sys_gen_is_deleted"
	FieldSysSharingRule_LastModifiedByID = "__sys_gen_last_modified_by_id"
	FieldSysSharingRule_LastModifiedDate = "__sys_gen_last_modified_date"
	FieldSysSharingRule_OwnerID = "__sys_gen_owner_id"
	FieldSysSharingRule_AccessLevel = "access_level"
	FieldSysSharingRule_Criteria = "criteria"
	FieldSysSharingRule_Name = "name"
	FieldSysSharingRule_ObjectAPIName = "object_api_name"
	FieldSysSharingRule_ShareWithGroupID = "share_with_group_id"
	FieldSysSharingRule_ShareWithRoleID = "share_with_role_id"
)

// _System_SystemLog fields
const (
	FieldSysSystemLog_ID = "__sys_gen_id"
	FieldSysSystemLog_Details = "details"
	FieldSysSystemLog_Level = "level"
	FieldSysSystemLog_Message = "message"
	FieldSysSystemLog_Source = "source"
	FieldSysSystemLog_Timestamp = "timestamp"
)

// _System_Table fields
const (
	FieldSysTable_CreatedDate = "__sys_gen_created_date"
	FieldSysTable_ID = "__sys_gen_id"
	FieldSysTable_LastModifiedDate = "__sys_gen_last_modified_date"
	FieldSysTable_Category = "category"
	FieldSysTable_CreatedBy = "created_by"
	FieldSysTable_Description = "description"
	FieldSysTable_IsManaged = "is_managed"
	FieldSysTable_SchemaVersion = "schema_version"
	FieldSysTable_TableName = "table_name"
	FieldSysTable_TableType = "table_type"
)

// _System_TeamMember fields
const (
	FieldSysTeamMember_CreatedByID = "__sys_gen_created_by_id"
	FieldSysTeamMember_CreatedDate = "__sys_gen_created_date"
	FieldSysTeamMember_ID = "__sys_gen_id"
	FieldSysTeamMember_IsDeleted = "__sys_gen_is_deleted"
	FieldSysTeamMember_LastModifiedByID = "__sys_gen_last_modified_by_id"
	FieldSysTeamMember_LastModifiedDate = "__sys_gen_last_modified_date"
	FieldSysTeamMember_AccessLevel = "access_level"
	FieldSysTeamMember_ObjectAPIName = "object_api_name"
	FieldSysTeamMember_RecordID = "record_id"
	FieldSysTeamMember_TeamRole = "team_role"
	FieldSysTeamMember_UserID = "user_id"
)

// _System_Theme fields
const (
	FieldSysTheme_CreatedDate = "__sys_gen_created_date"
	FieldSysTheme_ID = "__sys_gen_id"
	FieldSysTheme_LastModifiedDate = "__sys_gen_last_modified_date"
	FieldSysTheme_Colors = "colors"
	FieldSysTheme_Density = "density"
	FieldSysTheme_IsActive = "is_active"
	FieldSysTheme_LogoURL = "logo_url"
	FieldSysTheme_Name = "name"
)

// _System_UIComponent fields
const (
	FieldSysUIComponent_CreatedDate = "__sys_gen_created_date"
	FieldSysUIComponent_ID = "__sys_gen_id"
	FieldSysUIComponent_LastModifiedDate = "__sys_gen_last_modified_date"
	FieldSysUIComponent_ComponentPath = "component_path"
	FieldSysUIComponent_Description = "description"
	FieldSysUIComponent_IsEmbeddable = "is_embeddable"
	FieldSysUIComponent_Name = "name"
	FieldSysUIComponent_Type = "type"
)

// _System_User fields
const (
	FieldSysUser_CreatedByID = "__sys_gen_created_by_id"
	FieldSysUser_CreatedDate = "__sys_gen_created_date"
	FieldSysUser_ID = "__sys_gen_id"
	FieldSysUser_IsDeleted = "__sys_gen_is_deleted"
	FieldSysUser_LastModifiedByID = "__sys_gen_last_modified_by_id"
	FieldSysUser_LastModifiedDate = "__sys_gen_last_modified_date"
	FieldSysUser_OwnerID = "__sys_gen_owner_id"
	FieldSysUser_Email = "email"
	FieldSysUser_FirstName = "first_name"
	FieldSysUser_IsActive = "is_active"
	FieldSysUser_LastLoginDate = "last_login_date"
	FieldSysUser_LastName = "last_name"
	FieldSysUser_Password = "password"
	FieldSysUser_Phone = "phone"
	FieldSysUser_ProfileID = "profile_id"
	FieldSysUser_RoleID = "role_id"
	FieldSysUser_Username = "username"
)

// _System_Validation fields
const (
	FieldSysValidation_CreatedDate = "__sys_gen_created_date"
	FieldSysValidation_ID = "__sys_gen_id"
	FieldSysValidation_LastModifiedDate = "__sys_gen_last_modified_date"
	FieldSysValidation_Active = "active"
	FieldSysValidation_Condition = "condition"
	FieldSysValidation_ErrorMessage = "error_message"
	FieldSysValidation_Name = "name"
	FieldSysValidation_ObjectAPIName = "object_api_name"
)

// _System_Webhook fields
const (
	FieldSysWebhook_CreatedDate = "__sys_gen_created_date"
	FieldSysWebhook_ID = "__sys_gen_id"
	FieldSysWebhook_LastModifiedDate = "__sys_gen_last_modified_date"
	FieldSysWebhook_AuthConfig = "auth_config"
	FieldSysWebhook_AuthType = "auth_type"
	FieldSysWebhook_Headers = "headers"
	FieldSysWebhook_IsActive = "is_active"
	FieldSysWebhook_Method = "method"
	FieldSysWebhook_Name = "name"
	FieldSysWebhook_URL = "url"
)

