export const API_ENDPOINTS = {
    AUTH: {
        LOGIN: '/api/auth/login',
        LOGOUT: '/api/auth/logout',
        ME: '/api/auth/me',
        REGISTER: '/api/auth/register',
        USERS: '/api/auth/users',
        PROFILES: '/api/auth/profiles',
        PERMISSIONS: '/api/auth/permissions/me',
        // Permission related routes
        PROFILE_PERMISSIONS: (profileId: string) => `/api/auth/profiles/${profileId}/permissions`,
        PROFILE_FIELD_PERMISSIONS: (profileId: string) => `/api/auth/profiles/${profileId}/permissions/fields`,
        PERM_SET_PERMISSIONS: (permSetId: string) => `/api/auth/permission-sets/${permSetId}/permissions`,
        PERM_SET_FIELD_PERMISSIONS: (permSetId: string) => `/api/auth/permission-sets/${permSetId}/permissions/fields`,
        USER_EFFECTIVE_PERMISSIONS: (userId: string) => `/api/auth/users/${userId}/permissions/effective`,
        USER_EFFECTIVE_FIELD_PERMISSIONS: (userId: string) => `/api/auth/users/${userId}/permissions/fields/effective`,
    },
    METADATA: {
        OBJECTS: '/api/metadata/objects',
        FIELDS: (objectApiName: string) => `/api/metadata/objects/${objectApiName}/fields`,
        LAYOUTS: '/api/metadata/layouts',
        APPS: '/api/metadata/apps',
        ACTIONS: (objectApiName: string) => `/api/metadata/actions/${objectApiName}`,
        DASHBOARDS: '/api/metadata/dashboards',
        VALIDATION_RULES: '/api/metadata/validation-rules',
        FIELD_TYPES: '/api/metadata/fieldtypes',
        LIST_VIEWS: '/api/metadata/listviews',
        THEMES: '/api/metadata/themes/active',
        FLOWS: '/api/metadata/flows',
        FLOW: (flowId: string) => `/api/metadata/flows/${flowId}`,
        LAYOUT: (objectApiName: string) => `/api/metadata/layouts/${objectApiName}`,
        LAYOUT_ID: (layoutId: string) => `/api/metadata/layouts/${layoutId}`,
        LAYOUT_ASSIGN: '/api/metadata/layouts/assign',
        DASHBOARD: (id: string) => `/api/metadata/dashboards/${id}`,
        VALIDATION_RULE: (id: string) => `/api/metadata/validation-rules/${id}`,
        LIST_VIEW: (id: string) => `/api/metadata/listviews/${id}`,
        FIELD: (objectApiName: string, fieldApiName: string) => `/api/metadata/objects/${objectApiName}/fields/${fieldApiName}`,
    },
    DATA: {
        RECORDS: (objectName: string) => `/api/data/objects/${objectName}`,
        RECORD: (objectName: string, id: string) => `/api/data/objects/${objectName}/${id}`,
        QUERY: '/api/data/query',
        SEARCH: '/api/data/search',
        SEARCH_OBJECT: (objectApiName: string) => `/api/data/search/${encodeURIComponent(objectApiName)}`,
        RECYCLE_BIN: '/api/data/recyclebin/items',
        RESTORE: (id: string) => `/api/data/recyclebin/restore/${id}`,
        ANALYTICS: '/api/data/analytics/query',
    },
    APPROVALS: {
        SUBMIT: '/api/approvals/submit',
        APPROVE: (workItemId: string) => `/api/approvals/${encodeURIComponent(workItemId)}/approve`,
        REJECT: (workItemId: string) => `/api/approvals/${encodeURIComponent(workItemId)}/reject`,
        PENDING: '/api/approvals/pending',
        HISTORY: (objectApiName: string, recordId: string) => `/api/approvals/history/${encodeURIComponent(objectApiName)}/${encodeURIComponent(recordId)}`,
        FLOW_PROGRESS: (flowInstanceId: string) => `/api/approvals/flow-progress/${encodeURIComponent(flowInstanceId)}`,
        CHECK: (objectApiName: string) => `/api/approvals/check/${encodeURIComponent(objectApiName)}`,
    },
    FLOWS: {
        EXECUTE: (flowId: string) => `/api/flows/${encodeURIComponent(flowId)}/execute`,
    },
    ACTIONS: {
        EXECUTE: (actionId: string) => `/api/actions/execute/${actionId}`,
    },
    FILES: {
        UPLOAD: '/api/files/upload',
    },
    ANALYTICS: {
        QUERY: '/api/analytics/query',
    },
    AGENT: {
        CHAT: '/api/agent/chat',
        CHAT_STREAM: '/api/agent/chat/stream',
        CONTEXT: (query: string) => `/api/agent/context${query}`,
        COMPACT: '/api/agent/compact',
    },
    FEED: {
        RECORD: (recordId: string) => `/api/feed/${encodeURIComponent(recordId)}`,
        COMMENTS: '/api/feed/comments',
    },
};
