// Code generated by cmd/codegen. DO NOT EDIT.
// Source: shared/constants/*.json
// Generated at: 2026-01-04T18:56:03+08:00

// ==================== Profiles ====================

export const PROFILE_IDS = {
    STANDARD_USER: 'standard_user',
    SYSTEM_ADMIN: 'system_admin',
} as const;

export type ProfileId = typeof PROFILE_IDS[keyof typeof PROFILE_IDS];

export interface ProfileMetadata {
    id: ProfileId;
    label: string;
    description: string;
    is_system: boolean;
    is_super_user: boolean;
}

export const SYSTEM_PROFILES: Record<string, ProfileMetadata> = {
    "STANDARD_USER": {
        "id": "standard_user",
        "label": "Standard User",
        "description": "Default user profile with standard permissions as defined by administrators.",
        "is_system": true,
        "is_super_user": false
    },
    "SYSTEM_ADMIN": {
        "id": "system_admin",
        "label": "System Administrator",
        "description": "Full access to all platform features and data. Can modify system configuration.",
        "is_system": true,
        "is_super_user": true
    },
};

export function isSuperUserProfile(profileId: string | undefined): boolean {
    if (!profileId) return false;
    const profile = SYSTEM_PROFILES[profileId];
    return profile?.is_super_user ?? false;
}

export function isSystemProfile(profileId: string | undefined): boolean {
    if (!profileId) return false;
    const profile = SYSTEM_PROFILES[profileId];
    return profile?.is_system ?? false;
}

// ==================== System Tables ====================
// Re-exported from generated-schema.ts for backward compatibility
// SYSTEM_TABLE_NAMES is the single source of truth (generated from backend)

import { SYSTEM_TABLE_NAMES, type SystemTableName } from '../../generated-schema';
export { SYSTEM_TABLE_NAMES, type SystemTableName };

export function isSystemTable(objectApiName: string): boolean {
    return objectApiName.startsWith('_System_');
}

// ==================== Custom Objects ====================

export function isCustomObject(objectApiName: string): boolean {
    return objectApiName.endsWith('__c');
}

// ==================== Object Categories ====================

export const OBJECT_CATEGORIES = {
    "BUSINESS_CUSTOM": "business_custom",
    "SECURITY": "security",
    "SYSTEM_METADATA": "system_metadata",
    "UTILITY": "utility",
} as const;

export type ObjectCategory = typeof OBJECT_CATEGORIES[keyof typeof OBJECT_CATEGORIES];

export function getObjectCategory(objectApiName: string): ObjectCategory {
    if (isSystemTable(objectApiName)) {
        const securityTables: SystemTableName[] = [
            SYSTEM_TABLE_NAMES.SYSTEM_PROFILE,
            SYSTEM_TABLE_NAMES.SYSTEM_ROLE,
            SYSTEM_TABLE_NAMES.SYSTEM_OBJECTPERMS,
            SYSTEM_TABLE_NAMES.SYSTEM_FIELDPERMS,
            SYSTEM_TABLE_NAMES.SYSTEM_SHARINGRULE,
        ];

        const utilityTables: SystemTableName[] = [
            SYSTEM_TABLE_NAMES.SYSTEM_RECYCLEBIN,
            SYSTEM_TABLE_NAMES.SYSTEM_LOG,
            SYSTEM_TABLE_NAMES.SYSTEM_RECENT,
            SYSTEM_TABLE_NAMES.SYSTEM_CONFIG,
        ];

        if (securityTables.includes(objectApiName as SystemTableName)) {
            return OBJECT_CATEGORIES.SECURITY;
        } else if (utilityTables.includes(objectApiName as SystemTableName)) {
            return OBJECT_CATEGORIES.UTILITY;
        }
        return OBJECT_CATEGORIES.SYSTEM_METADATA;
    }

    return OBJECT_CATEGORIES.BUSINESS_CUSTOM;
}

// ==================== Defaults ====================

export const DEFAULTS = {
    "maxPageSize": 1000,
    "orderDir": "DESC",
    "pageSize": 25,
    "userEmail": "unknown@example.com",
    "userName": "Unknown",
} as const;

// ==================== Field Types ====================

export type FieldType = 'AutoNumber' | 'Boolean' | 'Currency' | 'Date' | 'DateTime' | 'Email' | 'Formula' | 'JSON' | 'LongTextArea' | 'Lookup' | 'Number' | 'Password' | 'Percent' | 'Phone' | 'Picklist' | 'RichText' | 'RollupSummary' | 'Text' | 'TextArea' | 'Url';

export interface FieldTypeDefinition {
    sqlType: string | null;
    icon: string;
    label: string;
    description: string;
    isSearchable: boolean;
    isGroupable: boolean;
    isSummable: boolean;
    validationPattern?: string;
    validationMessage?: string;
    isFK?: boolean;
    isVirtual?: boolean;
    isSystemOnly?: boolean;
    operators: string[];
}

export const FIELD_TYPES: Record<FieldType, FieldTypeDefinition> = {
    "AutoNumber": {
        "sqlType": "VARCHAR(255)",
        "icon": "Hash",
        "label": "Auto Number",
        "description": "System-generated sequence number",
        "isSearchable": true,
        "isGroupable": false,
        "isSummable": false,
        "operators": [
            "equals",
            "not_equals",
            "contains",
            "starts_with",
            "ends_with",
        ]
    },
    "Boolean": {
        "sqlType": "BOOLEAN",
        "icon": "ToggleLeft",
        "label": "Checkbox",
        "description": "True/false toggle",
        "isSearchable": false,
        "isGroupable": true,
        "isSummable": false,
        "operators": [
            "equals",
            "not_equals",
        ]
    },
    "Currency": {
        "sqlType": "DECIMAL(18,2)",
        "icon": "DollarSign",
        "label": "Currency",
        "description": "Currency amount with 2 decimal places",
        "isSearchable": false,
        "isGroupable": true,
        "isSummable": true,
        "operators": [
            "equals",
            "not_equals",
            "greater_than",
            "greater_or_equal",
            "less_than",
            "less_or_equal",
            "between",
            "is_null",
            "is_not_null",
        ]
    },
    "Date": {
        "sqlType": "DATE",
        "icon": "Calendar",
        "label": "Date",
        "description": "Date without time component",
        "isSearchable": false,
        "isGroupable": true,
        "isSummable": false,
        "operators": [
            "equals",
            "not_equals",
            "greater_than",
            "greater_or_equal",
            "less_than",
            "less_or_equal",
            "between",
            "is_null",
            "is_not_null",
        ]
    },
    "DateTime": {
        "sqlType": "DATETIME",
        "icon": "Clock",
        "label": "Date/Time",
        "description": "Date with time component",
        "isSearchable": false,
        "isGroupable": false,
        "isSummable": false,
        "operators": [
            "equals",
            "not_equals",
            "greater_than",
            "greater_or_equal",
            "less_than",
            "less_or_equal",
            "between",
            "is_null",
            "is_not_null",
        ]
    },
    "Email": {
        "sqlType": "VARCHAR(255)",
        "icon": "Mail",
        "label": "Email",
        "description": "Email address with validation",
        "isSearchable": true,
        "isGroupable": false,
        "isSummable": false,
        "validationPattern": "^[a-zA-Z0-9._%+\\-]+@[a-zA-Z0-9.\\-]+\\.[a-zA-Z]{2,}$",
        "validationMessage": "invalid email format",
        "operators": [
            "equals",
            "not_equals",
            "contains",
            "starts_with",
            "ends_with",
            "is_null",
            "is_not_null",
        ]
    },
    "Formula": {
        "sqlType": null,
        "icon": "Zap",
        "label": "Formula",
        "description": "Calculated field based on expression",
        "isSearchable": false,
        "isGroupable": false,
        "isSummable": false,
        "isVirtual": true,
        "isSystemOnly": true,
        "operators": [
        ]
    },
    "JSON": {
        "sqlType": "JSON",
        "icon": "Code",
        "label": "JSON",
        "description": "Structured JSON data",
        "isSearchable": false,
        "isGroupable": false,
        "isSummable": false,
        "operators": [
            "is_null",
            "is_not_null",
        ]
    },
    "LongTextArea": {
        "sqlType": "LONGTEXT",
        "icon": "FileText",
        "label": "Long Text Area",
        "description": "Large text field for extensive content",
        "isSearchable": false,
        "isGroupable": false,
        "isSummable": false,
        "operators": [
            "contains",
            "not_contains",
            "is_null",
            "is_not_null",
        ]
    },
    "Lookup": {
        "sqlType": "VARCHAR(36)",
        "icon": "ExternalLink",
        "label": "Lookup",
        "description": "Reference to another object record",
        "isSearchable": true,
        "isGroupable": true,
        "isSummable": false,
        "isFK": true,
        "operators": [
            "equals",
            "not_equals",
            "is_null",
            "is_not_null",
        ]
    },
    "Number": {
        "sqlType": "DECIMAL(18,2)",
        "icon": "Hash",
        "label": "Number",
        "description": "Numeric field with decimal support",
        "isSearchable": false,
        "isGroupable": true,
        "isSummable": true,
        "operators": [
            "equals",
            "not_equals",
            "greater_than",
            "greater_or_equal",
            "less_than",
            "less_or_equal",
            "between",
            "is_null",
            "is_not_null",
        ]
    },
    "Password": {
        "sqlType": "VARCHAR(255)",
        "icon": "Lock",
        "label": "Password",
        "description": "Encrypted password field",
        "isSearchable": false,
        "isGroupable": false,
        "isSummable": false,
        "isSystemOnly": true,
        "operators": [
        ]
    },
    "Percent": {
        "sqlType": "DECIMAL(5,2)",
        "icon": "Percent",
        "label": "Percent",
        "description": "Percentage value",
        "isSearchable": false,
        "isGroupable": true,
        "isSummable": true,
        "operators": [
            "equals",
            "not_equals",
            "greater_than",
            "greater_or_equal",
            "less_than",
            "less_or_equal",
            "between",
            "is_null",
            "is_not_null",
        ]
    },
    "Phone": {
        "sqlType": "VARCHAR(40)",
        "icon": "Phone",
        "label": "Phone",
        "description": "Phone number",
        "isSearchable": true,
        "isGroupable": false,
        "isSummable": false,
        "validationPattern": "^\\+?[1-9]\\d{1,14}$",
        "validationMessage": "invalid phone format",
        "operators": [
            "equals",
            "not_equals",
            "contains",
            "starts_with",
            "is_null",
            "is_not_null",
        ]
    },
    "Picklist": {
        "sqlType": "VARCHAR(255)",
        "icon": "List",
        "label": "Picklist",
        "description": "Single selection from predefined options",
        "isSearchable": true,
        "isGroupable": true,
        "isSummable": false,
        "operators": [
            "equals",
            "not_equals",
            "in",
            "not_in",
            "is_null",
            "is_not_null",
        ]
    },
    "RichText": {
        "sqlType": "LONGTEXT",
        "icon": "Edit3",
        "label": "Rich Text",
        "description": "HTML-formatted text content",
        "isSearchable": false,
        "isGroupable": false,
        "isSummable": false,
        "operators": [
            "contains",
            "not_contains",
            "is_null",
            "is_not_null",
        ]
    },
    "RollupSummary": {
        "sqlType": null,
        "icon": "Sigma",
        "label": "Rollup Summary",
        "description": "Aggregation of child records",
        "isSearchable": false,
        "isGroupable": false,
        "isSummable": false,
        "isVirtual": true,
        "isSystemOnly": true,
        "operators": [
        ]
    },
    "Text": {
        "sqlType": "VARCHAR(255)",
        "icon": "Type",
        "label": "Text",
        "description": "Text field with maximum 255 characters",
        "isSearchable": true,
        "isGroupable": false,
        "isSummable": false,
        "operators": [
            "equals",
            "not_equals",
            "contains",
            "not_contains",
            "starts_with",
            "ends_with",
            "is_null",
            "is_not_null",
        ]
    },
    "TextArea": {
        "sqlType": "TEXT",
        "icon": "AlignLeft",
        "label": "Text Area",
        "description": "Multi-line text field",
        "isSearchable": true,
        "isGroupable": false,
        "isSummable": false,
        "operators": [
            "contains",
            "not_contains",
            "is_null",
            "is_not_null",
        ]
    },
    "Url": {
        "sqlType": "VARCHAR(1024)",
        "icon": "Link",
        "label": "URL",
        "description": "Web address",
        "isSearchable": true,
        "isGroupable": false,
        "isSummable": false,
        "validationPattern": "^https?://[^\\s/$.?#].[^\\s]*$",
        "validationMessage": "invalid URL format",
        "operators": [
            "equals",
            "not_equals",
            "contains",
            "starts_with",
            "is_null",
            "is_not_null",
        ]
    },
};

export function getSqlType(type: FieldType): string | null {
    return FIELD_TYPES[type]?.sqlType ?? null;
}

export function isSearchableType(type: string): boolean {
    return FIELD_TYPES[type as FieldType]?.isSearchable ?? false;
}

export function isGroupableType(type: string): boolean {
    return FIELD_TYPES[type as FieldType]?.isGroupable ?? false;
}

export function isSummableType(type: string): boolean {
    return FIELD_TYPES[type as FieldType]?.isSummable ?? false;
}

// ==================== Operators ====================

export interface OperatorDefinition {
    label: string;
    symbol: string;
    sqlOperator: string;
    sqlPattern?: string;
    requiresRange?: boolean;
    requiresList?: boolean;
    noValue?: boolean;
}

export const OPERATORS: Record<string, OperatorDefinition> = {
    "between": {
        "label": "between",
        "symbol": "↔",
        "sqlOperator": "BETWEEN",
        "requiresRange": true,
    },
    "contains": {
        "label": "contains",
        "symbol": "∋",
        "sqlOperator": "LIKE",
        "sqlPattern": "%{value}%",
    },
    "ends_with": {
        "label": "ends with",
        "symbol": "$",
        "sqlOperator": "LIKE",
        "sqlPattern": "%{value}",
    },
    "equals": {
        "label": "equals",
        "symbol": "=",
        "sqlOperator": "=",
    },
    "greater_or_equal": {
        "label": "greater or equal",
        "symbol": "≥",
        "sqlOperator": ">=",
    },
    "greater_than": {
        "label": "greater than",
        "symbol": ">",
        "sqlOperator": ">",
    },
    "in": {
        "label": "in",
        "symbol": "∈",
        "sqlOperator": "IN",
        "requiresList": true,
    },
    "is_not_null": {
        "label": "is not empty",
        "symbol": "≠∅",
        "sqlOperator": "IS NOT NULL",
        "noValue": true,
    },
    "is_null": {
        "label": "is empty",
        "symbol": "∅",
        "sqlOperator": "IS NULL",
        "noValue": true,
    },
    "less_or_equal": {
        "label": "less or equal",
        "symbol": "≤",
        "sqlOperator": "<=",
    },
    "less_than": {
        "label": "less than",
        "symbol": "<",
        "sqlOperator": "<",
    },
    "not_contains": {
        "label": "does not contain",
        "symbol": "∌",
        "sqlOperator": "NOT LIKE",
        "sqlPattern": "%{value}%",
    },
    "not_equals": {
        "label": "not equal to",
        "symbol": "≠",
        "sqlOperator": "!=",
    },
    "not_in": {
        "label": "not in",
        "symbol": "∉",
        "sqlOperator": "NOT IN",
        "requiresList": true,
    },
    "starts_with": {
        "label": "starts with",
        "symbol": "^",
        "sqlOperator": "LIKE",
        "sqlPattern": "{value}%",
    },
};

export function getOperatorsForType(type: FieldType): string[] {
    return FIELD_TYPES[type]?.operators ?? [];
}
