// Code generated by cmd/codegen. DO NOT EDIT.
// Source: internal/bootstrap/system_tables.json
// Generated at: 2026-01-03T12:49:06+08:00

//go:generate go run ../../../cmd/codegen

package models

import (
	"encoding/json"
	"time"
)

// Ensure imports are used
var (
	_ json.RawMessage
	_ time.Time
)

// GenSystemAIConversation represents the _System_AI_Conversation table (generated).
// Persisted AI conversation history per user
type GenSystemAIConversation struct {
	ID string `json:"id"`
	UserID string `json:"user_id"`
	Title string `json:"title"`
	Messages json.RawMessage `json:"messages"`
	IsActive bool `json:"is_active"`
	CreatedDate time.Time `json:"created_date"`
	LastModifiedDate time.Time `json:"last_modified_date"`
	IsDeleted bool `json:"is_deleted"`
}

// GetTableName returns the database table name for GenSystemAIConversation.
func (GenSystemAIConversation) GetTableName() string {
	return "_System_AI_Conversation"
}

// GenSystemAction represents the _System_Action table (generated).
// UI action definitions
type GenSystemAction struct {
	ID string `json:"id"`
	ObjectAPIName string `json:"object_api_name"`
	Name string `json:"name"`
	Label string `json:"label"`
	Type string `json:"type"`
	Icon *string `json:"icon,omitempty"`
	TargetObject *string `json:"target_object,omitempty"`
	Config json.RawMessage `json:"config,omitempty"`
	CreatedDate time.Time `json:"created_date"`
	LastModifiedDate time.Time `json:"last_modified_date"`
}

// GetTableName returns the database table name for GenSystemAction.
func (GenSystemAction) GetTableName() string {
	return "_System_Action"
}

// GenSystemApp represents the _System_App table (generated).
// Application configurations
type GenSystemApp struct {
	ID string `json:"id"`
	Name string `json:"name"`
	Label string `json:"label"`
	Description string `json:"description"`
	Icon string `json:"icon"`
	Color string `json:"color"`
	NavigationItems json.RawMessage `json:"navigation_items"`
	IsDefault bool `json:"is_default"`
	CreatedDate time.Time `json:"created_date"`
	LastModifiedDate time.Time `json:"last_modified_date"`
}

// GetTableName returns the database table name for GenSystemApp.
func (GenSystemApp) GetTableName() string {
	return "_System_App"
}

// GenSystemApprovalProcess represents the _System_ApprovalProcess table (generated).
// Approval process definitions
type GenSystemApprovalProcess struct {
	ID string `json:"id"`
	Name string `json:"name"`
	ObjectAPIName string `json:"object_api_name"`
	Description *string `json:"description,omitempty"`
	EntryCriteria *string `json:"entry_criteria,omitempty"`
	ApproverType string `json:"approver_type"`
	ApproverID *string `json:"approver_id,omitempty"`
	IsActive bool `json:"is_active"`
	OwnerID *string `json:"owner_id,omitempty"`
	CreatedByID *string `json:"created_by_id,omitempty"`
	CreatedDate time.Time `json:"created_date"`
	LastModifiedByID *string `json:"last_modified_by_id,omitempty"`
	LastModifiedDate *time.Time `json:"last_modified_date,omitempty"`
	IsDeleted bool `json:"is_deleted"`
}

// GetTableName returns the database table name for GenSystemApprovalProcess.
func (GenSystemApprovalProcess) GetTableName() string {
	return "_System_ApprovalProcess"
}

// GenSystemApprovalWorkItem represents the _System_ApprovalWorkItem table (generated).
// Pending approval work items
type GenSystemApprovalWorkItem struct {
	ID string `json:"id"`
	ProcessID string `json:"process_id"`
	FlowInstanceID *string `json:"flow_instance_id,omitempty"`
	FlowStepID *string `json:"flow_step_id,omitempty"`
	ObjectAPIName string `json:"object_api_name"`
	RecordID string `json:"record_id"`
	Status string `json:"status"`
	SubmittedByID *string `json:"submitted_by_id,omitempty"`
	SubmittedDate time.Time `json:"submitted_date"`
	ApproverID *string `json:"approver_id,omitempty"`
	ApprovedByID *string `json:"approved_by_id,omitempty"`
	ApprovedDate *time.Time `json:"approved_date,omitempty"`
	Comments *string `json:"comments,omitempty"`
	OwnerID *string `json:"owner_id,omitempty"`
	CreatedByID *string `json:"created_by_id,omitempty"`
	CreatedDate time.Time `json:"created_date"`
	LastModifiedByID *string `json:"last_modified_by_id,omitempty"`
	LastModifiedDate *time.Time `json:"last_modified_date,omitempty"`
	IsDeleted bool `json:"is_deleted"`
}

// GetTableName returns the database table name for GenSystemApprovalWorkItem.
func (GenSystemApprovalWorkItem) GetTableName() string {
	return "_System_ApprovalWorkItem"
}

// GenSystemAuditLog represents the _System_AuditLog table (generated).
// Field history tracking
type GenSystemAuditLog struct {
	ID string `json:"id"`
	ObjectAPIName string `json:"object_api_name"`
	RecordID string `json:"record_id"`
	FieldName string `json:"field_name"`
	OldValue string `json:"old_value"`
	NewValue string `json:"new_value"`
	ChangedByID string `json:"changed_by_id"`
	ChangedAt time.Time `json:"changed_at"`
	CreatedDate time.Time `json:"created_date"`
	LastModifiedDate time.Time `json:"last_modified_date"`
}

// GetTableName returns the database table name for GenSystemAuditLog.
func (GenSystemAuditLog) GetTableName() string {
	return "_System_AuditLog"
}

// GenSystemAutoNumber represents the _System_AutoNumber table (generated).
// Auto-number sequence tracking
type GenSystemAutoNumber struct {
	ID string `json:"id"`
	ObjectAPIName string `json:"object_api_name"`
	FieldAPIName string `json:"field_api_name"`
	DisplayFormat string `json:"display_format"`
	StartingNumber int `json:"starting_number"`
	CurrentNumber int `json:"current_number"`
	CreatedDate time.Time `json:"created_date"`
	LastModifiedDate time.Time `json:"last_modified_date"`
}

// GetTableName returns the database table name for GenSystemAutoNumber.
func (GenSystemAutoNumber) GetTableName() string {
	return "_System_AutoNumber"
}

// GenSystemComment represents the _System_Comment table (generated).
// User comments on records
type GenSystemComment struct {
	ID string `json:"id"`
	ObjectAPIName string `json:"object_api_name"`
	RecordID string `json:"record_id"`
	Body string `json:"body"`
	CreatedByID string `json:"created_by_id"`
	CreatedDate time.Time `json:"created_date"`
	IsDeleted bool `json:"is_deleted"`
	ParentCommentID *string `json:"parent_comment_id,omitempty"`
	IsResolved bool `json:"is_resolved"`
	LastModifiedDate time.Time `json:"last_modified_date"`
}

// GetTableName returns the database table name for GenSystemComment.
func (GenSystemComment) GetTableName() string {
	return "_System_Comment"
}

// GenSystemConfig represents the _System_Config table (generated).
// System configuration settings
type GenSystemConfig struct {
	KeyName string `json:"key_name"`
	Value string `json:"value"`
	IsSecret bool `json:"is_secret"`
	Description string `json:"description"`
	CreatedDate time.Time `json:"created_date"`
	LastModifiedDate time.Time `json:"last_modified_date"`
}

// GetTableName returns the database table name for GenSystemConfig.
func (GenSystemConfig) GetTableName() string {
	return "_System_Config"
}

// GenSystemDashboard represents the _System_Dashboard table (generated).
// Dashboard configurations with widget-based layouts
type GenSystemDashboard struct {
	ID string `json:"id"`
	Name string `json:"name"`
	Description string `json:"description"`
	Layout string `json:"layout"`
	Widgets json.RawMessage `json:"widgets"`
	CreatedDate time.Time `json:"created_date"`
	LastModifiedDate time.Time `json:"last_modified_date"`
}

// GetTableName returns the database table name for GenSystemDashboard.
func (GenSystemDashboard) GetTableName() string {
	return "_System_Dashboard"
}

// GenSystemEmailTemplate represents the _System_EmailTemplate table (generated).
// Email templates for notifications
type GenSystemEmailTemplate struct {
	ID string `json:"id"`
	Name string `json:"name"`
	Subject string `json:"subject"`
	HTMLBody string `json:"html_body"`
	TextBody string `json:"text_body"`
	FromName string `json:"from_name"`
	FromEmail string `json:"from_email"`
	ReplyTo string `json:"reply_to"`
	IsActive bool `json:"is_active"`
	CreatedDate time.Time `json:"created_date"`
	LastModifiedDate time.Time `json:"last_modified_date"`
}

// GetTableName returns the database table name for GenSystemEmailTemplate.
func (GenSystemEmailTemplate) GetTableName() string {
	return "_System_EmailTemplate"
}

// GenSystemFeedItem represents the _System_FeedItem table (generated).
// Feed items for chatter and notifications
type GenSystemFeedItem struct {
	ID string `json:"id"`
	ParentID string `json:"parent_id"`
	Type string `json:"type"`
	Body string `json:"body"`
	CreatedByID string `json:"created_by_id"`
	CreatedDate time.Time `json:"created_date"`
	LastModifiedDate time.Time `json:"last_modified_date"`
}

// GetTableName returns the database table name for GenSystemFeedItem.
func (GenSystemFeedItem) GetTableName() string {
	return "_System_FeedItem"
}

// GenSystemField represents the _System_Field table (generated).
// Field metadata definitions
type GenSystemField struct {
	ID string `json:"id"`
	ObjectID string `json:"object_id"`
	APIName string `json:"api_name"`
	Label string `json:"label"`
	Type string `json:"type"`
	Required bool `json:"required"`
	Unique bool `json:"unique"`
	IsSystem bool `json:"is_system"`
	IsNameField bool `json:"is_name_field"`
	Indexed bool `json:"indexed"`
	Options json.RawMessage `json:"options,omitempty"`
	ReferenceTo *string `json:"reference_to,omitempty"`
	DeleteRule *string `json:"delete_rule,omitempty"`
	Formula *string `json:"formula,omitempty"`
	ReturnType *string `json:"return_type,omitempty"`
	DefaultValue *string `json:"default_value,omitempty"`
	HelpText *string `json:"help_text,omitempty"`
	Description *string `json:"description,omitempty"`
	TrackHistory bool `json:"track_history"`
	MinValue *float64 `json:"min_value,omitempty"`
	MaxValue *float64 `json:"max_value,omitempty"`
	MinLength *int `json:"min_length,omitempty"`
	MaxLength *int `json:"max_length,omitempty"`
	Regex *string `json:"regex,omitempty"`
	RegexMessage *string `json:"regex_message,omitempty"`
	Validator *string `json:"validator,omitempty"`
	ControllingField *string `json:"controlling_field,omitempty"`
	PicklistDependency json.RawMessage `json:"picklist_dependency,omitempty"`
	RollupConfig json.RawMessage `json:"rollup_config,omitempty"`
	IsMasterDetail bool `json:"is_master_detail"`
	RelationshipName *string `json:"relationship_name,omitempty"`
	IsDeleted bool `json:"is_deleted"`
	OwnerID *string `json:"owner_id,omitempty"`
	CreatedByID *string `json:"created_by_id,omitempty"`
	LastModifiedByID *string `json:"last_modified_by_id,omitempty"`
	CreatedDate time.Time `json:"created_date"`
	LastModifiedDate time.Time `json:"last_modified_date"`
}

// GetTableName returns the database table name for GenSystemField.
func (GenSystemField) GetTableName() string {
	return "_System_Field"
}

// GenSystemFieldDependency represents the _System_FieldDependency table (generated).
// Field dependency rules
type GenSystemFieldDependency struct {
	ID string `json:"id"`
	ControllingFieldID string `json:"controlling_field_id"`
	DependentFieldID string `json:"dependent_field_id"`
	ControllingValue string `json:"controlling_value"`
	DependentValues json.RawMessage `json:"dependent_values"`
	CreatedDate time.Time `json:"created_date"`
	LastModifiedDate time.Time `json:"last_modified_date"`
}

// GetTableName returns the database table name for GenSystemFieldDependency.
func (GenSystemFieldDependency) GetTableName() string {
	return "_System_FieldDependency"
}

// GenSystemFieldPerms represents the _System_FieldPerms table (generated).
// Field permissions for profiles
type GenSystemFieldPerms struct {
	ID string `json:"id"`
	ProfileID *string `json:"profile_id,omitempty"`
	PermissionSetID *string `json:"permission_set_id,omitempty"`
	ObjectAPIName string `json:"object_api_name"`
	FieldAPIName string `json:"field_api_name"`
	Readable bool `json:"readable"`
	Editable bool `json:"editable"`
	CreatedDate time.Time `json:"created_date"`
	LastModifiedDate time.Time `json:"last_modified_date"`
}

// GetTableName returns the database table name for GenSystemFieldPerms.
func (GenSystemFieldPerms) GetTableName() string {
	return "_System_FieldPerms"
}

// GenSystemFile represents the _System_File table (generated).
// File attachments
type GenSystemFile struct {
	ID string `json:"id"`
	ParentID string `json:"parent_id"`
	Name string `json:"name"`
	MimeType string `json:"mime_type"`
	SizeBytes int64 `json:"size_bytes"`
	StoragePath string `json:"storage_path"`
	CreatedByID string `json:"created_by_id"`
	CreatedDate time.Time `json:"created_date"`
	LastModifiedDate time.Time `json:"last_modified_date"`
}

// GetTableName returns the database table name for GenSystemFile.
func (GenSystemFile) GetTableName() string {
	return "_System_File"
}

// GenSystemFlow represents the _System_Flow table (generated).
// Workflow automation definitions
type GenSystemFlow struct {
	ID string `json:"id"`
	Name string `json:"name"`
	TriggerObject string `json:"trigger_object"`
	TriggerType string `json:"trigger_type"`
	TriggerCondition string `json:"trigger_condition"`
	ActionType string `json:"action_type"`
	ActionConfig json.RawMessage `json:"action_config"`
	FlowType string `json:"flow_type"`
	Description *string `json:"description,omitempty"`
	Status string `json:"status"`
	CreatedDate time.Time `json:"created_date"`
	CreatedByID *string `json:"created_by_id,omitempty"`
	LastModifiedByID *string `json:"last_modified_by_id,omitempty"`
	OwnerID *string `json:"owner_id,omitempty"`
	IsDeleted bool `json:"is_deleted"`
	Schedule *string `json:"schedule,omitempty"`
	ScheduleTimezone *string `json:"schedule_timezone,omitempty"`
	LastRunAt *time.Time `json:"last_run_at,omitempty"`
	NextRunAt *time.Time `json:"next_run_at,omitempty"`
	IsRunning bool `json:"is_running"`
	LastModifiedDate time.Time `json:"last_modified_date"`
}

// GetTableName returns the database table name for GenSystemFlow.
func (GenSystemFlow) GetTableName() string {
	return "_System_Flow"
}

// GenSystemFlowInstance represents the _System_FlowInstance table (generated).
// Tracks running and paused flow executions
type GenSystemFlowInstance struct {
	ID string `json:"id"`
	FlowID string `json:"flow_id"`
	ObjectAPIName string `json:"object_api_name"`
	RecordID string `json:"record_id"`
	Status string `json:"status"`
	CurrentStepID *string `json:"current_step_id,omitempty"`
	ContextData json.RawMessage `json:"context_data,omitempty"`
	StartedDate time.Time `json:"started_date"`
	PausedDate *time.Time `json:"paused_date,omitempty"`
	CompletedDate *time.Time `json:"completed_date,omitempty"`
	OwnerID *string `json:"owner_id,omitempty"`
	CreatedByID *string `json:"created_by_id,omitempty"`
	CreatedDate time.Time `json:"created_date"`
	LastModifiedByID *string `json:"last_modified_by_id,omitempty"`
	LastModifiedDate *time.Time `json:"last_modified_date,omitempty"`
	IsDeleted bool `json:"is_deleted"`
}

// GetTableName returns the database table name for GenSystemFlowInstance.
func (GenSystemFlowInstance) GetTableName() string {
	return "_System_FlowInstance"
}

// GenSystemFlowStep represents the _System_FlowStep table (generated).
// Step definitions for multi-step flows
type GenSystemFlowStep struct {
	ID string `json:"id"`
	FlowID string `json:"flow_id"`
	StepOrder int `json:"step_order"`
	StepName string `json:"step_name"`
	StepType string `json:"step_type"`
	ActionType *string `json:"action_type,omitempty"`
	ActionConfig json.RawMessage `json:"action_config,omitempty"`
	EntryCondition *string `json:"entry_condition,omitempty"`
	OnSuccessStep *string `json:"on_success_step,omitempty"`
	OnFailureStep *string `json:"on_failure_step,omitempty"`
	CreatedDate time.Time `json:"created_date"`
	CreatedByID *string `json:"created_by_id,omitempty"`
	LastModifiedByID *string `json:"last_modified_by_id,omitempty"`
	OwnerID *string `json:"owner_id,omitempty"`
	IsDeleted bool `json:"is_deleted"`
	LastModifiedDate time.Time `json:"last_modified_date"`
}

// GetTableName returns the database table name for GenSystemFlowStep.
func (GenSystemFlowStep) GetTableName() string {
	return "_System_FlowStep"
}

// GenSystemGroup represents the _System_Group table (generated).
// Groups and Queues
type GenSystemGroup struct {
	ID string `json:"id"`
	Name string `json:"name"`
	Label string `json:"label"`
	Type string `json:"type"`
	Email *string `json:"email,omitempty"`
	CreatedDate time.Time `json:"created_date"`
	IsDeleted bool `json:"is_deleted"`
	LastModifiedDate time.Time `json:"last_modified_date"`
}

// GetTableName returns the database table name for GenSystemGroup.
func (GenSystemGroup) GetTableName() string {
	return "_System_Group"
}

// GenSystemGroupMember represents the _System_GroupMember table (generated).
// Group membership
type GenSystemGroupMember struct {
	ID string `json:"id"`
	GroupID string `json:"group_id"`
	UserID string `json:"user_id"`
	CreatedDate time.Time `json:"created_date"`
	IsDeleted bool `json:"is_deleted"`
	LastModifiedDate time.Time `json:"last_modified_date"`
}

// GetTableName returns the database table name for GenSystemGroupMember.
func (GenSystemGroupMember) GetTableName() string {
	return "_System_GroupMember"
}

// GenSystemLayout represents the _System_Layout table (generated).
// Page layout configurations
type GenSystemLayout struct {
	ID string `json:"id"`
	ObjectAPIName string `json:"object_api_name"`
	Config json.RawMessage `json:"config"`
	CreatedDate time.Time `json:"created_date"`
	LastModifiedDate time.Time `json:"last_modified_date"`
}

// GetTableName returns the database table name for GenSystemLayout.
func (GenSystemLayout) GetTableName() string {
	return "_System_Layout"
}

// GenSystemListView represents the _System_ListView table (generated).
// List view configurations
type GenSystemListView struct {
	ID string `json:"id"`
	ObjectAPIName string `json:"object_api_name"`
	Label string `json:"label"`
	Filters json.RawMessage `json:"filters"`
	Fields json.RawMessage `json:"fields"`
	CreatedDate time.Time `json:"created_date"`
	LastModifiedDate time.Time `json:"last_modified_date"`
}

// GetTableName returns the database table name for GenSystemListView.
func (GenSystemListView) GetTableName() string {
	return "_System_ListView"
}

// GenSystemLog represents the _System_Log table (generated).
// System event logs
type GenSystemLog struct {
	ID string `json:"id"`
	Timestamp time.Time `json:"timestamp"`
	Level string `json:"level"`
	Source string `json:"source"`
	Message string `json:"message"`
	Details *string `json:"details,omitempty"`
	CreatedDate time.Time `json:"created_date"`
	LastModifiedDate time.Time `json:"last_modified_date"`
}

// GetTableName returns the database table name for GenSystemLog.
func (GenSystemLog) GetTableName() string {
	return "_System_Log"
}

// GenSystemNotification represents the _System_Notification table (generated).
// User notifications
type GenSystemNotification struct {
	ID string `json:"id"`
	RecipientID string `json:"recipient_id"`
	Title string `json:"title"`
	Body string `json:"body"`
	Link string `json:"link"`
	IsRead bool `json:"is_read"`
	NotificationType string `json:"notification_type"`
	CreatedDate time.Time `json:"created_date"`
	LastModifiedDate time.Time `json:"last_modified_date"`
}

// GetTableName returns the database table name for GenSystemNotification.
func (GenSystemNotification) GetTableName() string {
	return "_System_Notification"
}

// GenSystemObject represents the _System_Object table (generated).
// Object metadata definitions
type GenSystemObject struct {
	ID string `json:"id"`
	APIName string `json:"api_name"`
	TableType string `json:"table_type"`
	Label string `json:"label"`
	PluralLabel *string `json:"plural_label,omitempty"`
	AppID *string `json:"app_id,omitempty"`
	Icon *string `json:"icon,omitempty"`
	Description string `json:"description"`
	ThemeColor *string `json:"theme_color,omitempty"`
	IsCustom bool `json:"is_custom"`
	SharingModel string `json:"sharing_model"`
	PathField *string `json:"path_field,omitempty"`
	ListFields json.RawMessage `json:"list_fields,omitempty"`
	IsDeleted bool `json:"is_deleted"`
	OwnerID *string `json:"owner_id,omitempty"`
	CreatedByID *string `json:"created_by_id,omitempty"`
	LastModifiedByID *string `json:"last_modified_by_id,omitempty"`
	CreatedDate time.Time `json:"created_date"`
	LastModifiedDate time.Time `json:"last_modified_date"`
}

// GetTableName returns the database table name for GenSystemObject.
func (GenSystemObject) GetTableName() string {
	return "_System_Object"
}

// GenSystemObjectPerms represents the _System_ObjectPerms table (generated).
// Object permissions for profiles
type GenSystemObjectPerms struct {
	ID string `json:"id"`
	ProfileID *string `json:"profile_id,omitempty"`
	PermissionSetID *string `json:"permission_set_id,omitempty"`
	ObjectAPIName string `json:"object_api_name"`
	AllowRead bool `json:"allow_read"`
	AllowCreate bool `json:"allow_create"`
	AllowEdit bool `json:"allow_edit"`
	AllowDelete bool `json:"allow_delete"`
	ViewAll bool `json:"view_all"`
	ModifyAll bool `json:"modify_all"`
	CreatedDate time.Time `json:"created_date"`
	LastModifiedDate time.Time `json:"last_modified_date"`
}

// GetTableName returns the database table name for GenSystemObjectPerms.
func (GenSystemObjectPerms) GetTableName() string {
	return "_System_ObjectPerms"
}

// GenSystemOutboxEvent represents the _System_OutboxEvent table (generated).
// Transactional event outbox for guaranteed delivery
type GenSystemOutboxEvent struct {
	ID string `json:"id"`
	EventType string `json:"event_type"`
	Payload json.RawMessage `json:"payload"`
	Status string `json:"status"`
	RetryCount int `json:"retry_count"`
	ErrorMessage *string `json:"error_message,omitempty"`
	ProcessedDate *time.Time `json:"processed_date,omitempty"`
	CreatedDate time.Time `json:"created_date"`
	LastModifiedDate time.Time `json:"last_modified_date"`
}

// GetTableName returns the database table name for GenSystemOutboxEvent.
func (GenSystemOutboxEvent) GetTableName() string {
	return "_System_OutboxEvent"
}

// GenSystemPermissionSet represents the _System_PermissionSet table (generated).
// Additive permission sets
type GenSystemPermissionSet struct {
	ID string `json:"id"`
	Name string `json:"name"`
	Label string `json:"label"`
	Description string `json:"description"`
	IsActive bool `json:"is_active"`
	CreatedDate time.Time `json:"created_date"`
	IsDeleted bool `json:"is_deleted"`
	LastModifiedDate time.Time `json:"last_modified_date"`
}

// GetTableName returns the database table name for GenSystemPermissionSet.
func (GenSystemPermissionSet) GetTableName() string {
	return "_System_PermissionSet"
}

// GenSystemPermissionSetAssignment represents the _System_PermissionSetAssignment table (generated).
// Assignment of permission sets to users
type GenSystemPermissionSetAssignment struct {
	ID string `json:"id"`
	AssigneeID string `json:"assignee_id"`
	PermissionSetID string `json:"permission_set_id"`
	CreatedDate time.Time `json:"created_date"`
	IsDeleted bool `json:"is_deleted"`
	LastModifiedDate time.Time `json:"last_modified_date"`
}

// GetTableName returns the database table name for GenSystemPermissionSetAssignment.
func (GenSystemPermissionSetAssignment) GetTableName() string {
	return "_System_PermissionSetAssignment"
}

// GenSystemProfile represents the _System_Profile table (generated).
// User profiles and permission sets
type GenSystemProfile struct {
	ID string `json:"id"`
	Name string `json:"name"`
	Description string `json:"description"`
	IsActive bool `json:"is_active"`
	IsSystem bool `json:"is_system"`
	IsDeleted bool `json:"is_deleted"`
	OwnerID *string `json:"owner_id,omitempty"`
	CreatedByID *string `json:"created_by_id,omitempty"`
	LastModifiedByID *string `json:"last_modified_by_id,omitempty"`
	CreatedDate time.Time `json:"created_date"`
	LastModifiedDate time.Time `json:"last_modified_date"`
}

// GetTableName returns the database table name for GenSystemProfile.
func (GenSystemProfile) GetTableName() string {
	return "_System_Profile"
}

// GenSystemProfileLayout represents the _System_ProfileLayout table (generated).
// Profile to layout assignments
type GenSystemProfileLayout struct {
	ProfileID string `json:"profile_id"`
	ObjectAPIName string `json:"object_api_name"`
	LayoutID string `json:"layout_id"`
	CreatedDate time.Time `json:"created_date"`
	LastModifiedDate time.Time `json:"last_modified_date"`
}

// GetTableName returns the database table name for GenSystemProfileLayout.
func (GenSystemProfileLayout) GetTableName() string {
	return "_System_ProfileLayout"
}

// GenSystemRecent represents the _System_Recent table (generated).
// Recently viewed records
type GenSystemRecent struct {
	ID string `json:"id"`
	UserID string `json:"user_id"`
	ObjectAPIName string `json:"object_api_name"`
	RecordID string `json:"record_id"`
	RecordName string `json:"record_name"`
	Timestamp time.Time `json:"timestamp"`
	CreatedDate time.Time `json:"created_date"`
	LastModifiedDate time.Time `json:"last_modified_date"`
}

// GetTableName returns the database table name for GenSystemRecent.
func (GenSystemRecent) GetTableName() string {
	return "_System_Recent"
}

// GenSystemRecordShare represents the _System_RecordShare table (generated).
// Manual record sharing with users or groups
type GenSystemRecordShare struct {
	ID string `json:"id"`
	ObjectAPIName string `json:"object_api_name"`
	RecordID string `json:"record_id"`
	ShareWithUserID *string `json:"share_with_user_id,omitempty"`
	ShareWithGroupID *string `json:"share_with_group_id,omitempty"`
	AccessLevel string `json:"access_level"`
	Reason string `json:"reason"`
	CreatedByID *string `json:"created_by_id,omitempty"`
	CreatedDate time.Time `json:"created_date"`
	LastModifiedByID *string `json:"last_modified_by_id,omitempty"`
	LastModifiedDate *time.Time `json:"last_modified_date,omitempty"`
	IsDeleted bool `json:"is_deleted"`
}

// GetTableName returns the database table name for GenSystemRecordShare.
func (GenSystemRecordShare) GetTableName() string {
	return "_System_RecordShare"
}

// GenSystemRecordType represents the _System_RecordType table (generated).
// Record type configurations
type GenSystemRecordType struct {
	ID string `json:"id"`
	ObjectID string `json:"object_id"`
	Name string `json:"name"`
	Description string `json:"description"`
	IsActive bool `json:"is_active"`
	IsMaster bool `json:"is_master"`
	IsDeleted bool `json:"is_deleted"`
	CreatedDate time.Time `json:"created_date"`
	LastModifiedDate time.Time `json:"last_modified_date"`
}

// GetTableName returns the database table name for GenSystemRecordType.
func (GenSystemRecordType) GetTableName() string {
	return "_System_RecordType"
}

// GenSystemRecycleBin represents the _System_RecycleBin table (generated).
// Recycle bin for soft-deleted records
type GenSystemRecycleBin struct {
	ID string `json:"id"`
	RecordID string `json:"record_id"`
	ObjectAPIName string `json:"object_api_name"`
	RecordName string `json:"record_name"`
	DeletedBy string `json:"deleted_by"`
	DeletedDate time.Time `json:"deleted_date"`
	CreatedDate time.Time `json:"created_date"`
	LastModifiedDate time.Time `json:"last_modified_date"`
}

// GetTableName returns the database table name for GenSystemRecycleBin.
func (GenSystemRecycleBin) GetTableName() string {
	return "_System_RecycleBin"
}

// GenSystemRelationship represents the _System_Relationship table (generated).
// Object relationship definitions
type GenSystemRelationship struct {
	ID string `json:"id"`
	ChildObjectAPIName string `json:"child_object_api_name"`
	ParentObjectAPIName string `json:"parent_object_api_name"`
	FieldAPIName string `json:"field_api_name"`
	RelationshipName string `json:"relationship_name"`
	RelationshipType string `json:"relationship_type"`
	CascadeDelete bool `json:"cascade_delete"`
	RestrictedDelete bool `json:"restricted_delete"`
	RelatedListLabel string `json:"related_list_label"`
	RelatedListFields string `json:"related_list_fields"`
	CreatedDate time.Time `json:"created_date"`
	LastModifiedDate time.Time `json:"last_modified_date"`
}

// GetTableName returns the database table name for GenSystemRelationship.
func (GenSystemRelationship) GetTableName() string {
	return "_System_Relationship"
}

// GenSystemRole represents the _System_Role table (generated).
// Role hierarchy for access control
type GenSystemRole struct {
	ID string `json:"id"`
	Name string `json:"name"`
	Description string `json:"description"`
	ParentRoleID *string `json:"parent_role_id,omitempty"`
	IsActive bool `json:"is_active"`
	IsDeleted bool `json:"is_deleted"`
	OwnerID *string `json:"owner_id,omitempty"`
	CreatedByID *string `json:"created_by_id,omitempty"`
	LastModifiedByID *string `json:"last_modified_by_id,omitempty"`
	CreatedDate time.Time `json:"created_date"`
	LastModifiedDate time.Time `json:"last_modified_date"`
}

// GetTableName returns the database table name for GenSystemRole.
func (GenSystemRole) GetTableName() string {
	return "_System_Role"
}

// GenSystemSession represents the _System_Session table (generated).
// User authentication sessions
type GenSystemSession struct {
	ID string `json:"id"`
	UserID string `json:"user_id"`
	Token string `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
	LastActivity time.Time `json:"last_activity"`
	IpAddress string `json:"ip_address"`
	UserAgent string `json:"user_agent"`
	IsRevoked bool `json:"is_revoked"`
	CreatedDate time.Time `json:"created_date"`
	LastModifiedDate time.Time `json:"last_modified_date"`
}

// GetTableName returns the database table name for GenSystemSession.
func (GenSystemSession) GetTableName() string {
	return "_System_Session"
}

// GenSystemSetupPage represents the _System_SetupPage table (generated).
// Setup page definitions
type GenSystemSetupPage struct {
	ID string `json:"id"`
	Label string `json:"label"`
	Icon *string `json:"icon,omitempty"`
	ComponentName string `json:"component_name"`
	Category string `json:"category"`
	PageOrder int `json:"page_order"`
	PermissionRequired *string `json:"permission_required,omitempty"`
	IsEnabled bool `json:"is_enabled"`
	Description *string `json:"description,omitempty"`
	Path *string `json:"path,omitempty"`
	CreatedDate time.Time `json:"created_date"`
	LastModifiedDate time.Time `json:"last_modified_date"`
}

// GetTableName returns the database table name for GenSystemSetupPage.
func (GenSystemSetupPage) GetTableName() string {
	return "_System_SetupPage"
}

// GenSystemSharingRule represents the _System_SharingRule table (generated).
// Record sharing rules
type GenSystemSharingRule struct {
	ID string `json:"id"`
	ObjectAPIName string `json:"object_api_name"`
	Name string `json:"name"`
	Criteria string `json:"criteria"`
	AccessLevel string `json:"access_level"`
	ShareWithRoleID *string `json:"share_with_role_id,omitempty"`
	ShareWithGroupID *string `json:"share_with_group_id,omitempty"`
	IsDeleted bool `json:"is_deleted"`
	OwnerID *string `json:"owner_id,omitempty"`
	CreatedByID *string `json:"created_by_id,omitempty"`
	LastModifiedByID *string `json:"last_modified_by_id,omitempty"`
	CreatedDate time.Time `json:"created_date"`
	LastModifiedDate time.Time `json:"last_modified_date"`
}

// GetTableName returns the database table name for GenSystemSharingRule.
func (GenSystemSharingRule) GetTableName() string {
	return "_System_SharingRule"
}

// GenSystemTable represents the _System_Table table (generated).
// Meta-metadata registry cataloging all tables
type GenSystemTable struct {
	ID string `json:"id"`
	TableName string `json:"table_name"`
	TableType string `json:"table_type"`
	Category string `json:"category"`
	Description string `json:"description"`
	IsManaged bool `json:"is_managed"`
	SchemaVersion string `json:"schema_version"`
	CreatedBy string `json:"created_by"`
	CreatedDate time.Time `json:"created_date"`
	LastModifiedDate time.Time `json:"last_modified_date"`
}

// GetTableName returns the database table name for GenSystemTable.
func (GenSystemTable) GetTableName() string {
	return "_System_Table"
}

// GenSystemTeamMember represents the _System_TeamMember table (generated).
// Generic record team members
type GenSystemTeamMember struct {
	ID string `json:"id"`
	ObjectAPIName string `json:"object_api_name"`
	RecordID string `json:"record_id"`
	UserID string `json:"user_id"`
	TeamRole string `json:"team_role"`
	AccessLevel string `json:"access_level"`
	CreatedByID *string `json:"created_by_id,omitempty"`
	CreatedDate time.Time `json:"created_date"`
	LastModifiedByID *string `json:"last_modified_by_id,omitempty"`
	LastModifiedDate *time.Time `json:"last_modified_date,omitempty"`
	IsDeleted bool `json:"is_deleted"`
}

// GetTableName returns the database table name for GenSystemTeamMember.
func (GenSystemTeamMember) GetTableName() string {
	return "_System_TeamMember"
}

// GenSystemTheme represents the _System_Theme table (generated).
// Visual theme configurations
type GenSystemTheme struct {
	ID string `json:"id"`
	Name string `json:"name"`
	IsActive bool `json:"is_active"`
	Colors json.RawMessage `json:"colors"`
	Density string `json:"density"`
	LogoURL *string `json:"logo_url,omitempty"`
	CreatedDate time.Time `json:"created_date"`
	LastModifiedDate time.Time `json:"last_modified_date"`
}

// GetTableName returns the database table name for GenSystemTheme.
func (GenSystemTheme) GetTableName() string {
	return "_System_Theme"
}

// GenSystemUIComponent represents the _System_UIComponent table (generated).
// Registered UI components
type GenSystemUIComponent struct {
	ID string `json:"id"`
	Name string `json:"name"`
	Type string `json:"type"`
	IsEmbeddable bool `json:"is_embeddable"`
	Description string `json:"description"`
	ComponentPath *string `json:"component_path,omitempty"`
	CreatedDate time.Time `json:"created_date"`
	LastModifiedDate time.Time `json:"last_modified_date"`
}

// GetTableName returns the database table name for GenSystemUIComponent.
func (GenSystemUIComponent) GetTableName() string {
	return "_System_UIComponent"
}

// GenSystemUser represents the _System_User table (generated).
// System users
type GenSystemUser struct {
	ID string `json:"id"`
	Username string `json:"username"`
	Email string `json:"email"`
	Password string `json:"-"`
	FirstName string `json:"first_name"`
	LastName string `json:"last_name"`
	Phone *string `json:"phone,omitempty"`
	ProfileID string `json:"profile_id"`
	RoleID *string `json:"role_id,omitempty"`
	IsActive bool `json:"is_active"`
	IsDeleted bool `json:"is_deleted"`
	OwnerID *string `json:"owner_id,omitempty"`
	CreatedByID *string `json:"created_by_id,omitempty"`
	LastModifiedByID *string `json:"last_modified_by_id,omitempty"`
	LastLoginDate *time.Time `json:"last_login_date,omitempty"`
	CreatedDate time.Time `json:"created_date"`
	LastModifiedDate time.Time `json:"last_modified_date"`
}

// GetTableName returns the database table name for GenSystemUser.
func (GenSystemUser) GetTableName() string {
	return "_System_User"
}

// GenSystemValidation represents the _System_Validation table (generated).
// Validation rule definitions
type GenSystemValidation struct {
	ID string `json:"id"`
	ObjectAPIName string `json:"object_api_name"`
	Name string `json:"name"`
	Active bool `json:"active"`
	Condition string `json:"condition"`
	ErrorMessage string `json:"error_message"`
	CreatedDate time.Time `json:"created_date"`
	LastModifiedDate time.Time `json:"last_modified_date"`
}

// GetTableName returns the database table name for GenSystemValidation.
func (GenSystemValidation) GetTableName() string {
	return "_System_Validation"
}

// GenSystemWebhook represents the _System_Webhook table (generated).
// External webhook configurations
type GenSystemWebhook struct {
	ID string `json:"id"`
	Name string `json:"name"`
	URL string `json:"url"`
	Method string `json:"method"`
	Headers string `json:"headers"`
	AuthType string `json:"auth_type"`
	AuthConfig string `json:"auth_config"`
	IsActive bool `json:"is_active"`
	CreatedDate time.Time `json:"created_date"`
	LastModifiedDate time.Time `json:"last_modified_date"`
}

// GetTableName returns the database table name for GenSystemWebhook.
func (GenSystemWebhook) GetTableName() string {
	return "_System_Webhook"
}

