// Code generated by cmd/codegen. DO NOT EDIT.
// Source: internal/bootstrap/system_tables.json
// Generated at: 2026-01-10T07:36:43+08:00

//go:generate go run ../../../cmd/codegen

package models

import (
	"encoding/json"
	"time"
)

// Ensure imports are used
var (
	_ json.RawMessage
	_ time.Time
)

// SystemAIConversation represents the _System_AI_Conversation table (generated).
// Persisted AI conversation history per user
type SystemAIConversation struct {
	ID string `json:"__sys_gen_id"`
	UserID string `json:"user_id"`
	Title string `json:"title"`
	Messages json.RawMessage `json:"messages"`
	IsActive bool `json:"is_active"`
	CreatedDate time.Time `json:"__sys_gen_created_date"`
	LastModifiedDate time.Time `json:"__sys_gen_last_modified_date"`
	IsDeleted bool `json:"__sys_gen_is_deleted"`
}

// GetTableName returns the database table name for SystemAIConversation.
func (SystemAIConversation) GetTableName() string {
	return "_System_AI_Conversation"
}

// SystemAction represents the _System_Action table (generated).
// UI action definitions
type SystemAction struct {
	ID string `json:"__sys_gen_id"`
	ObjectAPIName string `json:"object_api_name"`
	Name string `json:"name"`
	Label string `json:"label"`
	Type string `json:"type"`
	Icon *string `json:"icon,omitempty"`
	TargetObject *string `json:"target_object,omitempty"`
	Config json.RawMessage `json:"config,omitempty"`
	CreatedDate time.Time `json:"__sys_gen_created_date"`
	LastModifiedDate time.Time `json:"__sys_gen_last_modified_date"`
}

// GetTableName returns the database table name for SystemAction.
func (SystemAction) GetTableName() string {
	return "_System_Action"
}

// SystemApp represents the _System_App table (generated).
// Application configurations
type SystemApp struct {
	ID string `json:"__sys_gen_id"`
	Name string `json:"name"`
	Label string `json:"label"`
	Description string `json:"description"`
	Icon string `json:"icon"`
	Color string `json:"color"`
	NavigationItems json.RawMessage `json:"navigation_items"`
	IsDefault bool `json:"is_default"`
	CreatedDate time.Time `json:"__sys_gen_created_date"`
	LastModifiedDate time.Time `json:"__sys_gen_last_modified_date"`
}

// GetTableName returns the database table name for SystemApp.
func (SystemApp) GetTableName() string {
	return "_System_App"
}

// SystemApprovalProcess represents the _System_ApprovalProcess table (generated).
// Approval process definitions
type SystemApprovalProcess struct {
	ID string `json:"__sys_gen_id"`
	Name string `json:"name"`
	ObjectAPIName string `json:"object_api_name"`
	Description *string `json:"description,omitempty"`
	EntryCriteria *string `json:"entry_criteria,omitempty"`
	ApproverType string `json:"approver_type"`
	ApproverID *string `json:"approver_id,omitempty"`
	IsActive bool `json:"is_active"`
	OwnerID *string `json:"__sys_gen_owner_id,omitempty"`
	CreatedByID *string `json:"__sys_gen_created_by_id,omitempty"`
	CreatedDate time.Time `json:"__sys_gen_created_date"`
	LastModifiedByID *string `json:"__sys_gen_last_modified_by_id,omitempty"`
	LastModifiedDate *time.Time `json:"__sys_gen_last_modified_date,omitempty"`
	IsDeleted bool `json:"__sys_gen_is_deleted"`
}

// GetTableName returns the database table name for SystemApprovalProcess.
func (SystemApprovalProcess) GetTableName() string {
	return "_System_ApprovalProcess"
}

// SystemApprovalWorkItem represents the _System_ApprovalWorkItem table (generated).
// Pending approval work items
type SystemApprovalWorkItem struct {
	ID string `json:"__sys_gen_id"`
	ProcessID string `json:"process_id"`
	FlowInstanceID *string `json:"flow_instance_id,omitempty"`
	FlowStepID *string `json:"flow_step_id,omitempty"`
	ObjectAPIName string `json:"object_api_name"`
	RecordID string `json:"record_id"`
	Status string `json:"status"`
	SubmittedByID *string `json:"submitted_by_id,omitempty"`
	SubmittedDate time.Time `json:"submitted_date"`
	ApproverID *string `json:"approver_id,omitempty"`
	ApprovedByID *string `json:"approved_by_id,omitempty"`
	ApprovedDate *time.Time `json:"approved_date,omitempty"`
	Comments *string `json:"comments,omitempty"`
	OwnerID *string `json:"__sys_gen_owner_id,omitempty"`
	CreatedByID *string `json:"__sys_gen_created_by_id,omitempty"`
	CreatedDate time.Time `json:"__sys_gen_created_date"`
	LastModifiedByID *string `json:"__sys_gen_last_modified_by_id,omitempty"`
	LastModifiedDate *time.Time `json:"__sys_gen_last_modified_date,omitempty"`
	IsDeleted bool `json:"__sys_gen_is_deleted"`
}

// GetTableName returns the database table name for SystemApprovalWorkItem.
func (SystemApprovalWorkItem) GetTableName() string {
	return "_System_ApprovalWorkItem"
}

// SystemAuditLog represents the _System_AuditLog table (generated).
// Field history tracking
type SystemAuditLog struct {
	ID string `json:"__sys_gen_id"`
	ObjectAPIName string `json:"object_api_name"`
	RecordID string `json:"record_id"`
	FieldName string `json:"field_name"`
	OldValue string `json:"old_value"`
	NewValue string `json:"new_value"`
	ChangedByID string `json:"changed_by_id"`
	ChangedAt time.Time `json:"changed_at"`
	CreatedDate time.Time `json:"__sys_gen_created_date"`
	LastModifiedDate time.Time `json:"__sys_gen_last_modified_date"`
}

// GetTableName returns the database table name for SystemAuditLog.
func (SystemAuditLog) GetTableName() string {
	return "_System_AuditLog"
}

// SystemAutoNumber represents the _System_AutoNumber table (generated).
// Auto-number sequence tracking
type SystemAutoNumber struct {
	ID string `json:"__sys_gen_id"`
	ObjectAPIName string `json:"object_api_name"`
	FieldAPIName string `json:"field_api_name"`
	DisplayFormat string `json:"display_format"`
	StartingNumber int `json:"starting_number"`
	CurrentNumber int `json:"current_number"`
	CreatedDate time.Time `json:"__sys_gen_created_date"`
	LastModifiedDate time.Time `json:"__sys_gen_last_modified_date"`
}

// GetTableName returns the database table name for SystemAutoNumber.
func (SystemAutoNumber) GetTableName() string {
	return "_System_AutoNumber"
}

// SystemComment represents the _System_Comment table (generated).
// User comments on records
type SystemComment struct {
	ID string `json:"__sys_gen_id"`
	ObjectAPIName string `json:"object_api_name"`
	RecordID string `json:"record_id"`
	Body string `json:"body"`
	CreatedByID string `json:"__sys_gen_created_by_id"`
	CreatedDate time.Time `json:"__sys_gen_created_date"`
	IsDeleted bool `json:"__sys_gen_is_deleted"`
	ParentCommentID *string `json:"parent_comment_id,omitempty"`
	IsResolved bool `json:"is_resolved"`
	LastModifiedDate time.Time `json:"__sys_gen_last_modified_date"`
}

// GetTableName returns the database table name for SystemComment.
func (SystemComment) GetTableName() string {
	return "_System_Comment"
}

// SystemConfig represents the _System_Config table (generated).
// System configuration settings
type SystemConfig struct {
	KeyName string `json:"key_name"`
	Value string `json:"value"`
	IsSecret bool `json:"is_secret"`
	Description string `json:"description"`
	CreatedDate time.Time `json:"__sys_gen_created_date"`
	LastModifiedDate time.Time `json:"__sys_gen_last_modified_date"`
}

// GetTableName returns the database table name for SystemConfig.
func (SystemConfig) GetTableName() string {
	return "_System_Config"
}

// SystemDashboard represents the _System_Dashboard table (generated).
// Dashboard configurations with widget-based layouts
type SystemDashboard struct {
	ID string `json:"__sys_gen_id"`
	Name string `json:"name"`
	Description string `json:"description"`
	Layout string `json:"layout"`
	Widgets json.RawMessage `json:"widgets"`
	CreatedDate time.Time `json:"__sys_gen_created_date"`
	OwnerID *string `json:"__sys_gen_owner_id,omitempty"`
	CreatedByID *string `json:"__sys_gen_created_by_id,omitempty"`
	LastModifiedByID *string `json:"__sys_gen_last_modified_by_id,omitempty"`
	IsDeleted bool `json:"__sys_gen_is_deleted"`
	LastModifiedDate time.Time `json:"__sys_gen_last_modified_date"`
}

// GetTableName returns the database table name for SystemDashboard.
func (SystemDashboard) GetTableName() string {
	return "_System_Dashboard"
}

// SystemEmailTemplate represents the _System_EmailTemplate table (generated).
// Email templates for notifications
type SystemEmailTemplate struct {
	ID string `json:"__sys_gen_id"`
	Name string `json:"name"`
	Subject string `json:"subject"`
	HTMLBody string `json:"html_body"`
	TextBody string `json:"text_body"`
	FromName string `json:"from_name"`
	FromEmail string `json:"from_email"`
	ReplyTo string `json:"reply_to"`
	IsActive bool `json:"is_active"`
	CreatedDate time.Time `json:"__sys_gen_created_date"`
	LastModifiedDate time.Time `json:"__sys_gen_last_modified_date"`
}

// GetTableName returns the database table name for SystemEmailTemplate.
func (SystemEmailTemplate) GetTableName() string {
	return "_System_EmailTemplate"
}

// SystemFeedItem represents the _System_FeedItem table (generated).
// Feed items for chatter and notifications
type SystemFeedItem struct {
	ID string `json:"__sys_gen_id"`
	ParentID string `json:"parent_id"`
	Type string `json:"type"`
	Body string `json:"body"`
	CreatedByID string `json:"__sys_gen_created_by_id"`
	CreatedDate time.Time `json:"__sys_gen_created_date"`
	LastModifiedDate time.Time `json:"__sys_gen_last_modified_date"`
}

// GetTableName returns the database table name for SystemFeedItem.
func (SystemFeedItem) GetTableName() string {
	return "_System_FeedItem"
}

// SystemField represents the _System_Field table (generated).
// Field metadata definitions
type SystemField struct {
	ID string `json:"__sys_gen_id"`
	ObjectID string `json:"object_id"`
	APIName string `json:"api_name"`
	Label string `json:"label"`
	Type string `json:"type"`
	Required bool `json:"required"`
	IsUnique bool `json:"is_unique"`
	IsSystem bool `json:"is_system"`
	IsNameField bool `json:"is_name_field"`
	Indexed bool `json:"indexed"`
	Options json.RawMessage `json:"options,omitempty"`
	ReferenceTo json.RawMessage `json:"reference_to,omitempty"`
	DeleteRule *string `json:"delete_rule,omitempty"`
	Formula *string `json:"formula,omitempty"`
	ReturnType *string `json:"return_type,omitempty"`
	DefaultValue *string `json:"default_value,omitempty"`
	HelpText *string `json:"help_text,omitempty"`
	Description *string `json:"description,omitempty"`
	TrackHistory bool `json:"track_history"`
	MinValue *float64 `json:"min_value,omitempty"`
	MaxValue *float64 `json:"max_value,omitempty"`
	MinLength *int `json:"min_length,omitempty"`
	MaxLength *int `json:"max_length,omitempty"`
	Regex *string `json:"regex,omitempty"`
	RegexMessage *string `json:"regex_message,omitempty"`
	Validator *string `json:"validator,omitempty"`
	ControllingField *string `json:"controlling_field,omitempty"`
	PicklistDependency json.RawMessage `json:"picklist_dependency,omitempty"`
	RollupConfig json.RawMessage `json:"rollup_config,omitempty"`
	IsMasterDetail bool `json:"is_master_detail"`
	IsPolymorphic bool `json:"is_polymorphic"`
	RelationshipName *string `json:"relationship_name,omitempty"`
	IsDeleted bool `json:"__sys_gen_is_deleted"`
	OwnerID *string `json:"__sys_gen_owner_id,omitempty"`
	CreatedByID *string `json:"__sys_gen_created_by_id,omitempty"`
	LastModifiedByID *string `json:"__sys_gen_last_modified_by_id,omitempty"`
	CreatedDate time.Time `json:"__sys_gen_created_date"`
	LastModifiedDate time.Time `json:"__sys_gen_last_modified_date"`
}

// GetTableName returns the database table name for SystemField.
func (SystemField) GetTableName() string {
	return "_System_Field"
}

// SystemFieldDependency represents the _System_FieldDependency table (generated).
// Field dependency rules
type SystemFieldDependency struct {
	ID string `json:"__sys_gen_id"`
	ControllingFieldID string `json:"controlling_field_id"`
	DependentFieldID string `json:"dependent_field_id"`
	ControllingValue string `json:"controlling_value"`
	DependentValues json.RawMessage `json:"dependent_values"`
	CreatedDate time.Time `json:"__sys_gen_created_date"`
	LastModifiedDate time.Time `json:"__sys_gen_last_modified_date"`
}

// GetTableName returns the database table name for SystemFieldDependency.
func (SystemFieldDependency) GetTableName() string {
	return "_System_FieldDependency"
}

// SystemFieldPerms represents the _System_FieldPerms table (generated).
// Field permissions for profiles
type SystemFieldPerms struct {
	ID string `json:"__sys_gen_id"`
	ProfileID *string `json:"profile_id,omitempty"`
	PermissionSetID *string `json:"permission_set_id,omitempty"`
	ObjectAPIName string `json:"object_api_name"`
	FieldAPIName string `json:"field_api_name"`
	Readable bool `json:"readable"`
	Editable bool `json:"editable"`
	CreatedDate time.Time `json:"__sys_gen_created_date"`
	LastModifiedDate time.Time `json:"__sys_gen_last_modified_date"`
}

// GetTableName returns the database table name for SystemFieldPerms.
func (SystemFieldPerms) GetTableName() string {
	return "_System_FieldPerms"
}

// SystemFile represents the _System_File table (generated).
// File attachments
type SystemFile struct {
	ID string `json:"__sys_gen_id"`
	ParentID string `json:"parent_id"`
	Name string `json:"name"`
	MimeType string `json:"mime_type"`
	SizeBytes int64 `json:"size_bytes"`
	StoragePath string `json:"storage_path"`
	CreatedByID string `json:"__sys_gen_created_by_id"`
	CreatedDate time.Time `json:"__sys_gen_created_date"`
	LastModifiedDate time.Time `json:"__sys_gen_last_modified_date"`
}

// GetTableName returns the database table name for SystemFile.
func (SystemFile) GetTableName() string {
	return "_System_File"
}

// SystemFlow represents the _System_Flow table (generated).
// Workflow automation definitions
type SystemFlow struct {
	ID string `json:"__sys_gen_id"`
	Name string `json:"name"`
	TriggerObject string `json:"trigger_object"`
	TriggerType string `json:"trigger_type"`
	TriggerCondition string `json:"trigger_condition"`
	ActionType string `json:"action_type"`
	ActionConfig json.RawMessage `json:"action_config"`
	FlowType string `json:"flow_type"`
	Description *string `json:"description,omitempty"`
	Status string `json:"status"`
	CreatedDate time.Time `json:"__sys_gen_created_date"`
	CreatedByID *string `json:"__sys_gen_created_by_id,omitempty"`
	LastModifiedByID *string `json:"__sys_gen_last_modified_by_id,omitempty"`
	OwnerID *string `json:"__sys_gen_owner_id,omitempty"`
	IsDeleted bool `json:"__sys_gen_is_deleted"`
	Schedule *string `json:"schedule,omitempty"`
	ScheduleTimezone *string `json:"schedule_timezone,omitempty"`
	LastRunAt *time.Time `json:"last_run_at,omitempty"`
	NextRunAt *time.Time `json:"next_run_at,omitempty"`
	IsRunning bool `json:"is_running"`
	LastModifiedDate time.Time `json:"__sys_gen_last_modified_date"`
}

// GetTableName returns the database table name for SystemFlow.
func (SystemFlow) GetTableName() string {
	return "_System_Flow"
}

// SystemFlowInstance represents the _System_FlowInstance table (generated).
// Tracks running and paused flow executions
type SystemFlowInstance struct {
	ID string `json:"__sys_gen_id"`
	FlowID string `json:"flow_id"`
	ObjectAPIName string `json:"object_api_name"`
	RecordID string `json:"record_id"`
	Status string `json:"status"`
	CurrentStepID *string `json:"current_step_id,omitempty"`
	ContextData json.RawMessage `json:"context_data,omitempty"`
	StartedDate time.Time `json:"started_date"`
	PausedDate *time.Time `json:"paused_date,omitempty"`
	CompletedDate *time.Time `json:"completed_date,omitempty"`
	OwnerID *string `json:"__sys_gen_owner_id,omitempty"`
	CreatedByID *string `json:"__sys_gen_created_by_id,omitempty"`
	CreatedDate time.Time `json:"__sys_gen_created_date"`
	LastModifiedByID *string `json:"__sys_gen_last_modified_by_id,omitempty"`
	LastModifiedDate *time.Time `json:"__sys_gen_last_modified_date,omitempty"`
	IsDeleted bool `json:"__sys_gen_is_deleted"`
}

// GetTableName returns the database table name for SystemFlowInstance.
func (SystemFlowInstance) GetTableName() string {
	return "_System_FlowInstance"
}

// SystemFlowStep represents the _System_FlowStep table (generated).
// Step definitions for multi-step flows
type SystemFlowStep struct {
	ID string `json:"__sys_gen_id"`
	FlowID string `json:"flow_id"`
	StepOrder int `json:"step_order"`
	StepName string `json:"step_name"`
	StepType string `json:"step_type"`
	ActionType *string `json:"action_type,omitempty"`
	ActionConfig json.RawMessage `json:"action_config,omitempty"`
	EntryCondition *string `json:"entry_condition,omitempty"`
	OnSuccessStep *string `json:"on_success_step,omitempty"`
	OnFailureStep *string `json:"on_failure_step,omitempty"`
	CreatedDate time.Time `json:"__sys_gen_created_date"`
	CreatedByID *string `json:"__sys_gen_created_by_id,omitempty"`
	LastModifiedByID *string `json:"__sys_gen_last_modified_by_id,omitempty"`
	OwnerID *string `json:"__sys_gen_owner_id,omitempty"`
	IsDeleted bool `json:"__sys_gen_is_deleted"`
	LastModifiedDate time.Time `json:"__sys_gen_last_modified_date"`
}

// GetTableName returns the database table name for SystemFlowStep.
func (SystemFlowStep) GetTableName() string {
	return "_System_FlowStep"
}

// SystemGroup represents the _System_Group table (generated).
// Groups and Queues
type SystemGroup struct {
	ID string `json:"__sys_gen_id"`
	Name string `json:"name"`
	Label string `json:"label"`
	Type string `json:"type"`
	Email *string `json:"email,omitempty"`
	CreatedDate time.Time `json:"__sys_gen_created_date"`
	IsDeleted bool `json:"__sys_gen_is_deleted"`
	LastModifiedDate time.Time `json:"__sys_gen_last_modified_date"`
}

// GetTableName returns the database table name for SystemGroup.
func (SystemGroup) GetTableName() string {
	return "_System_Group"
}

// SystemGroupMember represents the _System_GroupMember table (generated).
// Group membership
type SystemGroupMember struct {
	ID string `json:"__sys_gen_id"`
	GroupID string `json:"group_id"`
	UserID string `json:"user_id"`
	CreatedDate time.Time `json:"__sys_gen_created_date"`
	IsDeleted bool `json:"__sys_gen_is_deleted"`
	LastModifiedDate time.Time `json:"__sys_gen_last_modified_date"`
}

// GetTableName returns the database table name for SystemGroupMember.
func (SystemGroupMember) GetTableName() string {
	return "_System_GroupMember"
}

// SystemLayout represents the _System_Layout table (generated).
// Page layout configurations
type SystemLayout struct {
	ID string `json:"__sys_gen_id"`
	ObjectAPIName string `json:"object_api_name"`
	Config json.RawMessage `json:"config"`
	CreatedDate time.Time `json:"__sys_gen_created_date"`
	LastModifiedDate time.Time `json:"__sys_gen_last_modified_date"`
}

// GetTableName returns the database table name for SystemLayout.
func (SystemLayout) GetTableName() string {
	return "_System_Layout"
}

// SystemListView represents the _System_ListView table (generated).
// List view configurations
type SystemListView struct {
	ID string `json:"__sys_gen_id"`
	ObjectAPIName string `json:"object_api_name"`
	Label string `json:"label"`
	FilterExpr *string `json:"filter_expr,omitempty"`
	Fields json.RawMessage `json:"fields"`
	CreatedDate time.Time `json:"__sys_gen_created_date"`
	LastModifiedDate time.Time `json:"__sys_gen_last_modified_date"`
}

// GetTableName returns the database table name for SystemListView.
func (SystemListView) GetTableName() string {
	return "_System_ListView"
}

// SystemLog represents the _System_Log table (generated).
// System event logs
type SystemLog struct {
	ID string `json:"__sys_gen_id"`
	Timestamp time.Time `json:"timestamp"`
	Level string `json:"level"`
	Source string `json:"source"`
	Message string `json:"message"`
	Details *string `json:"details,omitempty"`
	CreatedDate time.Time `json:"__sys_gen_created_date"`
	LastModifiedDate time.Time `json:"__sys_gen_last_modified_date"`
}

// GetTableName returns the database table name for SystemLog.
func (SystemLog) GetTableName() string {
	return "_System_Log"
}

// SystemNotification represents the _System_Notification table (generated).
// User notifications
type SystemNotification struct {
	ID string `json:"__sys_gen_id"`
	RecipientID string `json:"recipient_id"`
	Title string `json:"title"`
	Body string `json:"body"`
	Link string `json:"link"`
	IsRead bool `json:"is_read"`
	NotificationType string `json:"notification_type"`
	CreatedDate time.Time `json:"__sys_gen_created_date"`
	LastModifiedDate time.Time `json:"__sys_gen_last_modified_date"`
}

// GetTableName returns the database table name for SystemNotification.
func (SystemNotification) GetTableName() string {
	return "_System_Notification"
}

// SystemObject represents the _System_Object table (generated).
// Object metadata definitions
type SystemObject struct {
	ID string `json:"__sys_gen_id"`
	APIName string `json:"api_name"`
	TableType string `json:"table_type"`
	Label string `json:"label"`
	PluralLabel *string `json:"plural_label,omitempty"`
	AppID *string `json:"app_id,omitempty"`
	Icon *string `json:"icon,omitempty"`
	Description string `json:"description"`
	ThemeColor *string `json:"theme_color,omitempty"`
	IsCustom bool `json:"is_custom"`
	SharingModel string `json:"sharing_model"`
	PathField *string `json:"path_field,omitempty"`
	ListFields json.RawMessage `json:"list_fields,omitempty"`
	IsDeleted bool `json:"__sys_gen_is_deleted"`
	OwnerID *string `json:"__sys_gen_owner_id,omitempty"`
	CreatedByID *string `json:"__sys_gen_created_by_id,omitempty"`
	LastModifiedByID *string `json:"__sys_gen_last_modified_by_id,omitempty"`
	CreatedDate time.Time `json:"__sys_gen_created_date"`
	LastModifiedDate time.Time `json:"__sys_gen_last_modified_date"`
}

// GetTableName returns the database table name for SystemObject.
func (SystemObject) GetTableName() string {
	return "_System_Object"
}

// SystemObjectPerms represents the _System_ObjectPerms table (generated).
// Object permissions for profiles
type SystemObjectPerms struct {
	ID string `json:"__sys_gen_id"`
	ProfileID *string `json:"profile_id,omitempty"`
	PermissionSetID *string `json:"permission_set_id,omitempty"`
	ObjectAPIName string `json:"object_api_name"`
	AllowRead bool `json:"allow_read"`
	AllowCreate bool `json:"allow_create"`
	AllowEdit bool `json:"allow_edit"`
	AllowDelete bool `json:"allow_delete"`
	ViewAll bool `json:"view_all"`
	ModifyAll bool `json:"modify_all"`
	CreatedDate time.Time `json:"__sys_gen_created_date"`
	LastModifiedDate time.Time `json:"__sys_gen_last_modified_date"`
}

// GetTableName returns the database table name for SystemObjectPerms.
func (SystemObjectPerms) GetTableName() string {
	return "_System_ObjectPerms"
}

// SystemOutboxEvent represents the _System_OutboxEvent table (generated).
// Transactional event outbox for guaranteed delivery
type SystemOutboxEvent struct {
	ID string `json:"__sys_gen_id"`
	EventType string `json:"event_type"`
	Payload json.RawMessage `json:"payload"`
	Status string `json:"status"`
	RetryCount int `json:"retry_count"`
	ErrorMessage *string `json:"error_message,omitempty"`
	ProcessedDate *time.Time `json:"processed_date,omitempty"`
	CreatedDate time.Time `json:"__sys_gen_created_date"`
	LastModifiedDate time.Time `json:"__sys_gen_last_modified_date"`
}

// GetTableName returns the database table name for SystemOutboxEvent.
func (SystemOutboxEvent) GetTableName() string {
	return "_System_OutboxEvent"
}

// SystemPermissionSet represents the _System_PermissionSet table (generated).
// Additive permission sets
type SystemPermissionSet struct {
	ID string `json:"__sys_gen_id"`
	Name string `json:"name"`
	Label string `json:"label"`
	Description string `json:"description"`
	IsActive bool `json:"is_active"`
	CreatedDate time.Time `json:"__sys_gen_created_date"`
	IsDeleted bool `json:"__sys_gen_is_deleted"`
	LastModifiedDate time.Time `json:"__sys_gen_last_modified_date"`
}

// GetTableName returns the database table name for SystemPermissionSet.
func (SystemPermissionSet) GetTableName() string {
	return "_System_PermissionSet"
}

// SystemPermissionSetAssignment represents the _System_PermissionSetAssignment table (generated).
// Assignment of permission sets to users
type SystemPermissionSetAssignment struct {
	ID string `json:"__sys_gen_id"`
	AssigneeID string `json:"assignee_id"`
	PermissionSetID string `json:"permission_set_id"`
	CreatedDate time.Time `json:"__sys_gen_created_date"`
	IsDeleted bool `json:"__sys_gen_is_deleted"`
	LastModifiedDate time.Time `json:"__sys_gen_last_modified_date"`
}

// GetTableName returns the database table name for SystemPermissionSetAssignment.
func (SystemPermissionSetAssignment) GetTableName() string {
	return "_System_PermissionSetAssignment"
}

// SystemProfile represents the _System_Profile table (generated).
// User profiles and permission sets
type SystemProfile struct {
	ID string `json:"__sys_gen_id"`
	Name string `json:"name"`
	Description string `json:"description"`
	IsActive bool `json:"is_active"`
	IsSystem bool `json:"is_system"`
	IsDeleted bool `json:"__sys_gen_is_deleted"`
	OwnerID *string `json:"__sys_gen_owner_id,omitempty"`
	CreatedByID *string `json:"__sys_gen_created_by_id,omitempty"`
	LastModifiedByID *string `json:"__sys_gen_last_modified_by_id,omitempty"`
	CreatedDate time.Time `json:"__sys_gen_created_date"`
	LastModifiedDate time.Time `json:"__sys_gen_last_modified_date"`
}

// GetTableName returns the database table name for SystemProfile.
func (SystemProfile) GetTableName() string {
	return "_System_Profile"
}

// SystemProfileLayout represents the _System_ProfileLayout table (generated).
// Profile to layout assignments
type SystemProfileLayout struct {
	ProfileID string `json:"profile_id"`
	ObjectAPIName string `json:"object_api_name"`
	LayoutID string `json:"layout_id"`
	CreatedDate time.Time `json:"__sys_gen_created_date"`
	LastModifiedDate time.Time `json:"__sys_gen_last_modified_date"`
}

// GetTableName returns the database table name for SystemProfileLayout.
func (SystemProfileLayout) GetTableName() string {
	return "_System_ProfileLayout"
}

// SystemRecent represents the _System_Recent table (generated).
// Recently viewed records
type SystemRecent struct {
	ID string `json:"__sys_gen_id"`
	UserID string `json:"user_id"`
	ObjectAPIName string `json:"object_api_name"`
	RecordID string `json:"record_id"`
	RecordName string `json:"record_name"`
	Timestamp time.Time `json:"timestamp"`
	CreatedDate time.Time `json:"__sys_gen_created_date"`
	LastModifiedDate time.Time `json:"__sys_gen_last_modified_date"`
}

// GetTableName returns the database table name for SystemRecent.
func (SystemRecent) GetTableName() string {
	return "_System_Recent"
}

// SystemRecordShare represents the _System_RecordShare table (generated).
// Manual record sharing with users or groups
type SystemRecordShare struct {
	ID string `json:"__sys_gen_id"`
	ObjectAPIName string `json:"object_api_name"`
	RecordID string `json:"record_id"`
	ShareWithUserID *string `json:"share_with_user_id,omitempty"`
	ShareWithGroupID *string `json:"share_with_group_id,omitempty"`
	AccessLevel string `json:"access_level"`
	Reason string `json:"reason"`
	CreatedByID *string `json:"__sys_gen_created_by_id,omitempty"`
	CreatedDate time.Time `json:"__sys_gen_created_date"`
	LastModifiedByID *string `json:"__sys_gen_last_modified_by_id,omitempty"`
	LastModifiedDate *time.Time `json:"__sys_gen_last_modified_date,omitempty"`
	IsDeleted bool `json:"__sys_gen_is_deleted"`
}

// GetTableName returns the database table name for SystemRecordShare.
func (SystemRecordShare) GetTableName() string {
	return "_System_RecordShare"
}

// SystemRecordType represents the _System_RecordType table (generated).
// Record type configurations
type SystemRecordType struct {
	ID string `json:"__sys_gen_id"`
	ObjectID string `json:"object_id"`
	Name string `json:"name"`
	Description string `json:"description"`
	IsActive bool `json:"is_active"`
	IsMaster bool `json:"is_master"`
	IsDeleted bool `json:"__sys_gen_is_deleted"`
	CreatedDate time.Time `json:"__sys_gen_created_date"`
	LastModifiedDate time.Time `json:"__sys_gen_last_modified_date"`
}

// GetTableName returns the database table name for SystemRecordType.
func (SystemRecordType) GetTableName() string {
	return "_System_RecordType"
}

// SystemRecycleBin represents the _System_RecycleBin table (generated).
// Recycle bin for soft-deleted records
type SystemRecycleBin struct {
	ID string `json:"__sys_gen_id"`
	RecordID string `json:"record_id"`
	ObjectAPIName string `json:"object_api_name"`
	RecordName string `json:"record_name"`
	DeletedBy string `json:"deleted_by"`
	DeletedDate time.Time `json:"deleted_date"`
	CreatedDate time.Time `json:"__sys_gen_created_date"`
	LastModifiedDate time.Time `json:"__sys_gen_last_modified_date"`
}

// GetTableName returns the database table name for SystemRecycleBin.
func (SystemRecycleBin) GetTableName() string {
	return "_System_RecycleBin"
}

// SystemRelationship represents the _System_Relationship table (generated).
// Object relationship definitions
type SystemRelationship struct {
	ID string `json:"__sys_gen_id"`
	ChildObjectAPIName string `json:"child_object_api_name"`
	ParentObjectAPIName string `json:"parent_object_api_name"`
	FieldAPIName string `json:"field_api_name"`
	RelationshipName string `json:"relationship_name"`
	RelationshipType string `json:"relationship_type"`
	CascadeDelete bool `json:"cascade_delete"`
	RestrictedDelete bool `json:"restricted_delete"`
	RelatedListLabel string `json:"related_list_label"`
	RelatedListFields string `json:"related_list_fields"`
	CreatedDate time.Time `json:"__sys_gen_created_date"`
	LastModifiedDate time.Time `json:"__sys_gen_last_modified_date"`
}

// GetTableName returns the database table name for SystemRelationship.
func (SystemRelationship) GetTableName() string {
	return "_System_Relationship"
}

// SystemRole represents the _System_Role table (generated).
// Role hierarchy for access control
type SystemRole struct {
	ID string `json:"__sys_gen_id"`
	Name string `json:"name"`
	Description string `json:"description"`
	ParentRoleID *string `json:"parent_role_id,omitempty"`
	IsActive bool `json:"is_active"`
	IsDeleted bool `json:"__sys_gen_is_deleted"`
	OwnerID *string `json:"__sys_gen_owner_id,omitempty"`
	CreatedByID *string `json:"__sys_gen_created_by_id,omitempty"`
	LastModifiedByID *string `json:"__sys_gen_last_modified_by_id,omitempty"`
	CreatedDate time.Time `json:"__sys_gen_created_date"`
	LastModifiedDate time.Time `json:"__sys_gen_last_modified_date"`
}

// GetTableName returns the database table name for SystemRole.
func (SystemRole) GetTableName() string {
	return "_System_Role"
}

// SystemSession represents the _System_Session table (generated).
// User authentication sessions
type SystemSession struct {
	ID string `json:"__sys_gen_id"`
	UserID string `json:"user_id"`
	Token string `json:"token"`
	ExpiresAt time.Time `json:"expires_at"`
	LastActivity time.Time `json:"last_activity"`
	IPAddress string `json:"ip_address"`
	UserAgent string `json:"user_agent"`
	IsRevoked bool `json:"is_revoked"`
	CreatedDate time.Time `json:"__sys_gen_created_date"`
	LastModifiedDate time.Time `json:"__sys_gen_last_modified_date"`
}

// GetTableName returns the database table name for SystemSession.
func (SystemSession) GetTableName() string {
	return "_System_Session"
}

// SystemSetupPage represents the _System_SetupPage table (generated).
// Setup page definitions
type SystemSetupPage struct {
	ID string `json:"__sys_gen_id"`
	Label string `json:"label"`
	Icon *string `json:"icon,omitempty"`
	ComponentName string `json:"component_name"`
	Category string `json:"category"`
	PageOrder int `json:"page_order"`
	PermissionRequired *string `json:"permission_required,omitempty"`
	IsEnabled bool `json:"is_enabled"`
	Description *string `json:"description,omitempty"`
	Path *string `json:"path,omitempty"`
	CreatedDate time.Time `json:"__sys_gen_created_date"`
	LastModifiedDate time.Time `json:"__sys_gen_last_modified_date"`
}

// GetTableName returns the database table name for SystemSetupPage.
func (SystemSetupPage) GetTableName() string {
	return "_System_SetupPage"
}

// SystemSharingRule represents the _System_SharingRule table (generated).
// Record sharing rules
type SystemSharingRule struct {
	ID string `json:"__sys_gen_id"`
	ObjectAPIName string `json:"object_api_name"`
	Name string `json:"name"`
	Criteria string `json:"criteria"`
	AccessLevel string `json:"access_level"`
	ShareWithRoleID *string `json:"share_with_role_id,omitempty"`
	ShareWithGroupID *string `json:"share_with_group_id,omitempty"`
	IsDeleted bool `json:"__sys_gen_is_deleted"`
	OwnerID *string `json:"__sys_gen_owner_id,omitempty"`
	CreatedByID *string `json:"__sys_gen_created_by_id,omitempty"`
	LastModifiedByID *string `json:"__sys_gen_last_modified_by_id,omitempty"`
	CreatedDate time.Time `json:"__sys_gen_created_date"`
	LastModifiedDate time.Time `json:"__sys_gen_last_modified_date"`
}

// GetTableName returns the database table name for SystemSharingRule.
func (SystemSharingRule) GetTableName() string {
	return "_System_SharingRule"
}

// SystemSystemLog represents the _System_SystemLog table (generated).
// System operation logs
type SystemSystemLog struct {
	ID string `json:"__sys_gen_id"`
	Timestamp time.Time `json:"timestamp"`
	Level string `json:"level"`
	Source string `json:"source"`
	Message string `json:"message"`
	Details *string `json:"details,omitempty"`
}

// GetTableName returns the database table name for SystemSystemLog.
func (SystemSystemLog) GetTableName() string {
	return "_System_SystemLog"
}

// SystemTable represents the _System_Table table (generated).
// Meta-metadata registry cataloging all tables
type SystemTable struct {
	ID string `json:"__sys_gen_id"`
	TableName string `json:"table_name"`
	TableType string `json:"table_type"`
	Category string `json:"category"`
	Description string `json:"description"`
	IsManaged bool `json:"is_managed"`
	SchemaVersion string `json:"schema_version"`
	CreatedBy string `json:"created_by"`
	CreatedDate time.Time `json:"__sys_gen_created_date"`
	LastModifiedDate time.Time `json:"__sys_gen_last_modified_date"`
}

// GetTableName returns the database table name for SystemTable.
func (SystemTable) GetTableName() string {
	return "_System_Table"
}

// SystemTeamMember represents the _System_TeamMember table (generated).
// Generic record team members
type SystemTeamMember struct {
	ID string `json:"__sys_gen_id"`
	ObjectAPIName string `json:"object_api_name"`
	RecordID string `json:"record_id"`
	UserID string `json:"user_id"`
	TeamRole string `json:"team_role"`
	AccessLevel string `json:"access_level"`
	CreatedByID *string `json:"__sys_gen_created_by_id,omitempty"`
	CreatedDate time.Time `json:"__sys_gen_created_date"`
	LastModifiedByID *string `json:"__sys_gen_last_modified_by_id,omitempty"`
	LastModifiedDate *time.Time `json:"__sys_gen_last_modified_date,omitempty"`
	IsDeleted bool `json:"__sys_gen_is_deleted"`
}

// GetTableName returns the database table name for SystemTeamMember.
func (SystemTeamMember) GetTableName() string {
	return "_System_TeamMember"
}

// SystemTheme represents the _System_Theme table (generated).
// Visual theme configurations
type SystemTheme struct {
	ID string `json:"__sys_gen_id"`
	Name string `json:"name"`
	IsActive bool `json:"is_active"`
	Colors json.RawMessage `json:"colors"`
	Density string `json:"density"`
	LogoURL *string `json:"logo_url,omitempty"`
	CreatedDate time.Time `json:"__sys_gen_created_date"`
	LastModifiedDate time.Time `json:"__sys_gen_last_modified_date"`
}

// GetTableName returns the database table name for SystemTheme.
func (SystemTheme) GetTableName() string {
	return "_System_Theme"
}

// SystemUIComponent represents the _System_UIComponent table (generated).
// Registered UI components
type SystemUIComponent struct {
	ID string `json:"__sys_gen_id"`
	Name string `json:"name"`
	Type string `json:"type"`
	IsEmbeddable bool `json:"is_embeddable"`
	Description string `json:"description"`
	ComponentPath *string `json:"component_path,omitempty"`
	CreatedDate time.Time `json:"__sys_gen_created_date"`
	LastModifiedDate time.Time `json:"__sys_gen_last_modified_date"`
}

// GetTableName returns the database table name for SystemUIComponent.
func (SystemUIComponent) GetTableName() string {
	return "_System_UIComponent"
}

// SystemUser represents the _System_User table (generated).
// System users
type SystemUser struct {
	ID string `json:"__sys_gen_id"`
	Username string `json:"username"`
	Email string `json:"email"`
	Password string `json:"-"`
	FirstName string `json:"first_name"`
	LastName string `json:"last_name"`
	Phone *string `json:"phone,omitempty"`
	ProfileID string `json:"profile_id"`
	RoleID *string `json:"role_id,omitempty"`
	IsActive bool `json:"is_active"`
	IsDeleted bool `json:"__sys_gen_is_deleted"`
	OwnerID *string `json:"__sys_gen_owner_id,omitempty"`
	CreatedByID *string `json:"__sys_gen_created_by_id,omitempty"`
	LastModifiedByID *string `json:"__sys_gen_last_modified_by_id,omitempty"`
	LastLoginDate *time.Time `json:"last_login_date,omitempty"`
	CreatedDate time.Time `json:"__sys_gen_created_date"`
	LastModifiedDate time.Time `json:"__sys_gen_last_modified_date"`
}

// GetTableName returns the database table name for SystemUser.
func (SystemUser) GetTableName() string {
	return "_System_User"
}

// SystemValidation represents the _System_Validation table (generated).
// Validation rule definitions
type SystemValidation struct {
	ID string `json:"__sys_gen_id"`
	ObjectAPIName string `json:"object_api_name"`
	Name string `json:"name"`
	Active bool `json:"active"`
	Condition string `json:"condition"`
	ErrorMessage string `json:"error_message"`
	CreatedDate time.Time `json:"__sys_gen_created_date"`
	LastModifiedDate time.Time `json:"__sys_gen_last_modified_date"`
}

// GetTableName returns the database table name for SystemValidation.
func (SystemValidation) GetTableName() string {
	return "_System_Validation"
}

// SystemWebhook represents the _System_Webhook table (generated).
// External webhook configurations
type SystemWebhook struct {
	ID string `json:"__sys_gen_id"`
	Name string `json:"name"`
	URL string `json:"url"`
	Method string `json:"method"`
	Headers string `json:"headers"`
	AuthType string `json:"auth_type"`
	AuthConfig string `json:"auth_config"`
	IsActive bool `json:"is_active"`
	CreatedDate time.Time `json:"__sys_gen_created_date"`
	LastModifiedDate time.Time `json:"__sys_gen_last_modified_date"`
}

// GetTableName returns the database table name for SystemWebhook.
func (SystemWebhook) GetTableName() string {
	return "_System_Webhook"
}

